// AUTO-GENERATED by scripts/bundle-edge-functions.mjs — do not edit by hand.
// Paste this whole file as the Edge Function body in the Supabase dashboard.


// supabase/functions/tradovate-dashboard/index.ts
import { serve } from "https://deno.land/std@0.190.0/http/server.ts";

// supabase/functions/_shared/tradovate/auth.ts
import {
  createClient
} from "https://esm.sh/@supabase/supabase-js@2.45.0";
var UnauthorizedError = class extends Error {
  constructor() {
    super("unauthorized");
    this.name = "UnauthorizedError";
  }
};
async function requireUser(req) {
  const auth = req.headers.get("Authorization") ?? "";
  if (!auth.startsWith("Bearer ")) throw new UnauthorizedError();
  const token = auth.slice("Bearer ".length);
  const userClient = createClient(
    Deno.env.get("SUPABASE_URL") ?? "",
    Deno.env.get("SUPABASE_ANON_KEY") ?? "",
    { global: { headers: { Authorization: auth } } }
  );
  const { data, error } = await userClient.auth.getUser(token);
  if (error || !data?.user) throw new UnauthorizedError();
  const admin = createClient(
    Deno.env.get("SUPABASE_URL") ?? "",
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
    { auth: { autoRefreshToken: false, persistSession: false } }
  );
  return { user: { id: data.user.id, email: data.user.email }, admin };
}
var corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS"
};
function json(body, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" }
  });
}

// supabase/functions/_shared/tradovate/crypto.ts
var KEY_VERSION = 1;
var IV_BYTES = 12;
var TAG_BYTES = 16;
var KEY_BYTES = 32;
var EncryptionConfigError = class extends Error {
  constructor(message) {
    super(message);
    this.name = "EncryptionConfigError";
  }
};
var DecryptionError = class extends Error {
  constructor(message) {
    super(message);
    this.name = "DecryptionError";
  }
};
function isEncryptionConfigured() {
  return (Deno.env.get("TRADOVATE_ENCRYPTION_KEY") ?? "").length > 0;
}
function base64ToBytes(b64) {
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}
function bytesToBase64(bytes) {
  let bin = "";
  for (const b of bytes) bin += String.fromCharCode(b);
  return btoa(bin);
}
function hexToBytes(hex) {
  const clean = hex.trim().toLowerCase();
  if (!/^[0-9a-f]+$/.test(clean) || clean.length % 2 !== 0) return null;
  const out = new Uint8Array(clean.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(clean.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}
function tryRawKey(secret) {
  const hex = hexToBytes(secret);
  if (hex && hex.length === KEY_BYTES) return hex;
  try {
    const b64 = base64ToBytes(secret);
    if (b64.length === KEY_BYTES) return b64;
  } catch {
  }
  return null;
}
async function importAesKey(secret) {
  if (!secret) {
    throw new EncryptionConfigError(
      "TRADOVATE_ENCRYPTION_KEY is not set"
    );
  }
  let raw = tryRawKey(secret);
  if (!raw) {
    const digest = await crypto.subtle.digest(
      "SHA-256",
      new TextEncoder().encode(secret)
    );
    raw = new Uint8Array(digest);
  }
  return await crypto.subtle.importKey(
    "raw",
    raw,
    { name: "AES-GCM" },
    false,
    ["encrypt", "decrypt"]
  );
}
async function encryptCredentials(creds, secret) {
  const key = await importAesKey(secret);
  const iv = crypto.getRandomValues(new Uint8Array(IV_BYTES));
  const plaintext = new TextEncoder().encode(JSON.stringify(creds));
  const sealed = new Uint8Array(
    await crypto.subtle.encrypt(
      { name: "AES-GCM", iv, tagLength: 128 },
      key,
      plaintext
    )
  );
  const tag = sealed.slice(sealed.length - TAG_BYTES);
  const body = sealed.slice(0, sealed.length - TAG_BYTES);
  return {
    ciphertext: bytesToBase64(body),
    iv: bytesToBase64(iv),
    authTag: bytesToBase64(tag),
    keyVersion: KEY_VERSION
  };
}
async function decryptCredentials(parts, secret) {
  const key = await importAesKey(secret);
  const iv = base64ToBytes(parts.iv);
  const tag = base64ToBytes(parts.authTag);
  const body = base64ToBytes(parts.ciphertext);
  if (iv.length !== IV_BYTES || tag.length !== TAG_BYTES) {
    throw new DecryptionError("malformed credential envelope");
  }
  const sealed = new Uint8Array(body.length + tag.length);
  sealed.set(body, 0);
  sealed.set(tag, body.length);
  let plaintext;
  try {
    plaintext = await crypto.subtle.decrypt(
      { name: "AES-GCM", iv, tagLength: 128 },
      key,
      sealed
    );
  } catch {
    throw new DecryptionError(
      "could not decrypt credentials (wrong key or tampered ciphertext)"
    );
  }
  return JSON.parse(new TextDecoder().decode(plaintext));
}
function redact(value) {
  const s = typeof value === "string" ? value : JSON.stringify(value ?? "");
  return s.replace(/Bearer\s+[A-Za-z0-9._~+/-]+=*/gi, "Bearer [REDACTED]").replace(/(password|passwd|pwd)"?\s*[:=]\s*"?[^",}\s]+/gi, "$1=[REDACTED]").replace(/(accessToken|access_token|token|sec|cid|authorization)"?\s*[:=]\s*"?[^",}\s]+/gi, "$1=[REDACTED]");
}

// supabase/functions/_shared/tradovate/credentialStore.ts
var CredentialStoreError = class extends Error {
  constructor(code, message) {
    super(message ?? code);
    this.code = code;
    this.name = "CredentialStoreError";
  }
};
async function loadCredentials(admin, userId, integrationId) {
  if (!isEncryptionConfigured()) {
    throw new CredentialStoreError("encryption_not_configured");
  }
  const { data: integ, error: integErr } = await admin.from("integrations").select(
    "id, user_id, environment, tradovate_account_id, tradovate_user_id, account_spec, label, status, last_fill_id, token_expires_at"
  ).eq("id", integrationId).eq("user_id", userId).maybeSingle();
  if (integErr) throw new CredentialStoreError("integration_read_failed", integErr.message);
  if (!integ) throw new CredentialStoreError("integration_not_found");
  const { data: cred, error: credErr } = await admin.from("integration_credentials").select("ciphertext, iv, auth_tag, key_version").eq("integration_id", integrationId).maybeSingle();
  if (credErr) throw new CredentialStoreError("credential_read_failed", credErr.message);
  if (!cred) throw new CredentialStoreError("credentials_missing");
  const credentials = await decryptCredentials({
    ciphertext: cred.ciphertext,
    iv: cred.iv,
    authTag: cred.auth_tag,
    keyVersion: cred.key_version
  }, Deno.env.get("TRADOVATE_ENCRYPTION_KEY") ?? "");
  return { integration: integ, credentials };
}
async function storeSessionToken(admin, userId, integrationId, token) {
  try {
    const { integration, credentials } = await loadCredentials(admin, userId, integrationId);
    const merged = {
      ...credentials,
      accessToken: token.accessToken,
      accessTokenExpiresAt: token.expirationTime
    };
    const parts = await encryptCredentials(merged, Deno.env.get("TRADOVATE_ENCRYPTION_KEY") ?? "");
    await admin.from("integration_credentials").update({
      ciphertext: parts.ciphertext,
      iv: parts.iv,
      auth_tag: parts.authTag,
      key_version: parts.keyVersion
    }).eq("integration_id", integration.id);
    await admin.from("integrations").update({ token_expires_at: token.expirationTime }).eq("id", integrationId).eq("user_id", userId);
  } catch {
  }
}
async function listIntegrations(admin, userId) {
  const { data, error } = await admin.from("integrations").select(
    "id, user_id, environment, tradovate_account_id, tradovate_user_id, account_spec, label, status, last_fill_id, token_expires_at"
  ).eq("user_id", userId).neq("status", "revoked").order("created_at", { ascending: false });
  if (error) throw new CredentialStoreError("integration_list_failed", error.message);
  return data ?? [];
}
async function readSnapshot(admin, integrationId) {
  const { data, error } = await admin.from("tradovate_account_snapshots").select("payload, warnings, fetched_at").eq("integration_id", integrationId).maybeSingle();
  if (error) throw new CredentialStoreError("snapshot_read_failed", error.message);
  if (!data) return null;
  return {
    payload: data.payload,
    warnings: Array.isArray(data.warnings) ? data.warnings : [],
    fetched_at: String(data.fetched_at)
  };
}
async function writeSnapshot(admin, integrationId, payload, warnings) {
  const { error } = await admin.from("tradovate_account_snapshots").upsert({
    integration_id: integrationId,
    payload,
    warnings,
    fetched_at: (/* @__PURE__ */ new Date()).toISOString()
  }, { onConflict: "integration_id" });
  if (error) throw new CredentialStoreError("snapshot_write_failed", error.message);
}

// supabase/functions/_shared/tradovate/rateLimiter.ts
var CircuitOpenError = class extends Error {
  constructor(retryAfterMs) {
    super(`rate-limit circuit open for another ${retryAfterMs}ms`);
    this.retryAfterMs = retryAfterMs;
    this.name = "CircuitOpenError";
  }
};
var SECOND = 1e3;
var MINUTE = 60 * SECOND;
var HOUR = 60 * MINUTE;
var defaultSleep = (ms) => new Promise((resolve) => setTimeout(resolve, Math.max(0, ms)));
function parseTimePenalty(body) {
  if (!body || typeof body !== "object") return null;
  const rec = body;
  const hasTicket = "p-ticket" in rec;
  const hasTime = "p-time" in rec;
  const hasCaptcha = "p-captcha" in rec;
  if (!hasTicket && !hasTime && !hasCaptcha) return null;
  const rawTime = rec["p-time"];
  const waitSeconds = typeof rawTime === "number" && Number.isFinite(rawTime) ? Math.max(0, rawTime) : 0;
  const ticket = typeof rec["p-ticket"] === "string" ? rec["p-ticket"] : null;
  const captcha = rec["p-captcha"] === true;
  return { ticket, waitSeconds, captcha };
}
var TradovateRateLimiter = class {
  perSecond;
  perMinute;
  perHour;
  baseBackoffMs;
  maxBackoffMs;
  captchaCircuitMs;
  rateLimitCircuitMs;
  sleep;
  now;
  random;
  /** Timestamps (ms) of accepted requests within the last hour. */
  history = [];
  circuitOpenUntil = 0;
  /** Consecutive plain-429 counter, reset on success. */
  consecutive429 = 0;
  constructor(opts = {}) {
    this.perSecond = opts.requestsPerSecond ?? 4;
    this.perMinute = opts.requestsPerMinute ?? 60;
    this.perHour = opts.requestsPerHour ?? 4500;
    this.baseBackoffMs = opts.baseBackoffMs ?? 500;
    this.maxBackoffMs = opts.maxBackoffMs ?? 3e4;
    this.captchaCircuitMs = opts.captchaCircuitMs ?? HOUR;
    this.rateLimitCircuitMs = opts.rateLimitCircuitMs ?? MINUTE;
    this.sleep = opts.sleep ?? defaultSleep;
    this.now = opts.now ?? (() => Date.now());
    this.random = opts.random ?? Math.random;
  }
  /** Throw CircuitOpenError while a p-captcha / repeated-429 circuit is open. */
  assertCircuitClosed() {
    const remaining = this.circuitOpenUntil - this.now();
    if (remaining > 0) throw new CircuitOpenError(remaining);
  }
  isCircuitOpen() {
    return this.circuitOpenUntil > this.now();
  }
  /** Wait until all three rolling windows allow one more request. */
  async waitForSlot() {
    this.assertCircuitClosed();
    for (; ; ) {
      const now = this.now();
      this.history = this.history.filter((t) => now - t < HOUR);
      const waits = [
        this.windowWait(now, SECOND, this.perSecond),
        this.windowWait(now, MINUTE, this.perMinute),
        this.windowWait(now, HOUR, this.perHour)
      ];
      const wait = Math.max(0, ...waits);
      if (wait <= 0) break;
      await this.sleep(wait);
      this.assertCircuitClosed();
    }
    this.history.push(this.now());
  }
  windowWait(now, windowMs, limit) {
    const inWindow = this.history.filter((t) => now - t < windowMs);
    if (inWindow.length < limit) return 0;
    const oldest = Math.min(...inWindow);
    return oldest + windowMs - now;
  }
  /** Exponential backoff with jitter for a plain 429. */
  async backoffFor429() {
    this.consecutive429 += 1;
    if (this.consecutive429 >= 5) {
      this.circuitOpenUntil = this.now() + this.rateLimitCircuitMs;
    }
    const exp = Math.min(
      this.maxBackoffMs,
      this.baseBackoffMs * 2 ** (this.consecutive429 - 1)
    );
    const jitter = Math.floor(this.random() * (exp / 2));
    const wait = exp + jitter;
    await this.sleep(wait);
    return wait;
  }
  /**
   * Handle a p-time / p-ticket penalty. Returns the ticket the caller must
   * echo back in the request body. Opens the circuit (and throws) on captcha.
   */
  async handlePenalty(penalty) {
    if (penalty.captcha) {
      this.circuitOpenUntil = this.now() + this.captchaCircuitMs;
      throw new CircuitOpenError(this.captchaCircuitMs);
    }
    if (penalty.waitSeconds > 0) {
      await this.sleep(penalty.waitSeconds * SECOND);
    }
    return penalty.ticket;
  }
  /** Reset the consecutive-429 counter after any successful call. */
  onSuccess() {
    this.consecutive429 = 0;
  }
  /** Test/diagnostic snapshot; contains no credentials. */
  snapshot() {
    return {
      historyLength: this.history.length,
      consecutive429: this.consecutive429,
      circuitOpenUntil: this.circuitOpenUntil,
      circuitOpen: this.isCircuitOpen()
    };
  }
};
function createDefaultLimiter(opts = {}) {
  return new TradovateRateLimiter({
    requestsPerSecond: 4,
    requestsPerMinute: 60,
    requestsPerHour: 4500,
    ...opts
  });
}

// supabase/functions/_shared/tradovate/http.ts
var TradovateHttpError = class extends Error {
  constructor(status, body, message) {
    super(message);
    this.status = status;
    this.body = body;
    this.name = "TradovateHttpError";
  }
};
async function requestJson(opts) {
  const fetchImpl = opts.fetchImpl ?? fetch;
  const maxAttempts = opts.maxAttempts ?? 6;
  const method = opts.method ?? "POST";
  let body = opts.body ?? null;
  let attempts = 0;
  for (; ; ) {
    attempts += 1;
    opts.limiter.assertCircuitClosed();
    await opts.limiter.waitForSlot();
    const res = await fetchImpl(opts.url, {
      method,
      headers: {
        "Content-Type": "application/json",
        ...opts.headers ?? {}
      },
      body: body === null ? void 0 : JSON.stringify(body),
      signal: opts.signal
    });
    if (res.status === 429) {
      const parsed = await safeJson(res);
      const penalty = parseTimePenalty(parsed);
      if (penalty && !penalty.captcha && attempts < maxAttempts) {
        const ticket = await opts.limiter.handlePenalty(penalty);
        if (ticket) {
          body = { ...body ?? {}, "p-ticket": ticket };
        }
        continue;
      }
      if (penalty && penalty.captcha) {
        await opts.limiter.handlePenalty(penalty);
      }
      if (attempts < maxAttempts) {
        await opts.limiter.backoffFor429();
        continue;
      }
      throw new TradovateHttpError(
        429,
        parsed,
        "Tradovate rate limit persisted beyond retry budget"
      );
    }
    if (!res.ok) {
      throw new TradovateHttpError(
        res.status,
        await safeJson(res),
        `Tradovate HTTP ${res.status}`
      );
    }
    opts.limiter.onSuccess();
    return await safeJson(res);
  }
}
async function safeJson(res) {
  const text = await res.text();
  if (!text) return null;
  try {
    return JSON.parse(text);
  } catch {
    return text;
  }
}

// supabase/functions/_shared/tradovate/appCredentials.ts
function resolveAppCredentials(clientCid, clientSec, env = (k) => Deno.env.get(k)) {
  const cid = clientCid?.trim() || env("TRADOVATE_APP_CID")?.trim() || void 0;
  const sec = clientSec?.trim() || env("TRADOVATE_APP_SECRET")?.trim() || void 0;
  const source = clientCid || clientSec ? "client" : cid || sec ? "server" : "none";
  return {
    cid,
    sec,
    appId: env("TRADOVATE_APP_ID")?.trim() || "Braxel",
    appVersion: env("TRADOVATE_APP_VERSION")?.trim() || "1.3.0",
    source
  };
}

// supabase/functions/_shared/tradovate/authService.ts
var TRADOVATE_HOSTS = {
  demo: "https://demo.tradovateapi.com/v1",
  live: "https://live.tradovateapi.com/v1"
};
var TOKEN_RENEW_MARGIN_MS = 5 * 60 * 1e3;
function hostFor(env) {
  return TRADOVATE_HOSTS[env];
}
function needsRenewal(expirationTime, nowMs = Date.now(), marginMs = TOKEN_RENEW_MARGIN_MS) {
  if (!expirationTime) return true;
  const expiry = Date.parse(expirationTime);
  if (!Number.isFinite(expiry)) return true;
  return expiry - nowMs <= marginMs;
}
async function authenticate(opts) {
  const limiter = opts.limiter ?? createDefaultLimiter();
  const { credentials, environment } = opts;
  const url = `${hostFor(environment)}/auth/accesstokenrequest`;
  const app = resolveAppCredentials(credentials.cid, credentials.sec);
  const body = {
    name: credentials.name,
    password: credentials.password,
    appId: credentials.appId ?? app.appId,
    appVersion: credentials.appVersion ?? app.appVersion,
    deviceId: credentials.deviceId ?? "braxel-terminal"
  };
  if (app.cid) body.cid = app.cid;
  if (app.sec) body.sec = app.sec;
  try {
    const data = await requestJson({
      url,
      limiter,
      fetchImpl: opts.fetchImpl,
      body
    });
    const accessToken = typeof data?.accessToken === "string" ? data.accessToken : null;
    if (!accessToken) {
      const text = extractErrorText(data);
      if (text && /incorrect username or password|invalid (username|password|credentials)|bad credentials/i.test(text)) {
        return { ok: false, code: "invalid_credentials", message: text };
      }
      if (text && /api access|not enabled|entitlement|subscription|not entitled/i.test(text)) {
        return { ok: false, code: "api_disabled", message: text };
      }
      return {
        ok: false,
        code: "unexpected",
        message: text ?? "Tradovate returned no access token"
      };
    }
    return {
      ok: true,
      accessToken,
      expirationTime: String(data.expirationTime ?? ""),
      userId: Number(data.userId ?? 0),
      name: String(data.name ?? credentials.name)
    };
  } catch (err) {
    return classifyAuthError(err);
  }
}
function classifyAuthError(err) {
  if (err instanceof CircuitOpenError) {
    return {
      ok: false,
      code: "circuit_open",
      message: "Tradovate asked for a captcha; retry in about an hour",
      retryAfterMs: err.retryAfterMs
    };
  }
  if (err instanceof TradovateHttpError) {
    const text = extractErrorText(err.body);
    if (err.status === 401) {
      return {
        ok: false,
        code: "invalid_credentials",
        message: text ?? "Tradovate rejected the username or password"
      };
    }
    if (err.status === 403 || /api access|not enabled|entitlement/i.test(text ?? "")) {
      return {
        ok: false,
        code: "api_disabled",
        message: text ?? "API access is not enabled for this account"
      };
    }
    if (err.status === 429) {
      return {
        ok: false,
        code: "rate_limited",
        message: "Tradovate rate limit reached"
      };
    }
    return {
      ok: false,
      code: "unexpected",
      message: text ?? `Tradovate returned HTTP ${err.status}`
    };
  }
  return {
    ok: false,
    code: "transport",
    message: "Could not reach Tradovate"
  };
}
function extractErrorText(body) {
  if (!body) return null;
  if (typeof body === "string") return redact(body.slice(0, 200));
  if (typeof body === "object") {
    const rec = body;
    for (const key of ["errorText", "error", "message", "detail"]) {
      const v = rec[key];
      if (typeof v === "string" && v) return redact(v.slice(0, 200));
    }
  }
  return null;
}
async function ensureToken(opts) {
  const now = opts.now ?? (() => Date.now());
  if (opts.stored?.accessToken && !needsRenewal(opts.stored.expirationTime, now(), opts.marginMs)) {
    return {
      ok: true,
      accessToken: opts.stored.accessToken,
      expirationTime: opts.stored.expirationTime,
      userId: 0,
      name: opts.credentials.name
    };
  }
  return authenticate(opts);
}

// supabase/functions/_shared/tradovate/pnl.ts
function rootFromSymbol(symbol) {
  const s = (symbol ?? "").toUpperCase();
  const m = s.match(/^([A-Z0-9]{1,4}?)([FGHJKMNQUVXZ])(\d{1,2})$/);
  return m ? m[1] : s;
}

// supabase/functions/_shared/tradovate/restService.ts
function authHeaders(accessToken) {
  return { Authorization: `Bearer ${accessToken}` };
}
function finiteOrNull(v) {
  const n = Number(v);
  return Number.isFinite(n) ? n : null;
}
async function contractItem(opts) {
  const limiter = opts.limiter ?? createDefaultLimiter();
  const data = await requestJson({
    url: `${hostFor(opts.environment)}/contract/item`,
    limiter,
    fetchImpl: opts.fetchImpl,
    headers: authHeaders(opts.accessToken),
    body: { id: opts.contractId }
  });
  if (!data || typeof data !== "object") return null;
  return {
    id: Number(data.id ?? opts.contractId),
    name: String(data.name ?? ""),
    symbol: data.symbol ? String(data.symbol) : void 0
  };
}
async function positionList(opts) {
  const limiter = opts.limiter ?? createDefaultLimiter();
  const data = await requestJson({
    url: `${hostFor(opts.environment)}/position/list`,
    limiter,
    fetchImpl: opts.fetchImpl,
    headers: authHeaders(opts.accessToken),
    body: {}
  });
  if (!Array.isArray(data)) return [];
  return data.map(normalizePosition).filter((p) => !!p);
}
function normalizePosition(raw) {
  if (!raw || typeof raw !== "object") return null;
  const rec = raw;
  const accountId = Number(rec.accountId);
  if (!Number.isFinite(accountId)) return null;
  return {
    id: finiteOrNull(rec.id),
    accountId,
    contractId: finiteOrNull(rec.contractId),
    timestamp: typeof rec.timestamp === "string" ? rec.timestamp : null,
    netPos: Number(rec.netPos ?? 0) || 0,
    netPrice: finiteOrNull(rec.netPrice),
    bought: Number(rec.bought ?? 0) || 0,
    boughtValue: Number(rec.boughtValue ?? 0) || 0,
    sold: Number(rec.sold ?? 0) || 0,
    soldValue: Number(rec.soldValue ?? 0) || 0,
    prevPos: Number(rec.prevPos ?? 0) || 0,
    prevPrice: finiteOrNull(rec.prevPrice),
    raw: rec
  };
}
async function orderList(opts) {
  const limiter = opts.limiter ?? createDefaultLimiter();
  const data = await requestJson({
    url: `${hostFor(opts.environment)}/order/list`,
    limiter,
    fetchImpl: opts.fetchImpl,
    headers: authHeaders(opts.accessToken),
    body: {}
  });
  if (!Array.isArray(data)) return [];
  return data.map(normalizeOrder).filter((o) => !!o);
}
function normalizeOrder(raw) {
  if (!raw || typeof raw !== "object") return null;
  const rec = raw;
  const id = Number(rec.id);
  const accountId = Number(rec.accountId);
  if (!Number.isFinite(id) || !Number.isFinite(accountId)) return null;
  const actionRaw = String(rec.action ?? "");
  return {
    id,
    accountId,
    contractId: finiteOrNull(rec.contractId),
    timestamp: typeof rec.timestamp === "string" ? rec.timestamp : null,
    action: actionRaw === "Buy" || actionRaw === "Sell" ? actionRaw : null,
    ordStatus: String(rec.ordStatus ?? "Unknown"),
    raw: rec
  };
}
async function orderVersionList(opts) {
  const limiter = opts.limiter ?? createDefaultLimiter();
  const data = await requestJson({
    url: `${hostFor(opts.environment)}/orderVersion/list`,
    limiter,
    fetchImpl: opts.fetchImpl,
    headers: authHeaders(opts.accessToken),
    body: {}
  });
  if (!Array.isArray(data)) return [];
  return data.map(normalizeOrderVersion).filter((o) => !!o);
}
function normalizeOrderVersion(raw) {
  if (!raw || typeof raw !== "object") return null;
  const rec = raw;
  const orderId = Number(rec.orderId);
  if (!Number.isFinite(orderId)) return null;
  return {
    id: finiteOrNull(rec.id),
    orderId,
    orderQty: finiteOrNull(rec.orderQty),
    orderType: rec.orderType ? String(rec.orderType) : null,
    price: finiteOrNull(rec.price),
    stopPrice: finiteOrNull(rec.stopPrice),
    limitIfTouchedPrice: finiteOrNull(rec.limitIfTouchedPrice),
    timeInForce: rec.timeInForce ? String(rec.timeInForce) : null,
    text: typeof rec.text === "string" ? rec.text : null,
    raw: rec
  };
}
async function cashBalanceSnapshot(opts) {
  const limiter = opts.limiter ?? createDefaultLimiter();
  const data = await requestJson({
    url: `${hostFor(opts.environment)}/cashBalance/getCashBalanceSnapshot`,
    limiter,
    fetchImpl: opts.fetchImpl,
    headers: authHeaders(opts.accessToken),
    body: { accountId: opts.accountId }
  });
  if (!data || typeof data !== "object") return null;
  const errorText = typeof data.errorText === "string" ? data.errorText : "";
  if (errorText) return null;
  return {
    accountId: opts.accountId,
    totalCashValue: finiteOrNull(data.totalCashValue),
    totalPnL: finiteOrNull(data.totalPnL),
    netLiq: finiteOrNull(data.netLiq),
    openPnL: finiteOrNull(data.openPnL),
    realizedPnL: finiteOrNull(data.realizedPnL),
    weekRealizedPnL: finiteOrNull(data.weekRealizedPnL),
    initialMargin: finiteOrNull(data.initialMargin),
    maintenanceMargin: finiteOrNull(data.maintenanceMargin),
    fullInitialMargin: finiteOrNull(data.fullInitialMargin),
    autoLiqLevel: finiteOrNull(data.autoLiqLevel),
    cashUSD: finiteOrNull(data.cashUSD),
    currencyCashAvailWithdrawalUSD: finiteOrNull(data.currencyCashAvailWithdrawalUSD),
    raw: data
  };
}
function makeCachedContractResolver(opts) {
  const cache = /* @__PURE__ */ new Map();
  return {
    resolve(contractId) {
      if (contractId === null) return null;
      return cache.get(contractId) ?? null;
    },
    async ensure(contractIds) {
      for (const id of contractIds) {
        if (cache.has(id)) continue;
        try {
          const item = await contractItem({ ...opts, contractId: id });
          if (item) {
            const name = item.symbol || item.name || "";
            cache.set(id, { root: rootFromSymbol(name), symbol: name });
          }
        } catch {
        }
      }
    }
  };
}

// supabase/functions/_shared/tradovate/snapshot.ts
var WORKING_STATUSES = /* @__PURE__ */ new Set([
  "Working",
  "PendingNew",
  "PendingCancel",
  "PendingReplace",
  "Suspended"
]);
async function fetchAccountSnapshot(opts) {
  const limiter = opts.limiter ?? createDefaultLimiter();
  const now = opts.now ?? (() => Date.now());
  const env = opts.integration.environment;
  const accountId = Number(opts.integration.tradovate_account_id);
  const base = {
    integrationId: opts.integrationId,
    accountId,
    accountSpec: opts.integration.account_spec,
    environment: env,
    balance: null,
    positions: [],
    orders: [],
    fetchedAt: new Date(now()).toISOString(),
    warnings: []
  };
  const auth = await ensureToken({
    credentials: opts.credentials,
    environment: env,
    limiter,
    fetchImpl: opts.fetchImpl,
    now,
    stored: opts.credentials.accessToken ? {
      accessToken: opts.credentials.accessToken,
      expirationTime: opts.credentials.accessTokenExpiresAt ?? ""
    } : null
  });
  if (!auth.ok) {
    return { ...base, warnings: ["auth"] };
  }
  const accessToken = auth.accessToken;
  if (!opts.credentials.accessToken || opts.credentials.accessToken !== accessToken) {
    await storeSessionToken(opts.admin, opts.userId, opts.integrationId, {
      accessToken,
      expirationTime: auth.expirationTime
    });
  }
  const rest = { environment: env, accessToken, limiter, fetchImpl: opts.fetchImpl };
  const resolver = makeCachedContractResolver(rest);
  let balance = null;
  try {
    const snap = await cashBalanceSnapshot({ ...rest, accountId });
    if (snap) {
      balance = {
        totalCashValue: snap.totalCashValue,
        totalPnL: snap.totalPnL,
        netLiq: snap.netLiq,
        openPnL: snap.openPnL,
        realizedPnL: snap.realizedPnL,
        weekRealizedPnL: snap.weekRealizedPnL,
        initialMargin: snap.initialMargin,
        maintenanceMargin: snap.maintenanceMargin,
        fullInitialMargin: snap.fullInitialMargin,
        autoLiqLevel: snap.autoLiqLevel,
        cashUSD: snap.cashUSD,
        currencyCashAvailWithdrawalUSD: snap.currencyCashAvailWithdrawalUSD
      };
    } else {
      base.warnings.push("balance");
    }
  } catch {
    base.warnings.push("balance");
  }
  const positions = [];
  try {
    const rows = (await positionList(rest)).filter(
      (p) => p.accountId === accountId && p.netPos !== 0
    );
    await resolver.ensure(
      rows.map((p) => p.contractId).filter((id) => id !== null)
    );
    for (const p of rows) {
      const info = resolver.resolve(p.contractId);
      positions.push({
        contractId: p.contractId,
        symbol: info?.symbol ?? null,
        root: info?.root ?? null,
        side: p.netPos > 0 ? "long" : "short",
        quantity: Math.abs(p.netPos),
        avgPrice: p.netPrice
      });
    }
  } catch {
    base.warnings.push("positions");
  }
  const orders = [];
  try {
    const [orderRows, versionRows] = await Promise.all([
      orderList(rest),
      orderVersionList(rest).catch(() => [])
    ]);
    const versionByOrder = /* @__PURE__ */ new Map();
    for (const v of versionRows) versionByOrder.set(v.orderId, v);
    const scoped = orderRows.filter((o) => o.accountId === accountId);
    await resolver.ensure(
      scoped.map((o) => o.contractId).filter((id) => id !== null)
    );
    for (const o of scoped) {
      const info = resolver.resolve(o.contractId);
      const v = versionByOrder.get(o.id);
      orders.push({
        orderId: o.id,
        contractId: o.contractId,
        symbol: info?.symbol ?? null,
        root: info?.root ?? null,
        action: o.action,
        orderType: v?.orderType ?? null,
        quantity: v?.orderQty ?? null,
        price: v?.price ?? null,
        stopPrice: v?.stopPrice ?? null,
        timeInForce: v?.timeInForce ?? null,
        ordStatus: o.ordStatus,
        isWorking: WORKING_STATUSES.has(o.ordStatus),
        timestamp: o.timestamp
      });
    }
  } catch {
    base.warnings.push("orders");
  }
  return { ...base, balance, positions, orders };
}
async function loadSnapshotInputs(admin, userId, integrationId) {
  return loadCredentials(admin, userId, integrationId);
}

// supabase/functions/_shared/features.ts
function flagEnabled(value) {
  return value !== "false";
}
function isTradovateEnabled(env = defaultEnv()) {
  return flagEnabled(env.TRADOVATE_ENABLED);
}
function featureDisabledBody(feature) {
  return {
    ok: false,
    error: "feature_disabled",
    feature,
    message: `${feature} is disabled by its runtime switch.`
  };
}
function defaultEnv() {
  return {
    TRADOVATE_ENABLED: Deno.env.get("TRADOVATE_ENABLED") ?? void 0,
    AI_KYC_ENABLED: Deno.env.get("AI_KYC_ENABLED") ?? void 0,
    WITHDRAWAL_KYC_GATE_ENABLED: Deno.env.get("WITHDRAWAL_KYC_GATE_ENABLED") ?? void 0
  };
}

// supabase/functions/tradovate-dashboard/index.ts
var DEFAULT_TTL_SECONDS = 20;
function ttlMs() {
  const raw = Number(Deno.env.get("TRADOVATE_SNAPSHOT_TTL_SECONDS") ?? DEFAULT_TTL_SECONDS);
  const seconds = Number.isFinite(raw) && raw >= 0 ? raw : DEFAULT_TTL_SECONDS;
  return seconds * 1e3;
}
serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  if (req.method !== "GET") return json({ error: "method_not_allowed" }, 405);
  if (!isTradovateEnabled()) {
    return json(featureDisabledBody("tradovate"), 503);
  }
  let ctx;
  try {
    ctx = await requireUser(req);
  } catch (e) {
    if (e instanceof UnauthorizedError) return json({ error: "unauthorized" }, 401);
    return json({ error: "unauthorized" }, 401);
  }
  const integrations = await listIntegrations(ctx.admin, ctx.user.id);
  if (integrations.length === 0) {
    return json({
      ok: true,
      connected: false,
      accounts: [],
      account: null,
      snapshot: null,
      cached: false,
      warnings: [],
      lastSyncedAt: null,
      integrations: []
    });
  }
  const url = new URL(req.url);
  const requestedIntegration = url.searchParams.get("integrationId");
  const fresh = url.searchParams.get("fresh") === "1";
  const selected = requestedIntegration ? integrations.find((i) => i.id === requestedIntegration) ?? null : integrations[0];
  if (!selected) return json({ error: "integration_not_found" }, 404);
  const accounts = integrations.map((i) => ({
    integrationId: i.id,
    accountId: i.tradovate_account_id,
    accountSpec: i.account_spec,
    label: i.label,
    environment: i.environment,
    status: i.status
  }));
  const base = {
    ok: true,
    connected: true,
    accounts,
    account: accounts.find((a) => a.integrationId === selected.id) ?? accounts[0],
    lastSyncedAt: null,
    integrations: accounts
  };
  try {
    const cached = await readSnapshot(ctx.admin, selected.id);
    if (cached && !fresh) {
      const age = Date.now() - Date.parse(cached.fetched_at);
      if (Number.isFinite(age) && age >= 0 && age < ttlMs()) {
        return json({
          ...base,
          snapshot: cached.payload,
          cached: true,
          warnings: cached.warnings,
          lastSyncedAt: cached.fetched_at
        });
      }
    }
  } catch {
  }
  try {
    const { integration, credentials } = await loadSnapshotInputs(
      ctx.admin,
      ctx.user.id,
      selected.id
    );
    const snapshot = await fetchAccountSnapshot({
      admin: ctx.admin,
      userId: ctx.user.id,
      integrationId: selected.id,
      integration,
      credentials,
      limiter: createDefaultLimiter()
    });
    try {
      await writeSnapshot(ctx.admin, selected.id, snapshot, snapshot.warnings);
    } catch {
    }
    return json({
      ...base,
      snapshot,
      cached: false,
      warnings: snapshot.warnings,
      lastSyncedAt: snapshot.fetchedAt
    });
  } catch {
    return json({
      ...base,
      snapshot: null,
      cached: false,
      warnings: ["unavailable"]
    });
  }
});
