// AUTO-GENERATED by scripts/bundle-edge-functions.mjs — do not edit by hand.
// Paste this whole file as the Edge Function body in the Supabase dashboard.


// supabase/functions/tradovate-sync/index.ts
import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient as createClient2 } from "https://esm.sh/@supabase/supabase-js@2.45.0";

// supabase/functions/_shared/tradovate/auth.ts
import {
  createClient
} from "https://esm.sh/@supabase/supabase-js@2.45.0";
var UnauthorizedError = class extends Error {
  constructor() {
    super("unauthorized");
    this.name = "UnauthorizedError";
  }
};
async function requireUser(req) {
  const auth = req.headers.get("Authorization") ?? "";
  if (!auth.startsWith("Bearer ")) throw new UnauthorizedError();
  const token = auth.slice("Bearer ".length);
  const userClient = createClient(
    Deno.env.get("SUPABASE_URL") ?? "",
    Deno.env.get("SUPABASE_ANON_KEY") ?? "",
    { global: { headers: { Authorization: auth } } }
  );
  const { data, error } = await userClient.auth.getUser(token);
  if (error || !data?.user) throw new UnauthorizedError();
  const admin = createClient(
    Deno.env.get("SUPABASE_URL") ?? "",
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
    { auth: { autoRefreshToken: false, persistSession: false } }
  );
  return { user: { id: data.user.id, email: data.user.email }, admin };
}
var corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS"
};
function json(body, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" }
  });
}

// supabase/functions/_shared/tradovate/rateLimiter.ts
var CircuitOpenError = class extends Error {
  constructor(retryAfterMs) {
    super(`rate-limit circuit open for another ${retryAfterMs}ms`);
    this.retryAfterMs = retryAfterMs;
    this.name = "CircuitOpenError";
  }
};
var SECOND = 1e3;
var MINUTE = 60 * SECOND;
var HOUR = 60 * MINUTE;
var defaultSleep = (ms) => new Promise((resolve) => setTimeout(resolve, Math.max(0, ms)));
function parseTimePenalty(body) {
  if (!body || typeof body !== "object") return null;
  const rec = body;
  const hasTicket = "p-ticket" in rec;
  const hasTime = "p-time" in rec;
  const hasCaptcha = "p-captcha" in rec;
  if (!hasTicket && !hasTime && !hasCaptcha) return null;
  const rawTime = rec["p-time"];
  const waitSeconds = typeof rawTime === "number" && Number.isFinite(rawTime) ? Math.max(0, rawTime) : 0;
  const ticket = typeof rec["p-ticket"] === "string" ? rec["p-ticket"] : null;
  const captcha = rec["p-captcha"] === true;
  return { ticket, waitSeconds, captcha };
}
var TradovateRateLimiter = class {
  perSecond;
  perMinute;
  perHour;
  baseBackoffMs;
  maxBackoffMs;
  captchaCircuitMs;
  rateLimitCircuitMs;
  sleep;
  now;
  random;
  /** Timestamps (ms) of accepted requests within the last hour. */
  history = [];
  circuitOpenUntil = 0;
  /** Consecutive plain-429 counter, reset on success. */
  consecutive429 = 0;
  constructor(opts = {}) {
    this.perSecond = opts.requestsPerSecond ?? 4;
    this.perMinute = opts.requestsPerMinute ?? 60;
    this.perHour = opts.requestsPerHour ?? 4500;
    this.baseBackoffMs = opts.baseBackoffMs ?? 500;
    this.maxBackoffMs = opts.maxBackoffMs ?? 3e4;
    this.captchaCircuitMs = opts.captchaCircuitMs ?? HOUR;
    this.rateLimitCircuitMs = opts.rateLimitCircuitMs ?? MINUTE;
    this.sleep = opts.sleep ?? defaultSleep;
    this.now = opts.now ?? (() => Date.now());
    this.random = opts.random ?? Math.random;
  }
  /** Throw CircuitOpenError while a p-captcha / repeated-429 circuit is open. */
  assertCircuitClosed() {
    const remaining = this.circuitOpenUntil - this.now();
    if (remaining > 0) throw new CircuitOpenError(remaining);
  }
  isCircuitOpen() {
    return this.circuitOpenUntil > this.now();
  }
  /** Wait until all three rolling windows allow one more request. */
  async waitForSlot() {
    this.assertCircuitClosed();
    for (; ; ) {
      const now = this.now();
      this.history = this.history.filter((t) => now - t < HOUR);
      const waits = [
        this.windowWait(now, SECOND, this.perSecond),
        this.windowWait(now, MINUTE, this.perMinute),
        this.windowWait(now, HOUR, this.perHour)
      ];
      const wait = Math.max(0, ...waits);
      if (wait <= 0) break;
      await this.sleep(wait);
      this.assertCircuitClosed();
    }
    this.history.push(this.now());
  }
  windowWait(now, windowMs, limit) {
    const inWindow = this.history.filter((t) => now - t < windowMs);
    if (inWindow.length < limit) return 0;
    const oldest = Math.min(...inWindow);
    return oldest + windowMs - now;
  }
  /** Exponential backoff with jitter for a plain 429. */
  async backoffFor429() {
    this.consecutive429 += 1;
    if (this.consecutive429 >= 5) {
      this.circuitOpenUntil = this.now() + this.rateLimitCircuitMs;
    }
    const exp = Math.min(
      this.maxBackoffMs,
      this.baseBackoffMs * 2 ** (this.consecutive429 - 1)
    );
    const jitter = Math.floor(this.random() * (exp / 2));
    const wait = exp + jitter;
    await this.sleep(wait);
    return wait;
  }
  /**
   * Handle a p-time / p-ticket penalty. Returns the ticket the caller must
   * echo back in the request body. Opens the circuit (and throws) on captcha.
   */
  async handlePenalty(penalty) {
    if (penalty.captcha) {
      this.circuitOpenUntil = this.now() + this.captchaCircuitMs;
      throw new CircuitOpenError(this.captchaCircuitMs);
    }
    if (penalty.waitSeconds > 0) {
      await this.sleep(penalty.waitSeconds * SECOND);
    }
    return penalty.ticket;
  }
  /** Reset the consecutive-429 counter after any successful call. */
  onSuccess() {
    this.consecutive429 = 0;
  }
  /** Test/diagnostic snapshot; contains no credentials. */
  snapshot() {
    return {
      historyLength: this.history.length,
      consecutive429: this.consecutive429,
      circuitOpenUntil: this.circuitOpenUntil,
      circuitOpen: this.isCircuitOpen()
    };
  }
};
function createDefaultLimiter(opts = {}) {
  return new TradovateRateLimiter({
    requestsPerSecond: 4,
    requestsPerMinute: 60,
    requestsPerHour: 4500,
    ...opts
  });
}

// supabase/functions/_shared/tradovate/http.ts
var TradovateHttpError = class extends Error {
  constructor(status, body, message) {
    super(message);
    this.status = status;
    this.body = body;
    this.name = "TradovateHttpError";
  }
};
async function requestJson(opts) {
  const fetchImpl = opts.fetchImpl ?? fetch;
  const maxAttempts = opts.maxAttempts ?? 6;
  const method = opts.method ?? "POST";
  let body = opts.body ?? null;
  let attempts = 0;
  for (; ; ) {
    attempts += 1;
    opts.limiter.assertCircuitClosed();
    await opts.limiter.waitForSlot();
    const res = await fetchImpl(opts.url, {
      method,
      headers: {
        "Content-Type": "application/json",
        ...opts.headers ?? {}
      },
      body: body === null ? void 0 : JSON.stringify(body),
      signal: opts.signal
    });
    if (res.status === 429) {
      const parsed = await safeJson(res);
      const penalty = parseTimePenalty(parsed);
      if (penalty && !penalty.captcha && attempts < maxAttempts) {
        const ticket = await opts.limiter.handlePenalty(penalty);
        if (ticket) {
          body = { ...body ?? {}, "p-ticket": ticket };
        }
        continue;
      }
      if (penalty && penalty.captcha) {
        await opts.limiter.handlePenalty(penalty);
      }
      if (attempts < maxAttempts) {
        await opts.limiter.backoffFor429();
        continue;
      }
      throw new TradovateHttpError(
        429,
        parsed,
        "Tradovate rate limit persisted beyond retry budget"
      );
    }
    if (!res.ok) {
      throw new TradovateHttpError(
        res.status,
        await safeJson(res),
        `Tradovate HTTP ${res.status}`
      );
    }
    opts.limiter.onSuccess();
    return await safeJson(res);
  }
}
async function safeJson(res) {
  const text = await res.text();
  if (!text) return null;
  try {
    return JSON.parse(text);
  } catch {
    return text;
  }
}

// supabase/functions/_shared/tradovate/appCredentials.ts
function resolveAppCredentials(clientCid, clientSec, env = (k) => Deno.env.get(k)) {
  const cid = clientCid?.trim() || env("TRADOVATE_APP_CID")?.trim() || void 0;
  const sec = clientSec?.trim() || env("TRADOVATE_APP_SECRET")?.trim() || void 0;
  const source = clientCid || clientSec ? "client" : cid || sec ? "server" : "none";
  return {
    cid,
    sec,
    appId: env("TRADOVATE_APP_ID")?.trim() || "Braxel",
    appVersion: env("TRADOVATE_APP_VERSION")?.trim() || "1.3.0",
    source
  };
}

// supabase/functions/_shared/tradovate/crypto.ts
var KEY_VERSION = 1;
var IV_BYTES = 12;
var TAG_BYTES = 16;
var KEY_BYTES = 32;
var EncryptionConfigError = class extends Error {
  constructor(message) {
    super(message);
    this.name = "EncryptionConfigError";
  }
};
var DecryptionError = class extends Error {
  constructor(message) {
    super(message);
    this.name = "DecryptionError";
  }
};
function isEncryptionConfigured() {
  return (Deno.env.get("TRADOVATE_ENCRYPTION_KEY") ?? "").length > 0;
}
function base64ToBytes(b64) {
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}
function bytesToBase64(bytes) {
  let bin = "";
  for (const b of bytes) bin += String.fromCharCode(b);
  return btoa(bin);
}
function hexToBytes(hex) {
  const clean = hex.trim().toLowerCase();
  if (!/^[0-9a-f]+$/.test(clean) || clean.length % 2 !== 0) return null;
  const out = new Uint8Array(clean.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(clean.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}
function tryRawKey(secret) {
  const hex = hexToBytes(secret);
  if (hex && hex.length === KEY_BYTES) return hex;
  try {
    const b64 = base64ToBytes(secret);
    if (b64.length === KEY_BYTES) return b64;
  } catch {
  }
  return null;
}
async function importAesKey(secret) {
  if (!secret) {
    throw new EncryptionConfigError(
      "TRADOVATE_ENCRYPTION_KEY is not set"
    );
  }
  let raw = tryRawKey(secret);
  if (!raw) {
    const digest = await crypto.subtle.digest(
      "SHA-256",
      new TextEncoder().encode(secret)
    );
    raw = new Uint8Array(digest);
  }
  return await crypto.subtle.importKey(
    "raw",
    raw,
    { name: "AES-GCM" },
    false,
    ["encrypt", "decrypt"]
  );
}
async function encryptCredentials(creds, secret) {
  const key = await importAesKey(secret);
  const iv = crypto.getRandomValues(new Uint8Array(IV_BYTES));
  const plaintext = new TextEncoder().encode(JSON.stringify(creds));
  const sealed = new Uint8Array(
    await crypto.subtle.encrypt(
      { name: "AES-GCM", iv, tagLength: 128 },
      key,
      plaintext
    )
  );
  const tag = sealed.slice(sealed.length - TAG_BYTES);
  const body = sealed.slice(0, sealed.length - TAG_BYTES);
  return {
    ciphertext: bytesToBase64(body),
    iv: bytesToBase64(iv),
    authTag: bytesToBase64(tag),
    keyVersion: KEY_VERSION
  };
}
async function decryptCredentials(parts, secret) {
  const key = await importAesKey(secret);
  const iv = base64ToBytes(parts.iv);
  const tag = base64ToBytes(parts.authTag);
  const body = base64ToBytes(parts.ciphertext);
  if (iv.length !== IV_BYTES || tag.length !== TAG_BYTES) {
    throw new DecryptionError("malformed credential envelope");
  }
  const sealed = new Uint8Array(body.length + tag.length);
  sealed.set(body, 0);
  sealed.set(tag, body.length);
  let plaintext;
  try {
    plaintext = await crypto.subtle.decrypt(
      { name: "AES-GCM", iv, tagLength: 128 },
      key,
      sealed
    );
  } catch {
    throw new DecryptionError(
      "could not decrypt credentials (wrong key or tampered ciphertext)"
    );
  }
  return JSON.parse(new TextDecoder().decode(plaintext));
}
function redact(value) {
  const s = typeof value === "string" ? value : JSON.stringify(value ?? "");
  return s.replace(/Bearer\s+[A-Za-z0-9._~+/-]+=*/gi, "Bearer [REDACTED]").replace(/(password|passwd|pwd)"?\s*[:=]\s*"?[^",}\s]+/gi, "$1=[REDACTED]").replace(/(accessToken|access_token|token|sec|cid|authorization)"?\s*[:=]\s*"?[^",}\s]+/gi, "$1=[REDACTED]");
}

// supabase/functions/_shared/tradovate/authService.ts
var TRADOVATE_HOSTS = {
  demo: "https://demo.tradovateapi.com/v1",
  live: "https://live.tradovateapi.com/v1"
};
var TOKEN_RENEW_MARGIN_MS = 5 * 60 * 1e3;
function hostFor(env) {
  return TRADOVATE_HOSTS[env];
}
function needsRenewal(expirationTime, nowMs = Date.now(), marginMs = TOKEN_RENEW_MARGIN_MS) {
  if (!expirationTime) return true;
  const expiry = Date.parse(expirationTime);
  if (!Number.isFinite(expiry)) return true;
  return expiry - nowMs <= marginMs;
}
async function authenticate(opts) {
  const limiter = opts.limiter ?? createDefaultLimiter();
  const { credentials, environment } = opts;
  const url = `${hostFor(environment)}/auth/accesstokenrequest`;
  const app = resolveAppCredentials(credentials.cid, credentials.sec);
  const body = {
    name: credentials.name,
    password: credentials.password,
    appId: credentials.appId ?? app.appId,
    appVersion: credentials.appVersion ?? app.appVersion,
    deviceId: credentials.deviceId ?? "braxel-terminal"
  };
  if (app.cid) body.cid = app.cid;
  if (app.sec) body.sec = app.sec;
  try {
    const data = await requestJson({
      url,
      limiter,
      fetchImpl: opts.fetchImpl,
      body
    });
    const accessToken = typeof data?.accessToken === "string" ? data.accessToken : null;
    if (!accessToken) {
      const text = extractErrorText(data);
      if (text && /incorrect username or password|invalid (username|password|credentials)|bad credentials/i.test(text)) {
        return { ok: false, code: "invalid_credentials", message: text };
      }
      if (text && /api access|not enabled|entitlement|subscription|not entitled/i.test(text)) {
        return { ok: false, code: "api_disabled", message: text };
      }
      return {
        ok: false,
        code: "unexpected",
        message: text ?? "Tradovate returned no access token"
      };
    }
    return {
      ok: true,
      accessToken,
      expirationTime: String(data.expirationTime ?? ""),
      userId: Number(data.userId ?? 0),
      name: String(data.name ?? credentials.name)
    };
  } catch (err) {
    return classifyAuthError(err);
  }
}
function classifyAuthError(err) {
  if (err instanceof CircuitOpenError) {
    return {
      ok: false,
      code: "circuit_open",
      message: "Tradovate asked for a captcha; retry in about an hour",
      retryAfterMs: err.retryAfterMs
    };
  }
  if (err instanceof TradovateHttpError) {
    const text = extractErrorText(err.body);
    if (err.status === 401) {
      return {
        ok: false,
        code: "invalid_credentials",
        message: text ?? "Tradovate rejected the username or password"
      };
    }
    if (err.status === 403 || /api access|not enabled|entitlement/i.test(text ?? "")) {
      return {
        ok: false,
        code: "api_disabled",
        message: text ?? "API access is not enabled for this account"
      };
    }
    if (err.status === 429) {
      return {
        ok: false,
        code: "rate_limited",
        message: "Tradovate rate limit reached"
      };
    }
    return {
      ok: false,
      code: "unexpected",
      message: text ?? `Tradovate returned HTTP ${err.status}`
    };
  }
  return {
    ok: false,
    code: "transport",
    message: "Could not reach Tradovate"
  };
}
function extractErrorText(body) {
  if (!body) return null;
  if (typeof body === "string") return redact(body.slice(0, 200));
  if (typeof body === "object") {
    const rec = body;
    for (const key of ["errorText", "error", "message", "detail"]) {
      const v = rec[key];
      if (typeof v === "string" && v) return redact(v.slice(0, 200));
    }
  }
  return null;
}
async function ensureToken(opts) {
  const now = opts.now ?? (() => Date.now());
  if (opts.stored?.accessToken && !needsRenewal(opts.stored.expirationTime, now(), opts.marginMs)) {
    return {
      ok: true,
      accessToken: opts.stored.accessToken,
      expirationTime: opts.stored.expirationTime,
      userId: 0,
      name: opts.credentials.name
    };
  }
  return authenticate(opts);
}

// supabase/functions/_shared/tradovate/credentialStore.ts
var CredentialStoreError = class extends Error {
  constructor(code, message) {
    super(message ?? code);
    this.code = code;
    this.name = "CredentialStoreError";
  }
};
async function loadCredentials(admin, userId, integrationId) {
  if (!isEncryptionConfigured()) {
    throw new CredentialStoreError("encryption_not_configured");
  }
  const { data: integ, error: integErr } = await admin.from("integrations").select(
    "id, user_id, environment, tradovate_account_id, tradovate_user_id, account_spec, label, status, last_fill_id, token_expires_at"
  ).eq("id", integrationId).eq("user_id", userId).maybeSingle();
  if (integErr) throw new CredentialStoreError("integration_read_failed", integErr.message);
  if (!integ) throw new CredentialStoreError("integration_not_found");
  const { data: cred, error: credErr } = await admin.from("integration_credentials").select("ciphertext, iv, auth_tag, key_version").eq("integration_id", integrationId).maybeSingle();
  if (credErr) throw new CredentialStoreError("credential_read_failed", credErr.message);
  if (!cred) throw new CredentialStoreError("credentials_missing");
  const credentials = await decryptCredentials({
    ciphertext: cred.ciphertext,
    iv: cred.iv,
    authTag: cred.auth_tag,
    keyVersion: cred.key_version
  }, Deno.env.get("TRADOVATE_ENCRYPTION_KEY") ?? "");
  return { integration: integ, credentials };
}
async function storeSessionToken(admin, userId, integrationId, token) {
  try {
    const { integration, credentials } = await loadCredentials(admin, userId, integrationId);
    const merged = {
      ...credentials,
      accessToken: token.accessToken,
      accessTokenExpiresAt: token.expirationTime
    };
    const parts = await encryptCredentials(merged, Deno.env.get("TRADOVATE_ENCRYPTION_KEY") ?? "");
    await admin.from("integration_credentials").update({
      ciphertext: parts.ciphertext,
      iv: parts.iv,
      auth_tag: parts.authTag,
      key_version: parts.keyVersion
    }).eq("integration_id", integration.id);
    await admin.from("integrations").update({ token_expires_at: token.expirationTime }).eq("id", integrationId).eq("user_id", userId);
  } catch {
  }
}

// supabase/functions/_shared/tradovate/pnl.ts
var POINT_VALUES = {
  ES: 50,
  MES: 5,
  NQ: 20,
  MNQ: 2,
  YM: 5,
  MYM: 0.5,
  RTY: 50,
  M2K: 5,
  GC: 100,
  MGC: 10,
  SI: 5e3,
  SIL: 1e3,
  HG: 25e3,
  CL: 1e3,
  MCL: 100,
  NG: 1e4,
  MNG: 1e3,
  ZB: 1e3,
  ZN: 1e3,
  ZF: 1e3,
  ZT: 1e3,
  "6E": 125e3,
  "6B": 62500,
  "6J": 125e5,
  ZC: 50,
  ZS: 50,
  ZW: 50
};
function pointValueFor(root, fallback = 1) {
  const key = (root ?? "").toUpperCase();
  return POINT_VALUES[key] ?? fallback;
}
function rootFromSymbol(symbol) {
  const s = (symbol ?? "").toUpperCase();
  const m = s.match(/^([A-Z0-9]{1,4}?)([FGHJKMNQUVXZ])(\d{1,2})$/);
  return m ? m[1] : s;
}
function commissionFor(fill, opts) {
  if (fill.commission && fill.commission > 0) return fill.commission;
  const cpc = opts.commissionPerContract;
  if (typeof cpc === "function") return cpc(fill.accountId) * fill.quantity;
  if (typeof cpc === "number") return cpc * fill.quantity;
  return 0;
}
function reconstructTrades(fills, opts) {
  const method = opts.method ?? "fifo";
  const defaultPv = opts.defaultPointValue ?? 1;
  const byId = /* @__PURE__ */ new Map();
  for (const f of fills) {
    if (!f || !Number.isFinite(f.id)) continue;
    if (f.active === false) continue;
    if (f.action !== "Buy" && f.action !== "Sell") continue;
    if (!(f.quantity > 0)) continue;
    byId.set(f.id, f);
  }
  const ordered = [...byId.values()].sort((a, b) => {
    const ta = Date.parse(a.timestamp);
    const tb = Date.parse(b.timestamp);
    const na = Number.isFinite(ta) ? ta : 0;
    const nb = Number.isFinite(tb) ? tb : 0;
    return na - nb || a.id - b.id;
  });
  const positions = /* @__PURE__ */ new Map();
  const working = /* @__PURE__ */ new Map();
  const out = [];
  for (const fill of ordered) {
    const contract = opts.resolveContract(fill.contractId);
    const root = contract?.root ?? "UNKNOWN";
    const symbol = contract?.symbol;
    const pv = contract?.pointValue ?? pointValueFor(root, defaultPv);
    const key = `${fill.accountId ?? "na"}:${fill.contractId ?? root}`;
    const dir = fill.action === "Buy" ? "long" : "short";
    const fillCommPerUnit = commissionFor(fill, opts) / fill.quantity;
    let pos = positions.get(key);
    if (!pos || pos.side === dir) {
      if (!pos) {
        pos = { side: dir, lots: [], avgEntry: 0, avgCommissionPerUnit: 0 };
        positions.set(key, pos);
      }
      pos.lots.push({
        qty: fill.quantity,
        price: fill.price,
        commissionPerUnit: fillCommPerUnit
      });
      updateWeighted(pos);
      let trade2 = working.get(key);
      if (!trade2) {
        trade2 = newWorkingTrade(fill, root, symbol, dir);
        working.set(key, trade2);
      }
      trade2.fillIds.push(fill.id);
      trade2.quantity += fill.quantity;
      trade2.entryPrice = pos.avgEntry;
      continue;
    }
    let remaining = fill.quantity;
    let realized = 0;
    let commission = 0;
    const sign = pos.side === "long" ? 1 : -1;
    if (method === "weighted_average") {
      const openQty = pos.lots.reduce((s, l) => s + l.qty, 0);
      const qty = Math.min(remaining, openQty);
      realized += sign * (fill.price - pos.avgEntry) * qty * pv;
      commission += (pos.avgCommissionPerUnit + fillCommPerUnit) * qty;
      remaining -= qty;
      scaleLots(pos, qty);
    } else {
      for (const lot of pos.lots) {
        if (remaining <= 0) break;
        const qty = Math.min(remaining, lot.qty);
        if (qty <= 0) continue;
        realized += sign * (fill.price - lot.price) * qty * pv;
        commission += (lot.commissionPerUnit + fillCommPerUnit) * qty;
        lot.qty -= qty;
        remaining -= qty;
      }
      pos.lots = pos.lots.filter((l) => l.qty > 0);
    }
    const closedQty = fill.quantity - remaining;
    const trade = working.get(key);
    if (trade && closedQty > 0) {
      trade.fillIds.push(fill.id);
      trade.closedQty += closedQty;
      trade.realizedPnl += realized;
      trade.commission += commission;
      trade.exitPrice = fill.price;
      trade.closedAt = fill.timestamp;
      if (trade.closedQty >= trade.quantity) {
        out.push(toReconstructedTrade(trade, true));
        working.delete(key);
      }
    }
    if (remaining > 0) {
      pos.side = dir;
      pos.lots = [{
        qty: remaining,
        price: fill.price,
        commissionPerUnit: fillCommPerUnit
      }];
      updateWeighted(pos);
      const flip = newWorkingTrade(fill, root, symbol, dir);
      flip.fillIds.push(fill.id);
      flip.quantity = remaining;
      working.set(key, flip);
    } else if (pos.lots.length === 0) {
      positions.delete(key);
    } else {
      updateWeighted(pos);
    }
  }
  for (const w of working.values()) {
    out.push(toReconstructedTrade(w, false));
  }
  return out.sort((a, b) => Date.parse(a.openedAt) - Date.parse(b.openedAt));
}
function newWorkingTrade(fill, root, symbol, side) {
  return {
    root,
    symbol,
    accountId: fill.accountId,
    side,
    quantity: 0,
    entryPrice: fill.price,
    exitPrice: null,
    openedAt: fill.timestamp,
    closedAt: null,
    realizedPnl: 0,
    commission: 0,
    fillIds: [],
    closedQty: 0
  };
}
function updateWeighted(pos) {
  const qty = pos.lots.reduce((s, l) => s + l.qty, 0);
  if (qty === 0) {
    pos.avgEntry = 0;
    pos.avgCommissionPerUnit = 0;
    return;
  }
  pos.avgEntry = pos.lots.reduce((s, l) => s + l.price * l.qty, 0) / qty;
  pos.avgCommissionPerUnit = pos.lots.reduce((s, l) => s + l.commissionPerUnit * l.qty, 0) / qty;
}
function scaleLots(pos, qty) {
  let remaining = qty;
  for (const lot of pos.lots) {
    if (remaining <= 0) break;
    const take = Math.min(remaining, lot.qty);
    lot.qty -= take;
    remaining -= take;
  }
  pos.lots = pos.lots.filter((l) => l.qty > 0);
  updateWeighted(pos);
}
function toReconstructedTrade(w, closed) {
  const fillIds = [...w.fillIds].sort((a, b) => a - b);
  const dedupeKey = [
    w.accountId ?? "na",
    w.root,
    w.side,
    fillIds.join(".")
  ].join(":");
  const realizedPnl = round2(w.realizedPnl);
  const commission = round2(w.commission);
  return {
    dedupeKey,
    root: w.root,
    symbol: w.symbol,
    accountId: w.accountId,
    side: w.side,
    quantity: w.quantity,
    entryPrice: round8(w.entryPrice),
    exitPrice: closed && w.exitPrice !== null ? round8(w.exitPrice) : null,
    openedAt: w.openedAt,
    closedAt: closed ? w.closedAt : null,
    realizedPnl,
    commission,
    netPnl: round2(realizedPnl - commission),
    status: closed ? "closed" : "open",
    fillIds
  };
}
function round2(n) {
  return Math.round((n + Number.EPSILON) * 100) / 100;
}
function round8(n) {
  return Math.round((n + Number.EPSILON) * 1e8) / 1e8;
}

// supabase/functions/_shared/tradovate/restService.ts
var DEFAULT_FILL_PAGE_LIMIT = 500;
var MAX_FILL_PAGES = 40;
function authHeaders(accessToken) {
  return { Authorization: `Bearer ${accessToken}` };
}
function normalizeFill(raw) {
  if (!raw || typeof raw !== "object") return null;
  const rec = raw;
  const id = Number(rec.id);
  const qty = Number(rec.qty ?? rec.quantity);
  const price = Number(rec.price);
  if (!Number.isFinite(id) || !Number.isFinite(qty) || !Number.isFinite(price)) {
    return null;
  }
  const actionRaw = String(rec.action ?? "");
  const action = actionRaw === "Buy" || actionRaw === "Sell" ? actionRaw : null;
  return {
    tradovateFillId: id,
    orderId: finiteOrNull(rec.orderId),
    contractId: finiteOrNull(rec.contractId),
    accountId: finiteOrNull(rec.accountId),
    timestamp: normalizeTimestamp(rec.timestamp),
    tradeDate: typeof rec.tradeDate === "string" ? rec.tradeDate : null,
    action,
    quantity: Math.abs(qty),
    price,
    active: rec.active === void 0 ? true : rec.active === true,
    commission: Number(rec.commission ?? 0) || 0,
    raw: rec
  };
}
function finiteOrNull(v) {
  const n = Number(v);
  return Number.isFinite(n) ? n : null;
}
function normalizeTimestamp(value) {
  const s = String(value ?? "");
  if (!s) return (/* @__PURE__ */ new Date(0)).toISOString();
  const hasTz = /(Z|[+-]\d{2}:?\d{2})$/.test(s);
  const parsed = Date.parse(hasTz ? s : `${s}Z`);
  if (!Number.isFinite(parsed)) return (/* @__PURE__ */ new Date(0)).toISOString();
  return new Date(parsed).toISOString();
}
async function fillList(opts) {
  const limiter = opts.limiter ?? createDefaultLimiter();
  const limit = opts.limit ?? DEFAULT_FILL_PAGE_LIMIT;
  const maxPages = opts.maxPages ?? MAX_FILL_PAGES;
  const url = `${hostFor(opts.environment)}/fill/list`;
  const accountId = opts.accountId && Number.isFinite(opts.accountId) ? opts.accountId : void 0;
  let sinceId = opts.sinceId ?? 0;
  let pages = 0;
  let truncated = false;
  const byId = /* @__PURE__ */ new Map();
  while (pages < maxPages) {
    const data = await requestJson({
      url,
      limiter,
      fetchImpl: opts.fetchImpl,
      headers: authHeaders(opts.accessToken),
      body: accountId === void 0 ? { sinceId, limit } : { sinceId, limit, accountId }
    });
    pages += 1;
    const rows = Array.isArray(data) ? data : [];
    if (rows.length === 0) break;
    let maxId = sinceId;
    for (const row of rows) {
      const fill = normalizeFill(row);
      if (!fill) continue;
      if (accountId !== void 0 && fill.accountId !== null && fill.accountId !== accountId) {
        continue;
      }
      if (!byId.has(fill.tradovateFillId)) {
        byId.set(fill.tradovateFillId, fill);
      }
      if (fill.tradovateFillId > maxId) maxId = fill.tradovateFillId;
    }
    if (maxId <= sinceId) break;
    sinceId = maxId;
    if (rows.length < limit) break;
    if (pages >= maxPages) truncated = true;
  }
  const fills = [...byId.values()].sort(
    (a, b) => a.tradovateFillId - b.tradovateFillId
  );
  return { fills, nextSinceId: sinceId, pages, truncated };
}
async function contractItem(opts) {
  const limiter = opts.limiter ?? createDefaultLimiter();
  const data = await requestJson({
    url: `${hostFor(opts.environment)}/contract/item`,
    limiter,
    fetchImpl: opts.fetchImpl,
    headers: authHeaders(opts.accessToken),
    body: { id: opts.contractId }
  });
  if (!data || typeof data !== "object") return null;
  return {
    id: Number(data.id ?? opts.contractId),
    name: String(data.name ?? ""),
    symbol: data.symbol ? String(data.symbol) : void 0
  };
}

// supabase/functions/_shared/tradovate/sync.ts
var LOCK_TTL_MS = 5 * 60 * 1e3;
async function syncIntegration(opts) {
  const { admin, userId, integrationId } = opts;
  const limiter = opts.limiter ?? createDefaultLimiter();
  const now = opts.now ?? (() => Date.now());
  const base = {
    integrationId,
    status: "error",
    newFills: 0,
    totalFills: 0,
    trades: 0,
    nextSinceId: 0,
    truncated: false,
    pages: 0
  };
  if (!opts.skipLock) {
    const { data: cur } = await admin.from("integrations").select("sync_locked_at").eq("id", integrationId).eq("user_id", userId).maybeSingle();
    const lockedAt = cur?.sync_locked_at ? Date.parse(cur.sync_locked_at) : 0;
    if (lockedAt && now() - lockedAt < LOCK_TTL_MS) {
      return { ...base, status: "locked" };
    }
    await admin.from("integrations").update({ sync_locked_at: new Date(now()).toISOString() }).eq("id", integrationId).eq("user_id", userId);
  }
  try {
    let integration;
    let credentials;
    try {
      ({ integration, credentials } = await loadCredentials(
        admin,
        userId,
        integrationId
      ));
    } catch (e) {
      return {
        ...base,
        status: "error",
        errorCode: e instanceof Error ? e.name : "credential_error"
      };
    }
    const env = integration.environment;
    const scopedAccountId = Number.isFinite(integration.tradovate_account_id) && integration.tradovate_account_id > 0 ? integration.tradovate_account_id : null;
    const auth = await ensureToken({
      credentials,
      environment: env,
      limiter,
      fetchImpl: opts.fetchImpl,
      now,
      stored: credentials.accessToken ? {
        accessToken: credentials.accessToken,
        expirationTime: credentials.accessTokenExpiresAt ?? ""
      } : null
    });
    if (!auth.ok) {
      await markStatus(admin, integrationId, statusForAuthError(auth.code), auth.code, auth.message);
      return { ...base, status: statusForAuthError(auth.code), errorCode: auth.code };
    }
    const accessToken = auth.accessToken;
    if (!credentials.accessToken || credentials.accessToken !== accessToken) {
      await storeSessionToken(admin, userId, integrationId, {
        accessToken,
        expirationTime: auth.expirationTime
      });
    }
    const sinceId = integration.last_fill_id ?? 0;
    const list = await fillList({
      environment: env,
      accessToken,
      limiter,
      fetchImpl: opts.fetchImpl,
      sinceId,
      accountId: scopedAccountId ?? void 0
    });
    let newFills = 0;
    if (list.fills.length > 0) {
      const rows = list.fills.map((f) => ({
        integration_id: integrationId,
        tradovate_fill_id: f.tradovateFillId,
        order_id: f.orderId,
        contract_id: f.contractId,
        account_id: f.accountId,
        fill_timestamp: f.timestamp,
        trade_date: f.tradeDate,
        action: f.action,
        quantity: f.quantity,
        price: f.price,
        active: f.active,
        commission: f.commission,
        raw: f.raw
      }));
      const { data: inserted, error } = await admin.from("tradovate_fills").upsert(rows, {
        onConflict: "integration_id,tradovate_fill_id",
        ignoreDuplicates: true
      }).select("id");
      if (error) {
        await markStatus(admin, integrationId, "error", "fill_upsert_failed", error.message);
        return { ...base, status: "error", errorCode: "fill_upsert_failed" };
      }
      newFills = (inserted ?? []).length;
    }
    if (list.nextSinceId > sinceId) {
      await admin.from("integrations").update({ last_fill_id: list.nextSinceId, last_synced_at: new Date(now()).toISOString() }).eq("id", integrationId).eq("user_id", userId);
    }
    const allFills = await readAllFills(admin, integrationId);
    const resolver = makeContractResolver(env, accessToken, limiter, opts.fetchImpl);
    const contractIds = [
      ...new Set(
        allFills.map((f) => f.contractId).filter((id) => id !== null)
      )
    ];
    await resolver.ensure(contractIds);
    const trades = reconstructTrades(allFills, {
      resolveContract: resolver.resolve,
      commissionPerContract: 0
    });
    await replaceTrades(admin, integrationId, trades);
    await markStatus(admin, integrationId, "connected", null, null);
    return {
      ...base,
      status: "connected",
      newFills,
      totalFills: allFills.length,
      trades: trades.length,
      nextSinceId: list.nextSinceId,
      truncated: list.truncated,
      pages: list.pages
    };
  } catch (e) {
    const code = e instanceof TradovateHttpError ? e.status === 429 ? "rate_limited" : `http_${e.status}` : e instanceof CircuitOpenError ? "circuit_open" : e instanceof Error ? e.name : "unexpected";
    const message = e instanceof Error ? e.message : "sync failed";
    await markStatus(admin, integrationId, "error", code, message).catch(() => {
    });
    return { ...base, status: "error", errorCode: code };
  } finally {
    if (!opts.skipLock) {
      await admin.from("integrations").update({ sync_locked_at: null }).eq("id", integrationId).eq("user_id", userId);
    }
  }
}
function statusForAuthError(code) {
  switch (code) {
    case "invalid_credentials":
      return "invalid_credentials";
    case "api_disabled":
      return "api_disabled";
    case "rate_limited":
    case "circuit_open":
    case "transport":
    case "unexpected":
    default:
      return "error";
  }
}
async function markStatus(admin, integrationId, status, errorCode, errorMessage) {
  await admin.from("integrations").update({
    status,
    last_error_code: errorCode,
    // Message is already redacted by the services; cap length defensively.
    last_error_message: errorMessage ? errorMessage.slice(0, 300) : null,
    last_verified_at: (/* @__PURE__ */ new Date()).toISOString()
  }).eq("id", integrationId);
}
async function readAllFills(admin, integrationId) {
  const { data, error } = await admin.from("tradovate_fills").select(
    "tradovate_fill_id, contract_id, account_id, fill_timestamp, action, quantity, price, commission, active"
  ).eq("integration_id", integrationId).order("tradovate_fill_id", { ascending: true });
  if (error || !data) return [];
  return data.map((r) => ({
    id: Number(r.tradovate_fill_id),
    contractId: r.contract_id === null ? null : Number(r.contract_id),
    accountId: r.account_id === null ? null : Number(r.account_id),
    timestamp: String(r.fill_timestamp),
    action: r.action === "Buy" || r.action === "Sell" ? r.action : null,
    quantity: Number(r.quantity),
    price: Number(r.price),
    commission: Number(r.commission ?? 0),
    active: r.active !== false
  }));
}
async function replaceTrades(admin, integrationId, trades) {
  await admin.from("trades").delete().eq("integration_id", integrationId);
  if (trades.length === 0) return;
  const rows = trades.map((t) => ({
    integration_id: integrationId,
    account_id: t.accountId,
    root_symbol: t.root,
    symbol: t.symbol ?? null,
    side: t.side,
    quantity: t.quantity,
    entry_price: t.entryPrice,
    exit_price: t.exitPrice,
    opened_at: t.openedAt,
    closed_at: t.closedAt,
    realized_pnl: t.realizedPnl,
    commission: t.commission,
    net_pnl: t.netPnl,
    status: t.status,
    method: "fifo",
    fill_ids: t.fillIds,
    dedupe_key: t.dedupeKey
  }));
  await admin.from("trades").upsert(rows, { onConflict: "integration_id,dedupe_key" });
}
function makeContractResolver(env, accessToken, limiter, fetchImpl) {
  const cache = /* @__PURE__ */ new Map();
  return {
    async prime() {
    },
    resolve(contractId) {
      if (contractId === null) return null;
      return cache.get(contractId) ?? null;
    },
    async ensure(contractIds) {
      for (const id of contractIds) {
        if (cache.has(id)) continue;
        try {
          const item = await contractItem({
            environment: env,
            accessToken,
            limiter,
            fetchImpl,
            contractId: id
          });
          if (item) {
            const root = rootFromSymbol(item.name || item.symbol || "");
            cache.set(id, { root, symbol: item.symbol ?? item.name });
          }
        } catch {
        }
      }
    }
  };
}

// supabase/functions/_shared/features.ts
function flagEnabled(value) {
  return value !== "false";
}
function isTradovateEnabled(env = defaultEnv()) {
  return flagEnabled(env.TRADOVATE_ENABLED);
}
function defaultEnv() {
  return {
    TRADOVATE_ENABLED: Deno.env.get("TRADOVATE_ENABLED") ?? void 0,
    AI_KYC_ENABLED: Deno.env.get("AI_KYC_ENABLED") ?? void 0,
    WITHDRAWAL_KYC_GATE_ENABLED: Deno.env.get("WITHDRAWAL_KYC_GATE_ENABLED") ?? void 0
  };
}

// supabase/functions/tradovate-sync/index.ts
var MAX_INTEGRATIONS_PER_RUN = 25;
function isServiceRole(req) {
  const auth = req.headers.get("Authorization") ?? "";
  const token = auth.startsWith("Bearer ") ? auth.slice("Bearer ".length) : "";
  const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";
  return Boolean(serviceKey) && token === serviceKey;
}
serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  if (req.method !== "POST") return json({ error: "method_not_allowed" }, 405);
  if (!isTradovateEnabled()) {
    return json({ ok: true, enabled: false, synced: 0 });
  }
  const admin = createClient2(
    Deno.env.get("SUPABASE_URL") ?? "",
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
    { auth: { autoRefreshToken: false, persistSession: false } }
  );
  if (isServiceRole(req)) {
    const { data, error } = await admin.from("integrations").select("id, user_id, last_synced_at").neq("status", "revoked").order("last_synced_at", { ascending: true, nullsFirst: true }).limit(MAX_INTEGRATIONS_PER_RUN);
    if (error) return json({ error: "list_failed" }, 500);
    const results2 = [];
    for (const row of data ?? []) {
      try {
        results2.push(
          await syncIntegration({
            admin,
            userId: row.user_id,
            integrationId: row.id
          })
        );
      } catch (e) {
        results2.push({
          integrationId: row.id,
          status: "error",
          errorCode: e instanceof Error ? e.name : "unexpected"
        });
      }
    }
    return json({ ok: true, mode: "scheduled", count: results2.length, results: results2 });
  }
  let ctx;
  try {
    ctx = await requireUser(req);
  } catch (e) {
    if (e instanceof UnauthorizedError) return json({ error: "unauthorized" }, 401);
    return json({ error: "unauthorized" }, 401);
  }
  let body = {};
  try {
    body = await req.json();
  } catch {
  }
  const requested = typeof body.integrationId === "string" ? body.integrationId : null;
  const { data: owned } = await admin.from("integrations").select("id").eq("user_id", ctx.user.id).neq("status", "revoked");
  const ids = (owned ?? []).map((r) => r.id);
  const targets = requested ? ids.filter((id) => id === requested) : ids;
  if (targets.length === 0) return json({ error: "integration_not_found" }, 404);
  const results = [];
  for (const id of targets) {
    try {
      results.push(
        await syncIntegration({
          admin,
          userId: ctx.user.id,
          integrationId: id
        })
      );
    } catch (e) {
      results.push({
        integrationId: id,
        status: "error",
        errorCode: e instanceof Error ? e.name : "unexpected"
      });
    }
  }
  return json({ ok: true, mode: "user", count: results.length, results });
});
