// AUTO-GENERATED by scripts/bundle-edge-functions.mjs — do not edit by hand.
// Paste this whole file as the Edge Function body in the Supabase dashboard.


// supabase/functions/tradovate-data/index.ts
import { serve } from "https://deno.land/std@0.190.0/http/server.ts";

// supabase/functions/_shared/tradovate/auth.ts
import {
  createClient
} from "https://esm.sh/@supabase/supabase-js@2.45.0";
var UnauthorizedError = class extends Error {
  constructor() {
    super("unauthorized");
    this.name = "UnauthorizedError";
  }
};
async function requireUser(req) {
  const auth = req.headers.get("Authorization") ?? "";
  if (!auth.startsWith("Bearer ")) throw new UnauthorizedError();
  const token = auth.slice("Bearer ".length);
  const userClient = createClient(
    Deno.env.get("SUPABASE_URL") ?? "",
    Deno.env.get("SUPABASE_ANON_KEY") ?? "",
    { global: { headers: { Authorization: auth } } }
  );
  const { data, error } = await userClient.auth.getUser(token);
  if (error || !data?.user) throw new UnauthorizedError();
  const admin = createClient(
    Deno.env.get("SUPABASE_URL") ?? "",
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
    { auth: { autoRefreshToken: false, persistSession: false } }
  );
  return { user: { id: data.user.id, email: data.user.email }, admin };
}
var corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS"
};
function json(body, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" }
  });
}

// supabase/functions/_shared/tradovate/credentialStore.ts
var CredentialStoreError = class extends Error {
  constructor(code, message) {
    super(message ?? code);
    this.code = code;
    this.name = "CredentialStoreError";
  }
};
async function listIntegrations(admin, userId) {
  const { data, error } = await admin.from("integrations").select(
    "id, user_id, environment, tradovate_account_id, tradovate_user_id, account_spec, label, status, last_fill_id, token_expires_at"
  ).eq("user_id", userId).neq("status", "revoked").order("created_at", { ascending: false });
  if (error) throw new CredentialStoreError("integration_list_failed", error.message);
  return data ?? [];
}

// supabase/functions/_shared/tradovate/performance.ts
var num = (v) => {
  const n = typeof v === "number" ? v : parseFloat(String(v ?? 0));
  return Number.isFinite(n) ? n : 0;
};
function round2(n) {
  return Math.round((n + Number.EPSILON) * 100) / 100;
}
function utcDay(iso) {
  const t = Date.parse(iso);
  if (!Number.isFinite(t)) return null;
  return new Date(t).toISOString().slice(0, 10);
}
function isoWeekKey(iso) {
  const t = Date.parse(iso);
  if (!Number.isFinite(t)) return null;
  const d = new Date(t);
  const target = new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate()));
  const dayNum = (target.getUTCDay() + 6) % 7;
  target.setUTCDate(target.getUTCDate() - dayNum + 3);
  const firstThursday = new Date(Date.UTC(target.getUTCFullYear(), 0, 4));
  const fdayNum = (firstThursday.getUTCDay() + 6) % 7;
  firstThursday.setUTCDate(firstThursday.getUTCDate() - fdayNum + 3);
  const week = 1 + Math.round((target.getTime() - firstThursday.getTime()) / (7 * 864e5));
  return `${target.getUTCFullYear()}-W${String(week).padStart(2, "0")}`;
}
function closedSorted(trades) {
  return trades.filter((t) => t.status === "closed" && Boolean(t.closed_at)).slice().sort((a, b) => Date.parse(a.closed_at) - Date.parse(b.closed_at));
}
function computePerformance(trades, now = /* @__PURE__ */ new Date()) {
  const closed = closedSorted(trades);
  const openTrades = trades.filter((t) => t.status === "open").length;
  if (closed.length === 0) {
    return {
      hasData: false,
      closedTrades: 0,
      openTrades,
      wins: 0,
      losses: 0,
      breakEven: 0,
      winRate: null,
      profitFactor: null,
      avgWin: null,
      avgLoss: null,
      bestTrade: null,
      worstTrade: null,
      maxDrawdown: null,
      totalNet: 0,
      grossProfit: 0,
      grossLoss: 0,
      totalCommission: 0,
      equityCurve: [],
      calendar: [],
      realized: { day: 0, week: 0, month: 0, allTime: 0 }
    };
  }
  let wins = 0;
  let losses = 0;
  let breakEven = 0;
  let grossProfit = 0;
  let grossLoss = 0;
  let commission = 0;
  let best = null;
  let worst = null;
  let cumulative = 0;
  let peak = 0;
  let maxDrawdown = 0;
  const equityCurve = [];
  const byDay = /* @__PURE__ */ new Map();
  const nowDay = utcDay(now.toISOString());
  const nowWeek = isoWeekKey(now.toISOString());
  const nowMonth = nowDay ? nowDay.slice(0, 7) : null;
  const realized = { day: 0, week: 0, month: 0, allTime: 0 };
  for (const t of closed) {
    const pnl = num(t.net_pnl);
    cumulative += pnl;
    peak = Math.max(peak, cumulative);
    maxDrawdown = Math.min(maxDrawdown, cumulative - peak);
    if (pnl > 0) {
      wins++;
      grossProfit += pnl;
    } else if (pnl < 0) {
      losses++;
      grossLoss += pnl;
    } else {
      breakEven++;
    }
    best = best === null ? pnl : Math.max(best, pnl);
    worst = worst === null ? pnl : Math.min(worst, pnl);
    commission += num(t.commission);
    equityCurve.push({ t: t.closed_at, value: round2(cumulative) });
    const day = utcDay(t.closed_at);
    if (day) {
      const cur = byDay.get(day) ?? { date: day, pnl: 0, trades: 0 };
      cur.pnl = round2(cur.pnl + pnl);
      cur.trades += 1;
      byDay.set(day, cur);
    }
    realized.allTime = round2(realized.allTime + pnl);
    if (day && nowDay && day === nowDay) realized.day = round2(realized.day + pnl);
    if (nowMonth && day && day.slice(0, 7) === nowMonth) {
      realized.month = round2(realized.month + pnl);
    }
    const week = isoWeekKey(t.closed_at);
    if (nowWeek && week === nowWeek) realized.week = round2(realized.week + pnl);
  }
  const decided = wins + losses;
  return {
    hasData: true,
    closedTrades: closed.length,
    openTrades,
    wins,
    losses,
    breakEven,
    winRate: decided === 0 ? null : round4(wins / decided),
    profitFactor: grossLoss === 0 ? null : round4(grossProfit / Math.abs(grossLoss)),
    avgWin: wins === 0 ? null : round2(grossProfit / wins),
    avgLoss: losses === 0 ? null : round2(grossLoss / losses),
    bestTrade: best === null ? null : round2(best),
    worstTrade: worst === null ? null : round2(worst),
    maxDrawdown: round2(maxDrawdown),
    totalNet: round2(cumulative),
    grossProfit: round2(grossProfit),
    grossLoss: round2(grossLoss),
    totalCommission: round2(commission),
    equityCurve,
    calendar: [...byDay.values()].sort((a, b) => a.date < b.date ? -1 : 1),
    realized
  };
}
function round4(n) {
  return Math.round((n + Number.EPSILON) * 1e4) / 1e4;
}

// supabase/functions/_shared/features.ts
function flagEnabled(value) {
  return value !== "false";
}
function isTradovateEnabled(env = defaultEnv()) {
  return flagEnabled(env.TRADOVATE_ENABLED);
}
function featureDisabledBody(feature) {
  return {
    ok: false,
    error: "feature_disabled",
    feature,
    message: `${feature} is disabled by its runtime switch.`
  };
}
function defaultEnv() {
  return {
    TRADOVATE_ENABLED: Deno.env.get("TRADOVATE_ENABLED") ?? void 0,
    AI_KYC_ENABLED: Deno.env.get("AI_KYC_ENABLED") ?? void 0,
    WITHDRAWAL_KYC_GATE_ENABLED: Deno.env.get("WITHDRAWAL_KYC_GATE_ENABLED") ?? void 0
  };
}

// supabase/functions/tradovate-data/index.ts
serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  if (req.method !== "GET" && req.method !== "POST") {
    return json({ error: "method_not_allowed" }, 405);
  }
  if (!isTradovateEnabled()) {
    return json(featureDisabledBody("tradovate"), 503);
  }
  let ctx;
  try {
    ctx = await requireUser(req);
  } catch (e) {
    if (e instanceof UnauthorizedError) return json({ error: "unauthorized" }, 401);
    return json({ error: "unauthorized" }, 401);
  }
  const integrations = await listIntegrations(ctx.admin, ctx.user.id);
  const ids = integrations.map((i) => i.id);
  if (ids.length === 0) {
    return json({
      trades: [],
      fills: [],
      summary: {
        netPnl: 0,
        grossPnl: 0,
        commission: 0,
        openTrades: 0,
        closedTrades: 0,
        byAccount: []
      },
      performance: computePerformance([])
    });
  }
  const url = new URL(req.url);
  const requestedAccount = url.searchParams.get("accountId");
  const accountFilter = requestedAccount && Number.isFinite(Number(requestedAccount)) ? Number(requestedAccount) : null;
  let query = ctx.admin.from("trades").select(
    "id, integration_id, account_id, root_symbol, symbol, side, quantity, entry_price, exit_price, opened_at, closed_at, realized_pnl, commission, net_pnl, status"
  ).in("integration_id", ids);
  if (accountFilter !== null) query = query.eq("account_id", accountFilter);
  const { data: trades, error } = await query.order("opened_at", { ascending: false }).limit(2e3);
  if (error) return json({ error: "trades_failed" }, 500);
  let fillsQuery = ctx.admin.from("tradovate_fills").select(
    "tradovate_fill_id, integration_id, account_id, contract_id, fill_timestamp, action, quantity, price, commission, active"
  ).in("integration_id", ids);
  if (accountFilter !== null) fillsQuery = fillsQuery.eq("account_id", accountFilter);
  const { data: fills } = await fillsQuery.order("fill_timestamp", { ascending: false }).limit(5e3);
  const rows = trades ?? [];
  const closed = rows.filter((t) => t.status === "closed");
  const byAccountMap = /* @__PURE__ */ new Map();
  for (const t of rows) {
    const key = t.account_id ?? null;
    const entry = byAccountMap.get(key) ?? { accountId: key, netPnl: 0, trades: 0 };
    entry.netPnl += Number(t.net_pnl ?? 0);
    entry.trades += 1;
    byAccountMap.set(key, entry);
  }
  const round22 = (n) => Math.round((n + Number.EPSILON) * 100) / 100;
  return json({
    trades: rows,
    fills: fills ?? [],
    summary: {
      netPnl: round22(rows.reduce((s, t) => s + Number(t.net_pnl ?? 0), 0)),
      grossPnl: round22(rows.reduce((s, t) => s + Number(t.realized_pnl ?? 0), 0)),
      commission: round22(rows.reduce((s, t) => s + Number(t.commission ?? 0), 0)),
      openTrades: rows.length - closed.length,
      closedTrades: closed.length,
      byAccount: [...byAccountMap.values()].map((a) => ({ ...a, netPnl: round22(a.netPnl) }))
    },
    // Real performance stats computed from the same closed trades the client
    // renders, so the numbers shown and the numbers aggregated can't diverge.
    performance: computePerformance(rows.map((t) => ({
      root_symbol: t.root_symbol,
      symbol: t.symbol,
      side: t.side,
      quantity: Number(t.quantity),
      entry_price: Number(t.entry_price),
      exit_price: t.exit_price === null ? null : Number(t.exit_price),
      opened_at: t.opened_at,
      closed_at: t.closed_at,
      realized_pnl: Number(t.realized_pnl ?? 0),
      commission: Number(t.commission ?? 0),
      net_pnl: Number(t.net_pnl ?? 0),
      status: t.status
    })))
  });
});
