// AUTO-GENERATED by scripts/bundle-edge-functions.mjs — do not edit by hand.
// Paste this whole file as the Edge Function body in the Supabase dashboard.


// supabase/functions/tradovate-connect/index.ts
import { serve } from "https://deno.land/std@0.190.0/http/server.ts";

// supabase/functions/_shared/tradovate/auth.ts
import {
  createClient
} from "https://esm.sh/@supabase/supabase-js@2.45.0";
var UnauthorizedError = class extends Error {
  constructor() {
    super("unauthorized");
    this.name = "UnauthorizedError";
  }
};
async function requireUser(req) {
  const auth = req.headers.get("Authorization") ?? "";
  if (!auth.startsWith("Bearer ")) throw new UnauthorizedError();
  const token = auth.slice("Bearer ".length);
  const userClient = createClient(
    Deno.env.get("SUPABASE_URL") ?? "",
    Deno.env.get("SUPABASE_ANON_KEY") ?? "",
    { global: { headers: { Authorization: auth } } }
  );
  const { data, error } = await userClient.auth.getUser(token);
  if (error || !data?.user) throw new UnauthorizedError();
  const admin = createClient(
    Deno.env.get("SUPABASE_URL") ?? "",
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
    { auth: { autoRefreshToken: false, persistSession: false } }
  );
  return { user: { id: data.user.id, email: data.user.email }, admin };
}
var corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS"
};
function json(body, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" }
  });
}

// supabase/functions/_shared/tradovate/rateLimiter.ts
var CircuitOpenError = class extends Error {
  constructor(retryAfterMs) {
    super(`rate-limit circuit open for another ${retryAfterMs}ms`);
    this.retryAfterMs = retryAfterMs;
    this.name = "CircuitOpenError";
  }
};
var SECOND = 1e3;
var MINUTE = 60 * SECOND;
var HOUR = 60 * MINUTE;
var defaultSleep = (ms) => new Promise((resolve) => setTimeout(resolve, Math.max(0, ms)));
function parseTimePenalty(body) {
  if (!body || typeof body !== "object") return null;
  const rec = body;
  const hasTicket = "p-ticket" in rec;
  const hasTime = "p-time" in rec;
  const hasCaptcha = "p-captcha" in rec;
  if (!hasTicket && !hasTime && !hasCaptcha) return null;
  const rawTime = rec["p-time"];
  const waitSeconds = typeof rawTime === "number" && Number.isFinite(rawTime) ? Math.max(0, rawTime) : 0;
  const ticket = typeof rec["p-ticket"] === "string" ? rec["p-ticket"] : null;
  const captcha = rec["p-captcha"] === true;
  return { ticket, waitSeconds, captcha };
}
var TradovateRateLimiter = class {
  perSecond;
  perMinute;
  perHour;
  baseBackoffMs;
  maxBackoffMs;
  captchaCircuitMs;
  rateLimitCircuitMs;
  sleep;
  now;
  random;
  /** Timestamps (ms) of accepted requests within the last hour. */
  history = [];
  circuitOpenUntil = 0;
  /** Consecutive plain-429 counter, reset on success. */
  consecutive429 = 0;
  constructor(opts = {}) {
    this.perSecond = opts.requestsPerSecond ?? 4;
    this.perMinute = opts.requestsPerMinute ?? 60;
    this.perHour = opts.requestsPerHour ?? 4500;
    this.baseBackoffMs = opts.baseBackoffMs ?? 500;
    this.maxBackoffMs = opts.maxBackoffMs ?? 3e4;
    this.captchaCircuitMs = opts.captchaCircuitMs ?? HOUR;
    this.rateLimitCircuitMs = opts.rateLimitCircuitMs ?? MINUTE;
    this.sleep = opts.sleep ?? defaultSleep;
    this.now = opts.now ?? (() => Date.now());
    this.random = opts.random ?? Math.random;
  }
  /** Throw CircuitOpenError while a p-captcha / repeated-429 circuit is open. */
  assertCircuitClosed() {
    const remaining = this.circuitOpenUntil - this.now();
    if (remaining > 0) throw new CircuitOpenError(remaining);
  }
  isCircuitOpen() {
    return this.circuitOpenUntil > this.now();
  }
  /** Wait until all three rolling windows allow one more request. */
  async waitForSlot() {
    this.assertCircuitClosed();
    for (; ; ) {
      const now = this.now();
      this.history = this.history.filter((t) => now - t < HOUR);
      const waits = [
        this.windowWait(now, SECOND, this.perSecond),
        this.windowWait(now, MINUTE, this.perMinute),
        this.windowWait(now, HOUR, this.perHour)
      ];
      const wait = Math.max(0, ...waits);
      if (wait <= 0) break;
      await this.sleep(wait);
      this.assertCircuitClosed();
    }
    this.history.push(this.now());
  }
  windowWait(now, windowMs, limit) {
    const inWindow = this.history.filter((t) => now - t < windowMs);
    if (inWindow.length < limit) return 0;
    const oldest = Math.min(...inWindow);
    return oldest + windowMs - now;
  }
  /** Exponential backoff with jitter for a plain 429. */
  async backoffFor429() {
    this.consecutive429 += 1;
    if (this.consecutive429 >= 5) {
      this.circuitOpenUntil = this.now() + this.rateLimitCircuitMs;
    }
    const exp = Math.min(
      this.maxBackoffMs,
      this.baseBackoffMs * 2 ** (this.consecutive429 - 1)
    );
    const jitter = Math.floor(this.random() * (exp / 2));
    const wait = exp + jitter;
    await this.sleep(wait);
    return wait;
  }
  /**
   * Handle a p-time / p-ticket penalty. Returns the ticket the caller must
   * echo back in the request body. Opens the circuit (and throws) on captcha.
   */
  async handlePenalty(penalty) {
    if (penalty.captcha) {
      this.circuitOpenUntil = this.now() + this.captchaCircuitMs;
      throw new CircuitOpenError(this.captchaCircuitMs);
    }
    if (penalty.waitSeconds > 0) {
      await this.sleep(penalty.waitSeconds * SECOND);
    }
    return penalty.ticket;
  }
  /** Reset the consecutive-429 counter after any successful call. */
  onSuccess() {
    this.consecutive429 = 0;
  }
  /** Test/diagnostic snapshot; contains no credentials. */
  snapshot() {
    return {
      historyLength: this.history.length,
      consecutive429: this.consecutive429,
      circuitOpenUntil: this.circuitOpenUntil,
      circuitOpen: this.isCircuitOpen()
    };
  }
};
function createDefaultLimiter(opts = {}) {
  return new TradovateRateLimiter({
    requestsPerSecond: 4,
    requestsPerMinute: 60,
    requestsPerHour: 4500,
    ...opts
  });
}

// supabase/functions/_shared/tradovate/http.ts
var TradovateHttpError = class extends Error {
  constructor(status, body, message) {
    super(message);
    this.status = status;
    this.body = body;
    this.name = "TradovateHttpError";
  }
};
async function requestJson(opts) {
  const fetchImpl = opts.fetchImpl ?? fetch;
  const maxAttempts = opts.maxAttempts ?? 6;
  const method = opts.method ?? "POST";
  let body = opts.body ?? null;
  let attempts = 0;
  for (; ; ) {
    attempts += 1;
    opts.limiter.assertCircuitClosed();
    await opts.limiter.waitForSlot();
    const res = await fetchImpl(opts.url, {
      method,
      headers: {
        "Content-Type": "application/json",
        ...opts.headers ?? {}
      },
      body: body === null ? void 0 : JSON.stringify(body),
      signal: opts.signal
    });
    if (res.status === 429) {
      const parsed = await safeJson(res);
      const penalty = parseTimePenalty(parsed);
      if (penalty && !penalty.captcha && attempts < maxAttempts) {
        const ticket = await opts.limiter.handlePenalty(penalty);
        if (ticket) {
          body = { ...body ?? {}, "p-ticket": ticket };
        }
        continue;
      }
      if (penalty && penalty.captcha) {
        await opts.limiter.handlePenalty(penalty);
      }
      if (attempts < maxAttempts) {
        await opts.limiter.backoffFor429();
        continue;
      }
      throw new TradovateHttpError(
        429,
        parsed,
        "Tradovate rate limit persisted beyond retry budget"
      );
    }
    if (!res.ok) {
      throw new TradovateHttpError(
        res.status,
        await safeJson(res),
        `Tradovate HTTP ${res.status}`
      );
    }
    opts.limiter.onSuccess();
    return await safeJson(res);
  }
}
async function safeJson(res) {
  const text = await res.text();
  if (!text) return null;
  try {
    return JSON.parse(text);
  } catch {
    return text;
  }
}

// supabase/functions/_shared/tradovate/appCredentials.ts
function resolveAppCredentials(clientCid, clientSec, env = (k) => Deno.env.get(k)) {
  const cid = clientCid?.trim() || env("TRADOVATE_APP_CID")?.trim() || void 0;
  const sec = clientSec?.trim() || env("TRADOVATE_APP_SECRET")?.trim() || void 0;
  const source = clientCid || clientSec ? "client" : cid || sec ? "server" : "none";
  return {
    cid,
    sec,
    appId: env("TRADOVATE_APP_ID")?.trim() || "Braxel",
    appVersion: env("TRADOVATE_APP_VERSION")?.trim() || "1.3.0",
    source
  };
}

// supabase/functions/_shared/tradovate/crypto.ts
var KEY_VERSION = 1;
var IV_BYTES = 12;
var TAG_BYTES = 16;
var KEY_BYTES = 32;
var EncryptionConfigError = class extends Error {
  constructor(message) {
    super(message);
    this.name = "EncryptionConfigError";
  }
};
function isEncryptionConfigured() {
  return (Deno.env.get("TRADOVATE_ENCRYPTION_KEY") ?? "").length > 0;
}
function base64ToBytes(b64) {
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}
function bytesToBase64(bytes) {
  let bin = "";
  for (const b of bytes) bin += String.fromCharCode(b);
  return btoa(bin);
}
function hexToBytes(hex) {
  const clean = hex.trim().toLowerCase();
  if (!/^[0-9a-f]+$/.test(clean) || clean.length % 2 !== 0) return null;
  const out = new Uint8Array(clean.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(clean.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}
function tryRawKey(secret) {
  const hex = hexToBytes(secret);
  if (hex && hex.length === KEY_BYTES) return hex;
  try {
    const b64 = base64ToBytes(secret);
    if (b64.length === KEY_BYTES) return b64;
  } catch {
  }
  return null;
}
async function importAesKey(secret) {
  if (!secret) {
    throw new EncryptionConfigError(
      "TRADOVATE_ENCRYPTION_KEY is not set"
    );
  }
  let raw = tryRawKey(secret);
  if (!raw) {
    const digest = await crypto.subtle.digest(
      "SHA-256",
      new TextEncoder().encode(secret)
    );
    raw = new Uint8Array(digest);
  }
  return await crypto.subtle.importKey(
    "raw",
    raw,
    { name: "AES-GCM" },
    false,
    ["encrypt", "decrypt"]
  );
}
async function encryptCredentials(creds, secret) {
  const key = await importAesKey(secret);
  const iv = crypto.getRandomValues(new Uint8Array(IV_BYTES));
  const plaintext = new TextEncoder().encode(JSON.stringify(creds));
  const sealed = new Uint8Array(
    await crypto.subtle.encrypt(
      { name: "AES-GCM", iv, tagLength: 128 },
      key,
      plaintext
    )
  );
  const tag = sealed.slice(sealed.length - TAG_BYTES);
  const body = sealed.slice(0, sealed.length - TAG_BYTES);
  return {
    ciphertext: bytesToBase64(body),
    iv: bytesToBase64(iv),
    authTag: bytesToBase64(tag),
    keyVersion: KEY_VERSION
  };
}
function redact(value) {
  const s = typeof value === "string" ? value : JSON.stringify(value ?? "");
  return s.replace(/Bearer\s+[A-Za-z0-9._~+/-]+=*/gi, "Bearer [REDACTED]").replace(/(password|passwd|pwd)"?\s*[:=]\s*"?[^",}\s]+/gi, "$1=[REDACTED]").replace(/(accessToken|access_token|token|sec|cid|authorization)"?\s*[:=]\s*"?[^",}\s]+/gi, "$1=[REDACTED]");
}

// supabase/functions/_shared/tradovate/authService.ts
var TRADOVATE_HOSTS = {
  demo: "https://demo.tradovateapi.com/v1",
  live: "https://live.tradovateapi.com/v1"
};
var TOKEN_RENEW_MARGIN_MS = 5 * 60 * 1e3;
function hostFor(env) {
  return TRADOVATE_HOSTS[env];
}
async function authenticate(opts) {
  const limiter = opts.limiter ?? createDefaultLimiter();
  const { credentials, environment } = opts;
  const url = `${hostFor(environment)}/auth/accesstokenrequest`;
  const app = resolveAppCredentials(credentials.cid, credentials.sec);
  const body = {
    name: credentials.name,
    password: credentials.password,
    appId: credentials.appId ?? app.appId,
    appVersion: credentials.appVersion ?? app.appVersion,
    deviceId: credentials.deviceId ?? "braxel-terminal"
  };
  if (app.cid) body.cid = app.cid;
  if (app.sec) body.sec = app.sec;
  try {
    const data = await requestJson({
      url,
      limiter,
      fetchImpl: opts.fetchImpl,
      body
    });
    const accessToken = typeof data?.accessToken === "string" ? data.accessToken : null;
    if (!accessToken) {
      const text = extractErrorText(data);
      if (text && /incorrect username or password|invalid (username|password|credentials)|bad credentials/i.test(text)) {
        return { ok: false, code: "invalid_credentials", message: text };
      }
      if (text && /api access|not enabled|entitlement|subscription|not entitled/i.test(text)) {
        return { ok: false, code: "api_disabled", message: text };
      }
      return {
        ok: false,
        code: "unexpected",
        message: text ?? "Tradovate returned no access token"
      };
    }
    return {
      ok: true,
      accessToken,
      expirationTime: String(data.expirationTime ?? ""),
      userId: Number(data.userId ?? 0),
      name: String(data.name ?? credentials.name)
    };
  } catch (err) {
    return classifyAuthError(err);
  }
}
function classifyAuthError(err) {
  if (err instanceof CircuitOpenError) {
    return {
      ok: false,
      code: "circuit_open",
      message: "Tradovate asked for a captcha; retry in about an hour",
      retryAfterMs: err.retryAfterMs
    };
  }
  if (err instanceof TradovateHttpError) {
    const text = extractErrorText(err.body);
    if (err.status === 401) {
      return {
        ok: false,
        code: "invalid_credentials",
        message: text ?? "Tradovate rejected the username or password"
      };
    }
    if (err.status === 403 || /api access|not enabled|entitlement/i.test(text ?? "")) {
      return {
        ok: false,
        code: "api_disabled",
        message: text ?? "API access is not enabled for this account"
      };
    }
    if (err.status === 429) {
      return {
        ok: false,
        code: "rate_limited",
        message: "Tradovate rate limit reached"
      };
    }
    return {
      ok: false,
      code: "unexpected",
      message: text ?? `Tradovate returned HTTP ${err.status}`
    };
  }
  return {
    ok: false,
    code: "transport",
    message: "Could not reach Tradovate"
  };
}
function extractErrorText(body) {
  if (!body) return null;
  if (typeof body === "string") return redact(body.slice(0, 200));
  if (typeof body === "object") {
    const rec = body;
    for (const key of ["errorText", "error", "message", "detail"]) {
      const v = rec[key];
      if (typeof v === "string" && v) return redact(v.slice(0, 200));
    }
  }
  return null;
}

// supabase/functions/_shared/tradovate/restService.ts
function authHeaders(accessToken) {
  return { Authorization: `Bearer ${accessToken}` };
}
async function accountList(opts) {
  const limiter = opts.limiter ?? createDefaultLimiter();
  const data = await requestJson({
    url: `${hostFor(opts.environment)}/account/list`,
    limiter,
    fetchImpl: opts.fetchImpl,
    headers: authHeaders(opts.accessToken),
    body: {}
  });
  if (!Array.isArray(data)) return [];
  return data.map(normalizeAccount).filter((a) => !!a);
}
function normalizeAccount(raw) {
  if (!raw || typeof raw !== "object") return null;
  const rec = raw;
  const id = Number(rec.id);
  if (!Number.isFinite(id)) return null;
  return {
    id,
    name: String(rec.name ?? ""),
    userId: Number(rec.userId ?? 0),
    accountType: rec.accountType ? String(rec.accountType) : void 0,
    active: rec.active === void 0 ? void 0 : rec.active === true,
    simulation: rec.simulation === void 0 ? void 0 : rec.simulation === true
  };
}

// supabase/functions/_shared/tradovate/credentialStore.ts
var CredentialStoreError = class extends Error {
  constructor(code, message) {
    super(message ?? code);
    this.code = code;
    this.name = "CredentialStoreError";
  }
};
async function upsertIntegrationWithCredentials(admin, input) {
  if (!isEncryptionConfigured()) {
    throw new CredentialStoreError(
      "encryption_not_configured",
      "TRADOVATE_ENCRYPTION_KEY is not set"
    );
  }
  const secret = Deno.env.get("TRADOVATE_ENCRYPTION_KEY") ?? "";
  const parts = await encryptCredentials(input.credentials, secret);
  const { data: integ, error: integErr } = await admin.from("integrations").upsert({
    user_id: input.userId,
    provider: "tradovate",
    environment: input.environment,
    tradovate_account_id: input.tradovateAccountId,
    tradovate_user_id: input.tradovateUserId ?? null,
    account_spec: input.accountSpec ?? null,
    label: input.label ?? null,
    status: input.status ?? "pending"
  }, { onConflict: "user_id,provider,environment,tradovate_account_id" }).select("id").single();
  if (integErr || !integ) {
    throw new CredentialStoreError("integration_upsert_failed", integErr?.message);
  }
  const { error: credErr } = await admin.from("integration_credentials").upsert({
    integration_id: integ.id,
    ciphertext: parts.ciphertext,
    iv: parts.iv,
    auth_tag: parts.authTag,
    key_version: parts.keyVersion
  }, { onConflict: "integration_id" });
  if (credErr) {
    throw new CredentialStoreError("credential_upsert_failed", credErr.message);
  }
  return integ.id;
}

// supabase/functions/_shared/tradovate/environment.ts
var KNOWN_ENVIRONMENTS = ["demo", "live"];
var DEFAULT_ALLOWED_ENVIRONMENTS = ["demo"];
function parseAllowedEnvironments(raw) {
  const tokens = (raw ?? "").split(",").map((t) => t.trim().toLowerCase()).filter(Boolean).filter(
    (t) => KNOWN_ENVIRONMENTS.includes(t)
  );
  const unique = [...new Set(tokens)];
  return unique.length > 0 ? unique : [...DEFAULT_ALLOWED_ENVIRONMENTS];
}
function allowedEnvironments(env = (k) => Deno.env.get(k)) {
  return parseAllowedEnvironments(env("TRADOVATE_ALLOWED_ENVIRONMENTS"));
}
function resolveRequestedEnvironment(requested, env = (k) => Deno.env.get(k)) {
  const allowed = allowedEnvironments(env);
  if (requested !== "demo" && requested !== "live") {
    return {
      ok: false,
      code: "invalid_environment",
      message: "Choose a supported environment.",
      allowed
    };
  }
  if (!allowed.includes(requested)) {
    return {
      ok: false,
      code: "environment_not_allowed",
      message: `The ${requested} environment is not enabled for this deployment.`,
      allowed
    };
  }
  return { ok: true, environment: requested, allowed };
}

// supabase/functions/_shared/tradovate/accountSelection.ts
function selectAccount(accounts, requestedAccountId) {
  if (accounts.length === 0) return { kind: "no_accounts" };
  if (requestedAccountId !== null) {
    if (!Number.isFinite(requestedAccountId)) return { kind: "invalid_account" };
    const found = accounts.find((a) => a.id === requestedAccountId);
    return found ? { kind: "chosen", account: found } : { kind: "not_available" };
  }
  if (accounts.length === 1) return { kind: "chosen", account: accounts[0] };
  const active = accounts.find((a) => a.active === true);
  if (!active) return { kind: "no_active" };
  return { kind: "required", preselectAccountId: active.id };
}

// supabase/functions/_shared/features.ts
function flagEnabled(value) {
  return value !== "false";
}
function isTradovateEnabled(env = defaultEnv()) {
  return flagEnabled(env.TRADOVATE_ENABLED);
}
function featureDisabledBody(feature) {
  return {
    ok: false,
    error: "feature_disabled",
    feature,
    message: `${feature} is disabled by its runtime switch.`
  };
}
function defaultEnv() {
  return {
    TRADOVATE_ENABLED: Deno.env.get("TRADOVATE_ENABLED") ?? void 0,
    AI_KYC_ENABLED: Deno.env.get("AI_KYC_ENABLED") ?? void 0,
    WITHDRAWAL_KYC_GATE_ENABLED: Deno.env.get("WITHDRAWAL_KYC_GATE_ENABLED") ?? void 0
  };
}

// supabase/functions/tradovate-connect/index.ts
function accountPayload(a) {
  return { id: a.id, name: a.name, simulation: a.simulation, active: a.active };
}
serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  if (req.method !== "POST") return json({ error: "method_not_allowed" }, 405);
  if (!isTradovateEnabled()) {
    return json(featureDisabledBody("tradovate"), 503);
  }
  let ctx;
  try {
    ctx = await requireUser(req);
  } catch (e) {
    if (e instanceof UnauthorizedError) return json({ error: "unauthorized" }, 401);
    return json({ error: "unauthorized" }, 401);
  }
  let body;
  try {
    body = await req.json();
  } catch {
    return json({ error: "invalid_json" }, 400);
  }
  const requestedEnvironment = body.environment;
  const name = typeof body.name === "string" ? body.name.trim() : "";
  const password = typeof body.password === "string" ? body.password : "";
  const cid = typeof body.cid === "string" && body.cid.trim() ? body.cid.trim() : void 0;
  const sec = typeof body.sec === "string" && body.sec.trim() ? body.sec.trim() : void 0;
  const label = typeof body.label === "string" ? body.label.slice(0, 80) : void 0;
  const requestedAccountId = body.accountId === void 0 || body.accountId === null ? null : Number(body.accountId);
  const envDecision = resolveRequestedEnvironment(requestedEnvironment);
  if (!envDecision.ok) {
    return json({
      ok: false,
      code: envDecision.code,
      message: envDecision.message,
      allowedEnvironments: envDecision.allowed
    }, 422);
  }
  const environment = envDecision.environment;
  if (!name || !password) {
    return json({ ok: false, code: "missing_credentials" }, 422);
  }
  const limiter = createDefaultLimiter();
  const auth = await authenticate({
    credentials: { name, password, cid, sec },
    environment,
    limiter
  });
  if (!auth.ok) {
    return json({ ok: false, code: auth.code, message: auth.message }, 422);
  }
  let accounts = [];
  try {
    accounts = await accountList({
      environment,
      accessToken: auth.accessToken,
      limiter
    });
  } catch {
    return json({
      ok: false,
      code: "accounts_unavailable",
      message: "Could not read your Tradovate accounts right now. Try again shortly."
    }, 502);
  }
  if (accounts.length === 0) {
    return json({
      ok: false,
      code: "no_accounts",
      message: "This Tradovate login has no accounts. Contact Tradovate support."
    }, 422);
  }
  const selection = selectAccount(accounts, requestedAccountId);
  switch (selection.kind) {
    case "no_accounts":
      return json({ ok: false, code: "no_accounts" }, 422);
    case "invalid_account":
      return json({ ok: false, code: "invalid_account" }, 422);
    case "not_available":
      return json({
        ok: false,
        code: "account_not_available",
        message: "That account is not available for this login.",
        accounts: accounts.map(accountPayload)
      }, 422);
    case "no_active":
      return json({
        ok: false,
        code: "no_active_account",
        message: "None of your Tradovate accounts are active. Contact Tradovate support."
      }, 422);
    case "required":
      return json({
        ok: false,
        code: "account_selection_required",
        accounts: accounts.map(accountPayload),
        preselectAccountId: selection.preselectAccountId
      }, 200);
    case "chosen":
      break;
  }
  const chosen = selection.account;
  try {
    const integrationId = await upsertIntegrationWithCredentials(ctx.admin, {
      userId: ctx.user.id,
      environment,
      tradovateAccountId: chosen.id,
      tradovateUserId: auth.userId,
      accountSpec: chosen.name,
      label: label ?? chosen.name,
      credentials: { name, password, cid, sec },
      status: "connected"
    });
    return json({
      ok: true,
      status: "connected",
      integrationId,
      accounts: accounts.map(accountPayload),
      accountId: chosen.id
    });
  } catch (e) {
    if (e instanceof CredentialStoreError) {
      return json({ ok: false, code: e.code, message: e.message }, 500);
    }
    return json({ ok: false, code: "unexpected" }, 500);
  }
});
