// AUTO-GENERATED by scripts/bundle-edge-functions.mjs — do not edit by hand.
// Paste this whole file as the Edge Function body in the Supabase dashboard.


// supabase/functions/tradovate-status/index.ts
import { serve } from "https://deno.land/std@0.190.0/http/server.ts";

// supabase/functions/_shared/tradovate/auth.ts
import {
  createClient
} from "https://esm.sh/@supabase/supabase-js@2.45.0";
var UnauthorizedError = class extends Error {
  constructor() {
    super("unauthorized");
    this.name = "UnauthorizedError";
  }
};
async function requireUser(req) {
  const auth = req.headers.get("Authorization") ?? "";
  if (!auth.startsWith("Bearer ")) throw new UnauthorizedError();
  const token = auth.slice("Bearer ".length);
  const userClient = createClient(
    Deno.env.get("SUPABASE_URL") ?? "",
    Deno.env.get("SUPABASE_ANON_KEY") ?? "",
    { global: { headers: { Authorization: auth } } }
  );
  const { data, error } = await userClient.auth.getUser(token);
  if (error || !data?.user) throw new UnauthorizedError();
  const admin = createClient(
    Deno.env.get("SUPABASE_URL") ?? "",
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
    { auth: { autoRefreshToken: false, persistSession: false } }
  );
  return { user: { id: data.user.id, email: data.user.email }, admin };
}
var corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS"
};
function json(body, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" }
  });
}

// supabase/functions/_shared/tradovate/credentialStore.ts
var CredentialStoreError = class extends Error {
  constructor(code, message) {
    super(message ?? code);
    this.code = code;
    this.name = "CredentialStoreError";
  }
};
async function listIntegrations(admin, userId) {
  const { data, error } = await admin.from("integrations").select(
    "id, user_id, environment, tradovate_account_id, tradovate_user_id, account_spec, label, status, last_fill_id, token_expires_at"
  ).eq("user_id", userId).neq("status", "revoked").order("created_at", { ascending: false });
  if (error) throw new CredentialStoreError("integration_list_failed", error.message);
  return data ?? [];
}
async function hasAnyIntegration(admin, userId) {
  const { data } = await admin.from("integrations").select("id").eq("user_id", userId).limit(1);
  return (data ?? []).length > 0;
}
async function hasSkippedWelcome(admin, userId) {
  const { data, error } = await admin.from("tradovate_welcome_state").select("user_id").eq("user_id", userId).maybeSingle();
  if (error) {
    throw new CredentialStoreError("welcome_state_read_failed", error.message);
  }
  return Boolean(data);
}
async function markWelcomeSkipped(admin, userId) {
  const { error } = await admin.from("tradovate_welcome_state").upsert({ user_id: userId, skipped_at: (/* @__PURE__ */ new Date()).toISOString() }, {
    onConflict: "user_id"
  });
  if (error) throw new CredentialStoreError("welcome_skip_failed", error.message);
}

// supabase/functions/_shared/features.ts
function flagEnabled(value) {
  return value !== "false";
}
function isTradovateEnabled(env = defaultEnv()) {
  return flagEnabled(env.TRADOVATE_ENABLED);
}
function defaultEnv() {
  return {
    TRADOVATE_ENABLED: Deno.env.get("TRADOVATE_ENABLED") ?? void 0,
    AI_KYC_ENABLED: Deno.env.get("AI_KYC_ENABLED") ?? void 0,
    WITHDRAWAL_KYC_GATE_ENABLED: Deno.env.get("WITHDRAWAL_KYC_GATE_ENABLED") ?? void 0
  };
}

// supabase/functions/tradovate-status/index.ts
serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  if (req.method !== "GET" && req.method !== "POST") {
    return json({ error: "method_not_allowed" }, 405);
  }
  if (!isTradovateEnabled()) {
    return json({
      enabled: false,
      connected: false,
      integrations: [],
      welcome: { show: false, skipped: false }
    });
  }
  let ctx;
  try {
    ctx = await requireUser(req);
  } catch (e) {
    if (e instanceof UnauthorizedError) return json({ error: "unauthorized" }, 401);
    return json({ error: "unauthorized" }, 401);
  }
  try {
    const integrations = await listIntegrations(ctx.admin, ctx.user.id);
    const connected = integrations.length > 0;
    const everConnected = await hasAnyIntegration(ctx.admin, ctx.user.id);
    let skipped = false;
    let welcomeReadable = true;
    try {
      skipped = await hasSkippedWelcome(ctx.admin, ctx.user.id);
    } catch {
      welcomeReadable = false;
      skipped = true;
    }
    const showWelcome = welcomeReadable && !connected && !everConnected && !skipped;
    if (req.method === "POST") {
      let body = {};
      try {
        body = await req.json();
      } catch {
      }
      if (body.action === "skip") {
        await markWelcomeSkipped(ctx.admin, ctx.user.id);
        return json({
          ok: true,
          enabled: true,
          connected,
          integrations: serialize(integrations),
          welcome: { show: false, skipped: true }
        });
      }
    }
    return json({
      enabled: true,
      connected,
      integrations: serialize(integrations),
      welcome: { show: showWelcome, skipped }
    });
  } catch {
    return json({ error: "status_failed" }, 500);
  }
});
function serialize(integrations) {
  return integrations.map((i) => ({
    id: i.id,
    environment: i.environment,
    accountId: i.tradovate_account_id,
    accountSpec: i.account_spec,
    label: i.label,
    status: i.status,
    lastFillId: i.last_fill_id,
    tokenExpiresAt: i.token_expires_at
  }));
}
