// AUTO-GENERATED by scripts/bundle-edge-functions.mjs — do not edit by hand.
// Paste this whole file as the Edge Function body in the Supabase dashboard.


// supabase/functions/tradovate-disconnect/index.ts
import { serve } from "https://deno.land/std@0.190.0/http/server.ts";

// supabase/functions/_shared/tradovate/auth.ts
import {
  createClient
} from "https://esm.sh/@supabase/supabase-js@2.45.0";
var UnauthorizedError = class extends Error {
  constructor() {
    super("unauthorized");
    this.name = "UnauthorizedError";
  }
};
async function requireUser(req) {
  const auth = req.headers.get("Authorization") ?? "";
  if (!auth.startsWith("Bearer ")) throw new UnauthorizedError();
  const token = auth.slice("Bearer ".length);
  const userClient = createClient(
    Deno.env.get("SUPABASE_URL") ?? "",
    Deno.env.get("SUPABASE_ANON_KEY") ?? "",
    { global: { headers: { Authorization: auth } } }
  );
  const { data, error } = await userClient.auth.getUser(token);
  if (error || !data?.user) throw new UnauthorizedError();
  const admin = createClient(
    Deno.env.get("SUPABASE_URL") ?? "",
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
    { auth: { autoRefreshToken: false, persistSession: false } }
  );
  return { user: { id: data.user.id, email: data.user.email }, admin };
}
var corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS"
};
function json(body, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" }
  });
}

// supabase/functions/_shared/tradovate/credentialStore.ts
var CredentialStoreError = class extends Error {
  constructor(code, message) {
    super(message ?? code);
    this.code = code;
    this.name = "CredentialStoreError";
  }
};
async function disconnectIntegration(admin, userId, integrationId) {
  const { data: owned } = await admin.from("integrations").select("id").eq("id", integrationId).eq("user_id", userId).maybeSingle();
  if (!owned) throw new CredentialStoreError("integration_not_found");
  const { error: delErr } = await admin.from("integration_credentials").delete().eq("integration_id", integrationId);
  if (delErr) throw new CredentialStoreError("credential_delete_failed", delErr.message);
  const { error: updErr } = await admin.from("integrations").update({
    status: "revoked",
    last_error_code: null,
    last_error_message: null,
    token_expires_at: null
  }).eq("id", integrationId).eq("user_id", userId);
  if (updErr) throw new CredentialStoreError("integration_revoke_failed", updErr.message);
}

// supabase/functions/tradovate-disconnect/index.ts
serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  if (req.method !== "POST") return json({ error: "method_not_allowed" }, 405);
  let ctx;
  try {
    ctx = await requireUser(req);
  } catch (e) {
    if (e instanceof UnauthorizedError) return json({ error: "unauthorized" }, 401);
    return json({ error: "unauthorized" }, 401);
  }
  let body;
  try {
    body = await req.json();
  } catch {
    return json({ error: "invalid_json" }, 400);
  }
  const integrationId = typeof body.integrationId === "string" ? body.integrationId : "";
  if (!integrationId) return json({ error: "integration_id_required" }, 400);
  try {
    await disconnectIntegration(ctx.admin, ctx.user.id, integrationId);
    return json({ ok: true, status: "revoked" });
  } catch (e) {
    if (e instanceof CredentialStoreError && e.code === "integration_not_found") {
      return json({ error: "integration_not_found" }, 404);
    }
    return json({ error: "disconnect_failed" }, 500);
  }
});
