import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

export const supportedLanguages = [
  { code: 'en', name: 'English' },
  { code: 'pt', name: 'Português' },
  { code: 'it', name: 'Italiano' },
  { code: 'es', name: 'Español' },
  { code: 'fr', name: 'Français' },
  { code: 'de', name: 'Deutsch' },
  { code: 'ru', name: 'Русский' },
  { code: 'zh', name: '中文' },
  { code: 'ja', name: '日本語' },
  { code: 'ar', name: 'العربية' },
  { code: 'he', name: 'עברית' }
];

const resources = {
  en: {
    translation: {
      nav: { pricing: "INVESTMENT PLANS", howItWorks: "THE INFRASTRUCTURE", about: "OUR LEGACY", contact: "INSTITUTIONAL SUPPORT", login: "TERMINAL ACCESS", openAccount: "CREATE ACCOUNT", dashboard: "DASHBOARD", logout: "SIGN OUT" },
      footer: { desc: "Institutional-grade investment infrastructure. Proprietary technology for the modern market.", platform: "Platform", company: "Company", support: "Digital Support", rights: "All rights reserved.", privacy: "Privacy", terms: "Terms", disclaimer: "Financial Disclaimer" },
      auth: { loginTitle: "Login", loginSubtitle: "Enter your access credentials.", registerTitle: "Create Account", registerSubtitle: "Start your journey in the institutional market.", email: "Email Address", password: "Password", fullName: "Full Name", forgotPassword: "Forgot password?", noAccount: "Don't have an account?", hasAccount: "Already have access?", btnAccess: "ACCESS ACCOUNT", btnCreate: "CREATE MY ACCOUNT", termsAgree: "I agree to the Terms and Privacy.", futureTitle: "The Future of", futureSubtitle: "Investment", features: ["Institutional-grade algorithms", "Advanced capital protection", "Millisecond execution", "Total transparency"] },
      hero: { title1: "ELITE ALGORITHMIC", title2: "CAPITAL MANAGEMENT.", desc: "Deploy institutional-grade quantitative strategies engineered for the modern market. Experience millisecond execution precision and advanced risk mitigation protocols.", getStarted: "EXPLORE INVESTMENT PLANS", viewStrategies: "TECHNICAL METHODOLOGY" },
      stats: { volume: "Total Managed Volume", traders: "Global Active Investors", uptime: "Infrastructure Uptime", latency: "Execution Precision" },
      methodology: { badge: "METHODOLOGY", title: "QUANTITATIVE STRATEGIES", momentum: { title: "MOMENTUM ANALYSIS", desc: "Identification of high-probability trends using proprietary neural networks.", f1: "Trend Detection", f2: "Volume Analysis", f3: "Pattern Recognition" }, volatility: { title: "VOLATILITY ADAPTATION", desc: "Dynamic adjustment of exposure based on real-time market conditions.", f1: "Dynamic Hedging", f2: "Adaptive Stops", f3: "Liquidity Monitoring" }, risk: { title: "RISK MITIGATION", desc: "Multi-layered protection protocols to ensure capital preservation.", f1: "Drawdown Control", f2: "Asset Correlation", f3: "Stress Testing" } },
      process_home: { badge: "PROCESS", title: "INSTITUTIONAL", subtitle: "WORKFLOW", step1: { title: "REGISTRATION", desc: "Secure onboarding and identity verification." }, step2: { title: "ALLOCATION", desc: "Selection of the managed capital tier." }, step3: { title: "INTEGRATION", desc: "Deployment of algorithmic infrastructure." }, step4: { title: "MONITORING", desc: "Real-time performance tracking via terminal." }, step5: { title: "LIQUIDITY", desc: "Seamless profit withdrawal protocols." } },
      cta_home: { badge: "OPPORTUNITY", title: "SCALE YOUR", subtitle: "CAPITAL", desc: "Join the elite group of investors utilizing Braxel's proprietary infrastructure.", btn: "START ALLOCATION", trust: "Institutional Grade Security" },
      pricing: { badge: "TRANSPARENCY", title: "CAPITAL", subtitle: "ALLOCATIONS", desc: "Institutional-grade infrastructure with a transparent fee structure.", select: "SECURE THIS PLAN", allocation: "MANAGED CAPITAL", month: "monthly fee" },
      howItWorks: { badge: "INFRASTRUCTURE", title: "TECHNICAL", subtitle: "ARCHITECTURE", desc: "Our proprietary ecosystem is built for speed, security, and consistent performance.", steps: [{ title: "REGISTRATION", desc: "Create your institutional profile." }, { title: "DASHBOARD", desc: "Access your private management terminal." }, { title: "PLAN SELECTION", desc: "Choose your capital allocation tier." }, { title: "API DEPLOYMENT", desc: "Automated connection to global markets." }, { title: "EXECUTION", desc: "Millisecond algorithmic trade processing." }, { title: "REPORTING", desc: "Detailed weekly performance analytics." }], cta: "READY TO DEPLOY?", ctaBtn: "JOIN THE NETWORK" },
      about: { badge: "LEGACY", title: "INSTITUTIONAL", subtitle: "EXCELLENCE", desc: "Braxel Markets represents the pinnacle of algorithmic capital management.", historyTitle: "OUR HISTORY", historyDesc1: "Founded by a team of quantitative analysts and software engineers, Braxel was built to bridge the gap between retail capital and institutional technology.", historyDesc2: "Today, we manage billions in volume with a focus on risk-adjusted returns and infrastructure stability.", stats: { founded: "Founded", users: "Active Users", uptime: "Uptime", support: "Support" }, values: { mission: "MISSION", missionDesc: "To provide elite algorithmic infrastructure for global capital.", vision: "VISION", visionDesc: "To define the future of automated quantitative management.", values: "VALUES", valuesDesc: "Transparency, precision, and unwavering security." } },
      contact: { badge: "SUPPORT", title: "INSTITUTIONAL", subtitle: "CHANNELS", desc: "Our dedicated support team is available 24/7 for institutional inquiries.", infoTitle: "CONTACT INFO", formTitle: "DIRECT INQUIRY", placeholders: { name: "FULL NAME", email: "EMAIL ADDRESS", subject: "SUBJECT", message: "MESSAGE" }, sendBtn: "SEND INQUIRY" },
      dashboard: { portfolio: "Portfolio", activeServices: "Active Services", newAllocation: "New Allocation", noServices: "No active investment plans found.", balance: "Current Balance", withdraw: "Withdrawal", liquidity: "Liquidity", requestWithdraw: "Request Withdrawal", selectAccount: "Select Account", amount: "Amount (USD)", iban: "IBAN / Bank Details", btnWithdraw: "SUBMIT WITHDRAWAL REQUEST", profile: "Profile Management", settings: "Settings", firstName: "First Name", lastName: "Last Name", saveChanges: "SAVE CHANGES" },
      checkout: { summary: "SUMMARY", finalize: "FINALIZE ALLOCATION", managedCapital: "Managed Capital", total: "TOTAL", securityDesc: "Your transaction is protected by AES-256 encryption and institutional security protocols.", secure: "SECURE CHECKOUT", authRequired: "AUTHENTICATION REQUIRED", authDesc: "Please login or create an account to proceed with the allocation.", btnLogin: "LOGIN TO PROCEED", btnRegister: "CREATE ACCOUNT", loggedInAs: "LOGGED IN AS", footerNote: "By proceeding, you agree to our Terms of Service and Risk Disclosure." },
      legal: { badgeLegal: "LEGAL", termsTitle: "TERMS OF SERVICE" }
    }
  },
  pt: {
    translation: {
      nav: { pricing: "PLANOS DE INVESTIMENTO", howItWorks: "INFRAESTRUTURA", about: "NOSSO LEGADO", contact: "SUPORTE INSTITUCIONAL", login: "ACESSO AO TERMINAL", openAccount: "CRIAR CONTA", dashboard: "PAINEL", logout: "SAIR" },
      footer: { desc: "Infraestrutura de investimento de nível institucional. Tecnologia proprietária para o mercado moderno.", platform: "Plataforma", company: "Empresa", support: "Suporte Digital", rights: "Todos os direitos reservados.", privacy: "Privacidade", terms: "Termos", disclaimer: "Aviso Legal" },
      auth: { loginTitle: "Login", loginSubtitle: "Insira suas credenciais de acesso.", registerTitle: "Criar Conta", registerSubtitle: "Comece sua jornada no mercado institucional.", email: "Endereço de E-mail", password: "Senha", fullName: "Nome Completo", forgotPassword: "Esqueceu a senha?", noAccount: "Não tem uma conta?", hasAccount: "Já possui acesso?", btnAccess: "ACESSAR CONTA", btnCreate: "CRIAR MINHA CONTA", termsAgree: "Eu concordo com os Termos e Privacidade.", futureTitle: "O Futuro do", futureSubtitle: "Investimento", features: ["Algoritmos institucionais", "Proteção de capital avançada", "Execução em milissegundos", "Transparença total"] },
      hero: { title1: "GESTÃO DE CAPITAL", title2: "ALGORÍTMICA DE ELITE.", desc: "Implemente estratégias quantitativas de nível institucional projetadas para o mercado moderno. Experimente precisão de execução em milissegundos.", getStarted: "EXPLORAR PLANOS DE INVESTIMENTO", viewStrategies: "METODOLOGIA TÉCNICA" },
      stats: { volume: "Volume Total Gerenciado", traders: "Investidores Ativos", uptime: "Uptime da Infraestrutura", latency: "Precisão de Execução" },
      methodology: { badge: "METODOLOGIA", title: "ESTRATÉGIAS QUANTITATIVAS", momentum: { title: "ANÁLISIS DE MOMENTUM", desc: "Identificação de tendências de alta probabilidade usando redes neurais proprietárias.", f1: "Detecção de Tendência", f2: "Análise de Volume", f3: "Reconhecimento de Padrões" }, volatility: { title: "ADAPTAÇÃO DE VOLATILIDADE", desc: "Ajuste dinâmico de exposição baseado em condições de mercado em tempo real.", f1: "Hedging Dinâmico", f2: "Stops Adaptativos", f3: "Monitoramento de Liquidez" }, risk: { title: "MITIGAÇÃO DE RISCO", desc: "Protocolos de proteção em múltiplas camadas para garantir a preservação do capital.", f1: "Controle de Drawdown", f2: "Correlação de Ativos", f3: "Testes de Estresse" } },
      process_home: { badge: "PROCESSO", title: "FLUXO", subtitle: "INSTITUCIONAL", step1: { title: "REGISTRO", desc: "Onboarding seguro e verificação de identidade." }, step2: { title: "ALOCAÇÃO", desc: "Seleção do nível de capital gerenciado." }, step3: { title: "INTEGRAÇÃO", desc: "Implementação da infraestrutura algorítmica." }, step4: { title: "MONITORAMENTO", desc: "Acompanhamento em tempo real via terminal." }, step5: { title: "LIQUIDEZ", desc: "Protocolos de saque de lucros simplificados." } },
      cta_home: { badge: "OPPORTUNIDADE", title: "ESCALE SEU", subtitle: "CAPITAL", desc: "Junte-se ao grupo de elite de investidores que utilizam a infraestrutura proprietária da Braxel.", btn: "INICIAR ALOCAÇÃO", trust: "Segurança de Nível Institucional" },
      pricing: { badge: "TRANSPARENCIA", title: "ALOCAÇÕES DE", subtitle: "CAPITAL", desc: "Infraestrutura de nível institucional com uma estrutura de taxas transparente.", select: "GARANTIR ESTE PLANO", allocation: "CAPITAL GERENCIADO", month: "taxa mensal" },
      howItWorks: { badge: "INFRAESTRUTURA", title: "ARQUITETURA", subtitle: "TÉCNICA", desc: "Nosso ecossistema proprietário é construído para velocidade, segurança e desempenho consistente.", steps: [{ title: "REGISTRO", desc: "Crie seu perfil institucional." }, { title: "PAINEL", desc: "Acesse seu terminal privado de gestão." }, { title: "SELEÇÃO DE PLANO", desc: "Escolha seu nível de alocação de capital." }, { title: "IMPLEMENTAÇÃO API", desc: "Conexão automatizada aos mercados globais." }, { title: "EXECUÇÃO", desc: "Processamento de ordens em milissegundos." }, { title: "RELATÓRIOS", desc: "Análise detalhada de desempenho semanal." }], cta: "PRONTO PARA COMEÇAR?", ctaBtn: "ENTRAR NA REDE" },
      about: { badge: "LEGADO", title: "EXCELÊNCIA", subtitle: "INSTITUTIONAL", desc: "A Braxel Markets representa o ápice da gestão algorítmica de capital.", historyTitle: "NOSSA HISTÓRIA", historyDesc1: "Fundada por uma equipe de analistas quantitativos e engenheiros de software, a Braxel foi criada para unir o capital individual à tecnologia institucional.", historyDesc2: "Hoje, gerenciamos bilhões em volume com foco em retornos ajustados ao risco e estabilidade de infraestrutura.", stats: { founded: "Fundada", users: "Usuários Ativos", uptime: "Uptime", support: "Suporte" }, values: { mission: "MISSÃO", missionDesc: "Fornecer infraestrutura algorítmica de elite para o capital global.", vision: "VISÃO", visionDesc: "Definir o futuro da gestão quantitativa automatizada.", values: "VALORES", valuesDesc: "Transparença, precisão e segurança inabalável." } },
      contact: { badge: "SUPORTE", title: "CANAIS", subtitle: "INSTITUCIONAIS", desc: "Nossa equipe de suporte dedicada está disponível 24/7 para consultas institucionais.", infoTitle: "CONTATO", formTitle: "CONSULTA DIRETA", placeholders: { name: "NOME COMPLETO", email: "ENDEREÇO DE E-MAIL", subject: "ASSUNTO", message: "MENSAGEM" }, sendBtn: "ENVIAR CONSULTA" },
      dashboard: { portfolio: "Portfólio", activeServices: "Serviços Ativos", newAllocation: "Nova Alocação", noServices: "Nenhum plano de investimento ativo encontrado.", balance: "Saldo Atual", withdraw: "Saque", liquidity: "Liquidez", requestWithdraw: "Solicitar Saque", selectAccount: "Selecionar Conta", amount: "Valor (USD)", iban: "IBAN / Dados Bancários", btnWithdraw: "ENVIAR SOLICITAÇÃO DE SAQUE", profile: "Gestão de Perfil", settings: "Configurações", firstName: "Nome", lastName: "Sobrenome", saveChanges: "SALVAR ALTERAÇÕES" },
      checkout: { summary: "RESUMO", finalize: "FINALIZAR ALOCAÇÃO", managedCapital: "Capital Gerenciado", total: "TOTAL", securityDesc: "Sua transação é protegida por criptografia AES-256 e protocolos de segurança institucional.", secure: "CHECKOUT SEGURO", authRequired: "AUTENTICAÇÃO NECESSÁRIA", authDesc: "Por favor, faça login ou crie uma conta para prosseguir com a alocação.", btnLogin: "LOGIN PARA PROSSEGUIR", btnRegister: "CRIAR CONTA", loggedInAs: "LOGADO COMO", footerNote: "Ao prosseguir, você concorda com nossos Termos de Serviço e Divulgação de Risco." },
      legal: { badgeLegal: "LEGAL", termsTitle: "TERMOS DE SERVIÇO" }
    }
  },
  it: {
    translation: {
      nav: { pricing: "PIANI DI INVESTIMENTO", howItWorks: "INFRASTRUTTURA", about: "LA NOSTRA EREDITÀ", contact: "SUPPORTO ISTITUZIONALE", login: "ACCESSO TERMINALE", openAccount: "CREA ACCOUNT", dashboard: "DASHBOARD", logout: "DISCONNETTI" },
      footer: { desc: "Infrastruttura di investimento di livello istituzionale. Tecnologia proprietaria per il mercato moderno.", platform: "Piattaforma", company: "Azienda", support: "Supporto Digitale", rights: "Tutti i diritti riservati.", privacy: "Privacy", terms: "Termini", disclaimer: "Dichiarazione di non responsabilità" },
      auth: { loginTitle: "Accesso", loginSubtitle: "Inserisci le tue credenziali di accesso.", registerTitle: "Crea Account", registerSubtitle: "Inizia il tuo viaggio nel mercato istituzionale.", email: "Indirizzo Email", password: "Password", fullName: "Nome Completo", forgotPassword: "Password dimenticata?", noAccount: "Non hai un account?", hasAccount: "Hai già l'accesso?", btnAccess: "ACCEDI ALL'ACCOUNT", btnCreate: "CREA IL MIO ACCOUNT", termsAgree: "Accetto i Termini e la Privacy.", futureTitle: "Il Futuro dell'", futureSubtitle: "Investimento", features: ["Algoritmi istituzionali", "Protezione avanzata del capitale", "Esecuzione in millisecondi", "Trasparenza totale"] },
      hero: { title1: "GESTIONE CAPITALE", title2: "ALGORITMICA D'ELITE.", desc: "Implementa strategie quantitative di livello istituzionale progettate per il mercato moderno. Sperimenta la precisione di esecuzione in millisecondi.", getStarted: "ESPLORA I PIANI DI INVESTIMENTO", viewStrategies: "METODOLOGIA TECNICA" },
      stats: { volume: "Volume Totale Gestito", traders: "Investitori Attivi", uptime: "Uptime Infrastruttura", latency: "Precisione Esecuzione" },
      methodology: { badge: "METODOLOGIA", title: "STRATEGIE QUANTITATIVE", momentum: { title: "ANALISI MOMENTUM", desc: "Identificazione di tendenze ad alta probabilità utilizzando reti neurali proprietarie.", f1: "Rilevamento Trend", f2: "Analisi Volume", f3: "Riconoscimento Pattern" }, volatility: { title: "ADATTAMENTO VOLATILITÀ", desc: "Regolazione dinamica dell'esposizione basata sulle condizioni di mercato in tempo reale.", f1: "Hedging Dinamico", f2: "Stop Adattivi", f3: "Monitoraggio Liquidità" }, risk: { title: "MITIGAZIONE RISCHIO", desc: "Protocollo di protezione a più livelli per garantire la conservazione del capitale.", f1: "Controllo Drawdown", f2: "Correlazione Asset", f3: "Stress Test" } },
      process_home: { badge: "PROCESSO", title: "WORKFLOW", subtitle: "ISTITUZIONALE", step1: { title: "REGISTRAZIONE", desc: "Onboarding sicuro e verifica dell'identità." }, step2: { title: "ALLOCAZIONE", desc: "Selezione del livello di capitale gestito." }, step3: { title: "INTEGRAZIONE", desc: "Implementazione dell'infrastruttura algoritmica." }, step4: { title: "MONITORAGGIO", desc: "Monitoraggio delle prestazioni in tempo reale via terminale." }, step5: { title: "LIQUIDITÀ", desc: "Protocolli di prelievo profitti semplificati." } },
      cta_home: { badge: "OPPORTUNITÀ", title: "SCALA IL TUO", subtitle: "CAPITALE", desc: "Unisciti al gruppo d'élite di investitori che utilizzano l'infrastruttura proprietaria di Braxel.", btn: "INIZIA ALLOCAZIONE", trust: "Sicurezza di Livello Istituzionale" },
      pricing: { badge: "TRASPARENZA", title: "ALLOCAZIONI DI", subtitle: "CAPITALE", desc: "Infrastruttura istituzionale con una struttura commissionale trasparente.", select: "ASSICURA QUESTO PIANO", allocation: "CAPITALE GESTITO", month: "canone mensile" },
      howItWorks: { badge: "INFRASTRUTTURA", title: "ARCHITETTURA", subtitle: "TECNICA", desc: "Il nostro ecosistema proprietario è costruito per velocità, sicurezza e prestazioni costanti.", steps: [{ title: "REGISTRAZIONE", desc: "Crea il tuo profilo istituzionale." }, { title: "DASHBOARD", desc: "Accedi al tuo terminale di gestione privato." }, { title: "SELEZIONE PIANO", desc: "Scegli il tuo livello di allocazione del capitale." }, { title: "DISTRIBUZIONE API", desc: "Connessione automatizzata ai mercati globali." }, { title: "ESECUZIONE", desc: "Elaborazione ordini in millisecondi." }, { title: "REPORTING", desc: "Analisi dettagliata delle prestazioni settimanali." }], cta: "PRONTO A PARTIRE?", ctaBtn: "ENTRA NELLA RETE" },
      about: { badge: "EREDITÀ", title: "ECCELLENZA", subtitle: "ISTITUZIONALE", desc: "Braxel Markets rappresenta l'apice della gestione algoritmica del capitale.", historyTitle: "LA NOSTRA STORIA", historyDesc1: "Fondata da un team di analisti quantitativi e ingegneri del software, Braxel è stata creata per colmare il divario tra capitale retail e tecnologia istituzionale.", historyDesc2: "Oggi gestiamo miliardi di volume con un focus sui rendimenti corretti per il rischio e sulla stabilità dell'infrastruttura.", stats: { founded: "Fondata", users: "Utenti Attivi", uptime: "Uptime", support: "Supporto" }, values: { mission: "MISSIONE", missionDesc: "Fornire infrastrutture algoritmiche d'élite per il capitale globale.", vision: "VISIONE", visionDesc: "Definire il futuro della gestione quantitativa automatizzata.", values: "VALORI", valuesDesc: "Trasparenza, precisione e sicurezza incrollabile." } },
      contact: { badge: "SUPPORTO", title: "CANALI", subtitle: "ISTITUZIONALI", desc: "Il nostro team di supporto dedicato è disponibile 24/7 per richieste istituzionali.", infoTitle: "CONTATTI", formTitle: "RICHIESTA DIRETTA", placeholders: { name: "NOME COMPLETO", email: "INDIRIZZO EMAIL", subject: "OGGETTO", message: "MESSAGGIO" }, sendBtn: "INVIA RICHIESTA" },
      dashboard: { portfolio: "Portafoglio", activeServices: "Servizi Attivi", newAllocation: "Nuova Allocazione", noServices: "Nessun piano di investimento attivo trovato.", balance: "Saldo Attuale", withdraw: "Prelievo", liquidity: "Liquidità", requestWithdraw: "Richiedi Prelievo", selectAccount: "Seleziona Account", amount: "Importo (USD)", iban: "IBAN / Dati Bancari", btnWithdraw: "INVIA RICHIESTA DI PRELIEVO", profile: "Gestione Profilo", settings: "Impostazioni", firstName: "Nome", lastName: "Cognome", saveChanges: "SALVA MODIFICHE" },
      checkout: { summary: "RIEPILOGO", finalize: "FINALIZZA ALLOCAZIONE", managedCapital: "Capitale Gestito", total: "TOTALE", securityDesc: "La tua transazione è protetta da crittografia AES-256 e protocolli di sicurezza istituzionali.", secure: "CHECKOUT SICURO", authRequired: "AUTENTICAZIONE RICHIESTA", authDesc: "Accedi o crea un account per procedere con l'allocazione.", btnLogin: "ACCEDI PER PROCEDERE", btnRegister: "CREA ACCOUNT", loggedInAs: "ACCESSO COME", footerNote: "Procedendo, accetti i nostri Termini di Servizio e l'Informativa sui Rischi." },
      legal: { badgeLegal: "LEGALE", termsTitle: "TERMINI DI SERVIZIO" }
    }
  },
  es: {
    translation: {
      nav: { pricing: "PLANES DE INVERSIÓN", howItWorks: "INFRAESTRUCTURA", about: "NUESTRO LEGADO", contact: "SOPORTE INSTITUCIONAL", login: "ACCESO AL TERMINAL", openAccount: "CREAR CUENTA", dashboard: "PANEL", logout: "CERRAR SESIÓN" },
      footer: { desc: "Infraestructura de inversión de nivel institucional. Tecnología propia para el mercado moderno.", platform: "Plataforma", company: "Empresa", support: "Soporte Digital", rights: "Todos los derechos reservados.", privacy: "Privacidad", terms: "Términos", disclaimer: "Aviso Legal" },
      auth: { loginTitle: "Iniciar Sesión", loginSubtitle: "Ingrese sus credenciales de acceso.", registerTitle: "Crear Cuenta", registerSubtitle: "Comience su viaje no mercado institucional.", email: "Correo Electrónico", password: "Contraseña", fullName: "Nombre Completo", forgotPassword: "¿Olvidó su contraseña?", noAccount: "¿No tiene una cuenta?", hasAccount: "¿Ya tiene acceso?", btnAccess: "ACCEDER A LA CUENTA", btnCreate: "CREAR MI CUENTA", termsAgree: "Acepto los Términos e la Privacidad.", futureTitle: "El Futuro de la", futureSubtitle: "Inversión", features: ["Algoritmos institucionales", "Protección de capital avanzada", "Ejecución en milisegundos", "Transparencia total"] },
      hero: { title1: "GESTIÓN DE CAPITAL", title2: "ALGORÍTMICA DE ÉLITE.", desc: "Implemente estrategias cuantitativas de nivel institucional diseñadas para el mercado moderno. Experimente precisión de ejecución en milisegundos.", getStarted: "EXPLORAR PLANES DE INVERSIÓN", viewStrategies: "METODOLOGÍA TÉCNICA" },
      stats: { volume: "Volumen Total Gestionado", traders: "Inversores Activos", uptime: "Uptime de Infraestructura", latency: "Precisión de Ejecución" },
      methodology: { badge: "METODOLOGÍA", title: "ESTRATEGIAS CUANTITATIVAS", momentum: { title: "ANÁLISIS DE MOMENTUM", desc: "Identificación de tendencias de alta probabilidad utilizando redes neuronales propias.", f1: "Detección de Tendencia", f2: "Análisis de Volumen", f3: "Reconocimiento de Patrones" }, volatility: { title: "ADAPTACIÓN DE VOLATILIDAD", desc: "Ajuste dinámico de exposición basado en condiciones de mercado en tiempo real.", f1: "Cobertura Dinámica", f2: "Stops Adaptativos", f3: "Monitoreo de Liquidez" }, risk: { title: "MITIGACIÓN DE RIESGO", desc: "Protocolos de protección en múltiples capas para garantizar la preservación del capital.", f1: "Control de Drawdown", f2: "Correlación de Activos", f3: "Pruebas de Estrés" } },
      process_home: { badge: "PROCESO", title: "FLUJO", subtitle: "INSTITUCIONAL", step1: { title: "REGISTRO", desc: "Onboarding seguro e verificación de identidad." }, step2: { title: "ASIGNACIÓN", desc: "Selección del nivel de capital gestionado." }, step3: { title: "INTEGRACIÓN", desc: "Implementación de la infraestructura algorítmica." }, step4: { title: "MONITOREO", desc: "Seguimiento en tiempo real vía terminal." }, step5: { title: "LIQUIDEZ", desc: "Protocolos de retiro de beneficios simplificados." } },
      cta_home: { badge: "OPORTUNIDAD", title: "ESCALE SU", subtitle: "CAPITAL", desc: "Únase al grupo de élite de inversores que utilizan la infraestructura propia de Braxel.", btn: "INICIAR ASIGNACIÓN", trust: "Seguridad de Nivel Institucional" },
      pricing: { badge: "TRANSPARENCIA", title: "ASIGNACIONES DE", subtitle: "CAPITAL", desc: "Infraestructura institucional con una estructura de tarifas transparente.", select: "ASEGURAR ESTE PLAN", allocation: "CAPITAL GESTIONADO", month: "tarifa mensual" },
      howItWorks: { badge: "INFRAESTRUCTURA", title: "ARQUITECTURA", subtitle: "TÉCNICA", desc: "Nuestro ecosistema propio está construido para velocidad, seguridad y rendimiento constante.", steps: [{ title: "REGISTRO", desc: "Cree su perfil institucional." }, { title: "PANEL", desc: "Acceda a su terminal privado de gestión." }, { title: "SELECCIÓN DE PLAN", desc: "Elija su nivel de asignación de capital." }, { title: "DESPLIEGUE API", desc: "Conexión automatizada a los mercados globales." }, { title: "EJECUCIÓN", desc: "Procesamiento de órdenes en milisegundos." }, { title: "INFORMES", desc: "Análisis detallado de rendimiento semanal." }], cta: "¿LISTO PARA EMPEZAR?", ctaBtn: "ENTRAR EN LA RED" },
      about: { badge: "LEGADO", title: "EXCELENCIA", subtitle: "INSTITUCIONAL", desc: "Braxel Markets representa la cúspide de la gestión algorítmica de capital.", historyTitle: "NUESTRA HISTORIA", historyDesc1: "Fundada por un equipo de analistas cuantitativos e ingenieros de software, Braxel fue creada para unir el capital individual a la tecnología institucional.", historyDesc2: "Hoy, gestionamos miles de millones en volumen con un enfoque en retornos ajustados al riesgo y estabilidad de infraestructura.", stats: { founded: "Fundada", users: "Usuarios Activos", uptime: "Uptime", support: "Soporte" }, values: { mission: "MISIÓN", missionDesc: "Proporcionar infraestructura algorítmica de élite para el capital global.", vision: "VISIÓN", visionDesc: "Definir el futuro de la gestión cuantitativa automatizada.", values: "VALORES", valuesDesc: "Transparencia, precisión y seguridad inquebrantable." } },
      contact: { badge: "SOPORTE", title: "CANALES", subtitle: "INSTITUCIONALES", desc: "Nuestro equipo de soporte dedicado está disponible 24/7 para consultas institucionales.", infoTitle: "CONTACTO", formTitle: "CONSULTA DIRECTA", placeholders: { name: "NOMBRE COMPLETO", email: "CORREO ELECTRÓNICO", subject: "ASUNTO", message: "MENSAJE" }, sendBtn: "ENVIAR CONSULTA" },
      dashboard: { portfolio: "Portafolio", activeServices: "Servicios Activos", newAllocation: "Nueva Asignación", noServices: "No se encontraron planes de inversión activos.", balance: "Saldo Actual", withdraw: "Retiro", liquidity: "Liquidez", requestWithdraw: "Solicitar Retiro", selectAccount: "Seleccionar Cuenta", amount: "Monto (USD)", iban: "IBAN / Datos Bancarios", btnWithdraw: "ENVIAR SOLICITUD DE RETIRO", profile: "Gestión de Perfil", settings: "Configuración", firstName: "Nombre", lastName: "Apellido", saveChanges: "GUARDAR CAMBIOS" },
      checkout: { summary: "RESUMEN", finalize: "FINALIZAR ASIGNACIÓN", managedCapital: "Capital Gestionado", total: "TOTAL", securityDesc: "Su transacción está protegida por cifrado AES-256 y protocolos de seguridad institucional.", secure: "CHECKOUT SEGURO", authRequired: "AUTENTICACIÓN NECESARIA", authDesc: "Por favor, inicie sesión o cree una cuenta para continuar con la asignación.", btnLogin: "LOGIN PARA CONTINUAR", btnRegister: "CREAR CUENTA", loggedInAs: "CONECTADO COMO", footerNote: "Al continuar, acepta nuestros Términos de Servicio y Divulgación de Riesgos." },
      legal: { badgeLegal: "LEGAL", termsTitle: "TÉRMINOS DE SERVICIO" }
    }
  },
  fr: {
    translation: {
      nav: { pricing: "PLANS D'INVESTISSEMENT", howItWorks: "L'INFRASTRUCTURE", about: "NOTRE HÉRITAGE", contact: "SUPPORT INSTITUTIONNEL", login: "ACCÈS TERMINAL", openAccount: "CRÉER UN COMPTE", dashboard: "TABLEAU DE BORD", logout: "DÉCONNEXION" },
      footer: { desc: "Infrastructure d'investissement de classe institutionnelle. Technologie propriétaire pour le marché moderne.", platform: "Plateforme", company: "Entreprise", support: "Support Digital", rights: "Tous droits réservés.", privacy: "Confidentialité", terms: "Conditions", disclaimer: "Avis de non-responsabilité" },
      auth: { loginTitle: "Connexion", loginSubtitle: "Entrez vos identifiants d'accès.", registerTitle: "Créer un compte", registerSubtitle: "Commencez votre voyage sur le marché institutionnel.", email: "Adresse E-mail", password: "Mot de passe", fullName: "Nom complet", forgotPassword: "Mot de passe oublié ?", noAccount: "Pas de compte ?", hasAccount: "Déjà un accès ?", btnAccess: "ACCÉDER AU COMPTE", btnCreate: "CRÉER MON COMPTE", termsAgree: "J'accepte les conditions et la confidentialité.", futureTitle: "L'avenir de", futureSubtitle: "l'investissement", features: ["Algorithmes institutionnels", "Protection avancée du capital", "Exécution en millisecondes", "Transparence totale"] },
      hero: { title1: "GESTION DE CAPITAL", title2: "ALGORITHMIQUE D'ÉLITE.", desc: "Déployez des stratégies quantitatives de classe institutionnelle conçues pour le marché moderne. Découvrez la précision d'exécution en millisecondes.", getStarted: "EXPLORER LES PLANS", viewStrategies: "MÉTHODOLOGIE TECHNIQUE" },
      stats: { volume: "Volume total géré", traders: "Investisseurs actifs", uptime: "Disponibilité infrastructure", latency: "Précision d'exécution" },
      methodology: { badge: "MÉTHODOLOGIE", title: "STRATÉGIES QUANTITATIVES", momentum: { title: "ANALYSE DE MOMENTUM", desc: "Identification de tendances à haute probabilité via des réseaux neuronaux propriétaires.", f1: "Détection de Tendance", f2: "Analyse de Volume", f3: "Reconnaissance de Formes" }, volatility: { title: "ADAPTATION VOLATILITÉ", desc: "Ajustement dynamique de l'exposition basé sur les conditions de marché en temps réel.", f1: "Hedging Dynamique", f2: "Stops Adaptatifs", f3: "Suivi de Liquidité" }, risk: { title: "ATTÉNUATION DES RISQUES", desc: "Protocoles de protection multicouches pour garantir la préservation du capital.", f1: "Contrôle du Drawdown", f2: "Corrélation d'Actifs", f3: "Tests de Résistance" } },
      process_home: { badge: "PROCESSUS", title: "FLUX", subtitle: "INSTITUTIONNEL", step1: { title: "INSCRIPTION", desc: "Onboarding sécurisé et vérification d'identité." }, step2: { title: "ALLOCATION", desc: "Sélection du niveau de capital géré." }, step3: { title: "INTÉGRATION", desc: "Déploiement de l'infrastructure algorithmique." }, step4: { title: "SURVEILLANCE", desc: "Suivi des performances en temps réel via terminal." }, step5: { title: "LIQUIDITÉ", desc: "Protocoles de retrait de profits simplifiés." } },
      cta_home: { badge: "OPPORTUNITÉ", title: "DÉVELOPPEZ VOTRE", subtitle: "CAPITAL", desc: "Rejoignez le groupe d'élite d'investisseurs utilisant l'infrastructure propriétaire de Braxel.", btn: "LANCER L'ALLOCATION", trust: "Sécurité de Classe Institutionnelle" },
      pricing: { badge: "TRANSPARENCE", title: "ALLOCATIONS DE", subtitle: "CAPITAL", desc: "Infrastructure institutionnelle avec une structure de frais transparente.", select: "SÉCURISER CE PLAN", allocation: "CAPITAL GÉRÉ", month: "frais mensuels" },
      howItWorks: { badge: "INFRASTRUCTURE", title: "ARCHITECTURE", subtitle: "TECHNIQUE", desc: "Notre écosystème propriétaire est conçu pour la vitesse, la sécurité et la performance constante.", steps: [{ title: "INSCRIPTION", desc: "Créez votre profil institutionnel." }, { title: "TABLEAU DE BORD", desc: "Accédez à votre terminal de gestion privé." }, { title: "SÉLECTION DU PLAN", desc: "Choisissez votre niveau d'allocation de capital." }, { title: "DÉPLOIEMENT API", desc: "Connexion automatisée aux marchés mondiaux." }, { title: "EXÉCUTION", desc: "Traitement des ordres en millisecondes." }, { title: "RAPPORTS", desc: "Analyse détaillée des performances hebdomadaires." }], cta: "PRÊT À DÉPLOYER ?", ctaBtn: "REJOINDRE LE RÉSEAU" },
      about: { badge: "HÉRITAGE", title: "EXCELLENCE", subtitle: "INSTITUTIONNELLE", desc: "Braxel Markets représente le summum de la gestion algorithmique de capital.", historyTitle: "NOTRE HISTOIRE", historyDesc1: "Fondée par une équipe d'analystes quantitatifs et d'ingénieurs logiciels, Braxel a été créée pour combler le fossé entre capital individuel et technologie institutionnelle.", historyDesc2: "Aujourd'hui, nous gérons des milliards en volume avec un focus sur les rendements ajustés au risque et la stabilité de l'infrastructure.", stats: { founded: "Fondée", users: "Utilisateurs Actifs", uptime: "Uptime", support: "Support" }, values: { mission: "MISSION", missionDesc: "Fournir une infrastructure algorithmique d'élite pour le capital mondial.", vision: "VISION", visionDesc: "Définir l'avenir de la gestion quantitative automatisée.", values: "VALEURS", valuesDesc: "Transparence, précision et sécurité inébranlable." } },
      contact: { badge: "SUPPORT", title: "CANAUX", subtitle: "INSTITUTIONNELS", desc: "Notre équipe de support dédiée est disponible 24/7 pour les demandes institutionnelles.", infoTitle: "CONTACT", formTitle: "DEMANDE DIRECTE", placeholders: { name: "NOM COMPLET", email: "ADRESSE E-MAIL", subject: "SUJET", message: "MESSAGE" }, sendBtn: "ENVOYER LA DEMANDE" },
      dashboard: { portfolio: "Portefeuille", activeServices: "Services actifs", newAllocation: "Nouvelle allocation", noServices: "Aucun plan d'investissement actif trouvé.", balance: "Solde actuel", withdraw: "Retrait", liquidity: "Liquidité", requestWithdraw: "Demander un retrait", selectAccount: "Choisir un compte", amount: "Montant (USD)", iban: "IBAN / Coordonnées bancaires", btnWithdraw: "ENVOYER LA DEMANDE", profile: "Gestion du profil", settings: "Paramètres", firstName: "Prénom", lastName: "Nom", saveChanges: "ENREGISTRER" },
      checkout: { summary: "RÉSUMÉ", finalize: "FINALISER L'ALLOCATION", managedCapital: "Capital Géré", total: "TOTAL", securityDesc: "Votre transaction est protégée par un cryptage AES-256 et des protocoles de sécurité institutionnels.", secure: "PAIEMENT SÉCURISÉ", authRequired: "AUTHENTIFICATION REQUISE", authDesc: "Veuillez vous connecter ou créer un compte pour procéder à l'allocation.", btnLogin: "CONNEXION POUR CONTINUER", btnRegister: "CRÉER UN COMPTE", loggedInAs: "CONNECTÉ EN TANT QUE", footerNote: "En continuant, vous acceptez nos Conditions de Service et notre Divulgation des Risques." },
      legal: { badgeLegal: "LÉGAL", termsTitle: "TERMS OF SERVICE" }
    }
  },
  de: {
    translation: {
      nav: { pricing: "INVESTITIONSPLÄNE", howItWorks: "INFRASTRUKTUR", about: "UNSER ERBE", contact: "INSTITUTIONELLER SUPPORT", login: "TERMINAL-ZUGANG", openAccount: "KONTO ERSTELLEN", dashboard: "DASHBOARD", logout: "ABMELDEN" },
      footer: { desc: "Institutionelle Investment-Infrastruktur. Proprietäre Technologie für den modernen Markt.", platform: "Plattform", company: "Unternehmen", support: "Digitaler Support", rights: "Alle Rechte vorbehalten.", privacy: "Datenschutz", terms: "Bedingungen", disclaimer: "Haftungsausschluss" },
      auth: { loginTitle: "Anmelden", loginSubtitle: "Geben Sie Ihre Zugangsdaten ein.", registerTitle: "Konto erstellen", registerSubtitle: "Beginnen Sie Ihre Reise am institutionellen Markt.", email: "E-Mail-Adresse", password: "Passwort", fullName: "Vollständiger Name", forgotPassword: "Passwort vergessen?", noAccount: "Kein Konto?", hasAccount: "Bereits Zugang?", btnAccess: "ZUGANG ZUM KONTO", btnCreate: "MEIN KONTO ERSTELLEN", termsAgree: "Ich stimme den Bedingungen und dem Datenschutz zu.", futureTitle: "Die Zukunft der", futureSubtitle: "Investition", features: ["Institutionelle Algorithmen", "Erweiterter Kapitalschutz", "Millisekunden-Ausführung", "Volle Transparenz"] },
      hero: { title1: "ELITE ALGORITHMISCHES", title2: "KAPITALMANAGEMENT.", desc: "Nutzen Sie institutionelle quantitative Strategien für den modernen Markt. Erleben Sie Millisekunden-Präzision und fortsrittliche Risikominderung.", getStarted: "INVESTITIONSPLÄNE ERKUNDEN", viewStrategies: "TECHNISCHE METHODIK" },
      stats: { volume: "Verwaltetes Gesamtvolumen", traders: "Aktive Investoren", uptime: "Infrastruktur-Uptime", latency: "Ausführungspräzision" },
      methodology: { badge: "METHODIK", title: "QUANTITATIVE STRATEGIEN", momentum: { title: "MOMENTUM-ANALYSE", desc: "Identifizierung von Trends mit hoher Wahrscheinlichkeit durch neuronale Netze.", f1: "Trend-Erkennung", f2: "Volumen-Analyse", f3: "Muster-Erkennung" }, volatility: { title: "VOLATILITÄTS-ADAPTION", desc: "Dynamische Anpassung der Exposition basierend auf Echtzeit-Marktbedingungen.", f1: "Dynamisches Hedging", f2: "Adaptive Stops", f3: "Liquiditäts-Monitoring" }, risk: { title: "RISIKOMINDERUNG", desc: "Mehrschichtige Schutzprotokolle zur Gewährleistung des Kapitalerhalts.", f1: "Drawdown-Kontrolle", f2: "Asset-Korrelation", f3: "Stresstests" } },
      process_home: { badge: "PROZESS", title: "INSTITUTIONELLER", subtitle: "WORKFLOW", step1: { title: "REGISTRIERUNG", desc: "Sicheres Onboarding und Identitätsprüfung." }, step2: { title: "ALLOKATION", desc: "Auswahl der verwalteten Kapitalstufe." }, step3: { title: "INTEGRATION", desc: "Bereitstellung der algorithmischen Infrastruktur." }, step4: { title: "MONITORING", desc: "Echtzeit-Leistungsverfolgung via Terminal." }, step5: { title: "LIQUIDITÄT", desc: "Nahtlose Protokolle zur Gewinnabhebung." } },
      cta_home: { badge: "CHANCE", title: "SKALIEREN SIE IHR", subtitle: "KAPITAL", desc: "Treten Sie der Elitegruppe von Investoren bei, die die Infrastruktur von Braxel nutzen.", btn: "ALLOKATION STARTEN", trust: "Sicherheit auf institutionellem Niveau" },
      pricing: { badge: "TRANSPARENZ", title: "KAPITAL", subtitle: "ALLOKATIONEN", desc: "Institutionelle Infrastruktur mit transparenter Gebührenstruktur.", select: "DIESEN PLAN SICHERN", allocation: "VERWALTETES KAPITAL", month: "monatliche Gebühr" },
      howItWorks: { badge: "INFRASTRUKTUR", title: "TECHNISCHE", subtitle: "ARCHITEKTUR", desc: "Unser proprietäres Ökosystem ist auf Geschwindigkeit, Sicherheit und konstante Leistung ausgelegt.", steps: [{ title: "REGISTRIERUNG", desc: "Erstellen Sie Ihr institutionelles Profil." }, { title: "DASHBOARD", desc: "Greifen Sie auf Ihr privates Management-Terminal zu." }, { title: "PLAN-AUSWAHL", desc: "Wählen Sie Ihre Kapitalallokationsstufe." }, { title: "API-EINSATZ", desc: "Automatisierte Verbindung zu globalen Märkten." }, { title: "AUSFÜHRUNG", desc: "Millisekunden-algorithmische Auftragsverarbeitung." }, { title: "BERICHTERSTATTUNG", desc: "Detaillierte wöchentliche Leistungsanalysen." }], cta: "BEREIT ZUM START?", ctaBtn: "DEM NETZWERK BEITRETEN" },
      about: { badge: "ERBE", title: "INSTITUTIONELLE", subtitle: "EXZELLENZ", desc: "Braxel Markets repräsentiert die Spitze des algorithmischen Kapitalmanagements.", historyTitle: "UNSERE GESCHICHTE", historyDesc1: "Gegründet von einem Team aus Quant-Analysten und Software-Ingenieuren, Braxel wurde geschaffen, um die Lücke zwischen Privatkapital und institutioneller Technologie zu schließen.", historyDesc2: "Heute verwalten wir Milliarden an Volumen mit Fokus auf risikoadjustierte Renditen und Infrastrukturstabilität.", stats: { founded: "Gegründet", users: "Aktive Nutzer", uptime: "Uptime", support: "Support" }, values: { mission: "MISSION", missionDesc: "Bereitstellung einer Elite-Infrastruktur für globales Kapital.", vision: "VISION", visionDesc: "Die Zukunft des automatisierten quantitativen Managements definieren.", values: "WERTE", valuesDesc: "Transparenz, Präzision und unerschütterliche Sicherheit." } },
      contact: { badge: "SUPPORT", title: "INSTITUTIONELLE", subtitle: "KANÄLE", desc: "Unser engagiertes Support-Team steht rund um die Uhr für institutionelle Anfragen zur Verfügung.", infoTitle: "KONTAKTINFO", formTitle: "DIREKTE ANFRAGE", placeholders: { name: "VOLLSTÄNDIGER NAME", email: "E-MAIL-ADRESSE", subject: "BETREFF", message: "NACHRICHT" }, sendBtn: "ANFRAGE SENDEN" },
      dashboard: { portfolio: "Portfolio", activeServices: "Aktive Dienste", newAllocation: "Neue Allokation", noServices: "Keine aktiven Investitionspläne gefunden.", balance: "Aktueller Kontostand", withdraw: "Auszahlung", liquidity: "Liquidität", requestWithdraw: "Auszahlung anfordern", selectAccount: "Konto auswählen", amount: "Betrag (USD)", iban: "IBAN / Bankdaten", btnWithdraw: "AUSZAHLUNGSANTRAG SENDEN", profile: "Profilverwaltung", settings: "Einstellungen", firstName: "Vorname", lastName: "Nachname", saveChanges: "ÄNDERUNGEN SPEICHERN" },
      checkout: { summary: "ZUSAMMENFASSUNG", finalize: "ALLOKATION ABSCHLIESSEN", managedCapital: "Verwaltetes Kapital", total: "GESAMT", securityDesc: "Ihre Transaktion ist durch AES-256-Verschlüsselung und institutionelle Sicherheitsprotokolle geschützt.", secure: "SICHERER CHECKOUT", authRequired: "AUTHENTIFIZIERUNG ERFORDERLICH", authDesc: "Bitte melden Sie sich an oder erstellen Sie ein Konto, um fortzufahren.", btnLogin: "ANMELDEN ZUM FORTFAHREN", btnRegister: "KONTO ERSTELLEN", loggedInAs: "ANGEMELDET ALS", footerNote: "Durch Fortfahren akzeptieren Sie unsere Nutzungsbedingungen und Risikohinweise." },
      legal: { badgeLegal: "RECHTLICHES", termsTitle: "NUTZUNGSBEDINGUNGEN" }
    }
  },
  ru: {
    translation: {
      nav: { pricing: "ИНВЕСТИЦИОННЫЕ ПЛАНЫ", howItWorks: "ИНФРАСТРУКТУРА", about: "НАШЕ НАСЛЕДИЕ", contact: "ИНСТИТУЦИОНАЛЬНАЯ ПОДДЕРЖКА", login: "ДОСТУП К ТЕРМИНАЛУ", openAccount: "СОЗДАТЬ АККАУНТ", dashboard: "ПАНЕЛЬ УПРАВЛЕНИЯ", logout: "ВЫЙТИ" },
      footer: { desc: "Инвестиционная инфраструктура институционального уровня. Собственные технологии для современного рынка.", platform: "Платформа", company: "Компания", support: "Цифровая поддержка", rights: "Все права защищены.", privacy: "Конфиденциальность", terms: "Условия", disclaimer: "Отказ от ответственности" },
      auth: { loginTitle: "Вход", loginSubtitle: "Введите свои учетные данные.", registerTitle: "Создать аккаунт", registerSubtitle: "Начните свой путь на институциональном рынке.", email: "Электронная почта", password: "Пароль", fullName: "Полное имя", forgotPassword: "Забыли пароль?", noAccount: "Нет аккаунта?", hasAccount: "Уже есть доступ?", btnAccess: "ВОЙТИ В АККАУНТ", btnCreate: "СОЗДАТЬ МОЙ АККАУНТ", termsAgree: "Я согласен с Условиями и Конфиденциальностью.", futureTitle: "Будущее", futureSubtitle: "инвестиций", features: ["Алгоритмы институционального уровня", "Продвинутая защита капитала", "Исполнение за миллисекунды", "Полная прозрачность"] },
      hero: { title1: "ЭЛИТНОЕ АЛГОРИТМИЧЕСКОЕ", title2: "УПРАВЛЕНИЕ КАПИТАЛОМ.", desc: "Используйте количественные стратегии институционального уровня, разработанные для современного рынка. Ощутите точность исполнения за миллисекунды.", getStarted: "ИЗУЧИТЬ ИНВЕСТИЦИОННЫЕ ПЛАНЫ", viewStrategies: "ТЕХНИЧЕСКАЯ МЕТОДОЛОГИЯ" },
      stats: { volume: "Общий объем управления", traders: "Активные инвесторы", uptime: "Время работы системы", latency: "Точность исполнения" },
      methodology: { badge: "МЕТОДОЛОГИЯ", title: "КВАНТОВЫЕ СТРАТЕГИИ", momentum: { title: "АНАЛИЗ МОМЕНТУМА", desc: "Идентификация высоковероятных трендов с помощью нейронных сетей.", f1: "Детекция трендов", f2: "Анализ объема", f3: "Распознавание паттернов" }, volatility: { title: "АДАПТАЦИЯ К ВОЛАТИЛЬНОСТИ", desc: "Динамическая корректировка экспозиции на основе рыночных условий.", f1: "Динамическое хеджирование", f2: "Адаптивные стопы", f3: "Мониторинг ликвидности" }, risk: { title: "МИНИМИЗАЦИЯ РИСКОВ", desc: "Многоуровневые протоколы защиты для сохранения капитала.", f1: "Контроль просадки", f2: "Корреляция активов", f3: "Стресс-тестирование" } },
      process_home: { badge: "ПРОЦЕСС", title: "ИНСТИТУЦИОНАЛЬНЫЙ", subtitle: "РАБОЧИЙ ПРОЦЕСС", step1: { title: "РЕГИСТРАЦИЯ", desc: "Безопасная регистрация и верификация личности." }, step2: { title: "РАСПРЕДЕЛЕНИЕ", desc: "Выбор уровня управляемого капитала." }, step3: { title: "ИНТЕГРАЦИЯ", desc: "Развертывание алгоритмической инфраструктуры." }, step4: { title: "МОНИТОРИНГ", desc: "Отслеживание показателей в реальном времени." }, step5: { title: "ЛИКВИДНОСТЬ", desc: "Протоколы беспрепятственного вывода прибыли." } },
      cta_home: { badge: "ВОЗМОЖНОСТЬ", title: "МАСШТАБИРУЙТЕ ВАШ", subtitle: "КАПИТАЛ", desc: "Присоединяйтесь к элитной группе инвесторов, использующих инфраструктуру Braxel.", btn: "НАЧАТЬ РАСПРЕДЕЛЕНИЕ", trust: "Безопасность институционального уровня" },
      pricing: { badge: "ПРОЗРАЧНОСТЬ", title: "РАСПРЕДЕЛЕНИЕ", subtitle: "КАПИТАЛА", desc: "Инфраструктура институционального уровня с прозрачной структурой комиссий.", select: "ВЫБРАТЬ ЭТОТ ПЛАН", allocation: "УПРАВЛЯЕМЫЙ КАПИТАЛ", month: "ежемесячный взнос" },
      howItWorks: { badge: "ИНФРАСТРУКТУРА", title: "ТЕХНИЧЕСКАЯ", subtitle: "АРХИТЕКТУРА", desc: "Наша экосистема создана для скорости, безопасности и стабильной работы.", steps: [{ title: "РЕГИСТРАЦИЯ", desc: "Создайте свой институциональный профиль." }, { title: "ПАНЕЛЬ", desc: "Доступ к приватному терминалу управления." }, { title: "ВЫБОР ПЛАНА", desc: "Выберите уровень распределения капитала." }, { title: "РАЗВЕРТЫВАНИЕ API", desc: "Автоматическое подключение к мировым рынкам." }, { title: "ИСПОЛНЕНИЕ", desc: "Алгоритмическая обработка ордеров за миллисекунды." }, { title: "ОТЧЕТНОСТЬ", desc: "Детальная еженедельная аналитика показателей." }], cta: "ГОТОВЫ К ЗАПУСКУ?", ctaBtn: "ПРИСОЕДИНИТЬСЯ К СЕТИ" },
      about: { badge: "НАСЛЕДИЕ", title: "ИНСТИТУЦИОНАЛЬНОЕ", subtitle: "ПРЕВОСХОДСТВО", desc: "Braxel Markets представляет собой вершину алгоритмического управления капиталом.", historyTitle: "НАША ИСТОРИЯ", historyDesc1: "Основанная командой квантовых аналитиков и инженеров, Braxel была создана для объединения частного капитала и институциональных технологий.", historyDesc2: "Сегодня мы управляем миллиардными объемами, фокусируясь на доходности с поправкой на риск.", stats: { founded: "Основано", users: "Активные пользователи", uptime: "Аптайм", support: "Поддержка" }, values: { mission: "МИССИЯ", missionDesc: "Предоставление элитной инфраструктуры для глобального капитала.", vision: "ВИДЕНИЕ", visionDesc: "Определение будущего автоматизированного квантового управления.", values: "ЦЕННОСТИ", valuesDesc: "Прозрачность, точность и непоколебимая безопасность." } },
      contact: { badge: "ПОДДЕРЖКА", title: "ИНСТИТУЦИОНАЛЬНЫЕ", subtitle: "КАНАЛЫ", desc: "Наша команда поддержки доступна 24/7 для институциональных запросов.", infoTitle: "КОНТАКТЫ", formTitle: "ПРЯМОЙ ЗАПРОС", placeholders: { name: "ПОЛНОЕ ИМЯ", email: "ЭЛЕКТРОННАЯ ПОЧТА", subject: "ТЕМА", message: "СООБЩЕНИЕ" }, sendBtn: "ОТПРАВИТЬ ЗАПРОС" },
      dashboard: { portfolio: "Портфель", activeServices: "Активные услуги", newAllocation: "Новое распределение", noServices: "Активные инвестиционные планы не найдены.", balance: "Текущий баланс", withdraw: "Вывод средств", liquidity: "Ликвидность", requestWithdraw: "Запросить вывод", selectAccount: "Выбрать счет", amount: "Сумма (USD)", iban: "IBAN / Банковские реквизиты", btnWithdraw: "ОТПРАВИТЬ ЗАПРОС НА ВЫВОД", profile: "Управление профилем", settings: "Настройки", firstName: "Имя", lastName: "Фамилия", saveChanges: "СОХРАНИТЬ ИЗМЕНЕНИЯ" },
      checkout: { summary: "ИТОГО", finalize: "ЗАВЕРШИТЬ РАСПРЕДЕЛЕНИЕ", managedCapital: "Управляемый капитал", total: "ИТОГО", securityDesc: "Ваша транзакция защищена шифрованием AES-256 и институциональными протоколами безопасности.", secure: "БЕЗОПАСНАЯ ОПЛАТА", authRequired: "ТРЕБУЕТСЯ АВТОРИЗАЦИЯ", authDesc: "Пожалуйста, войдите или создайте аккаунт, чтобы продолжить.", btnLogin: "ВОЙТИ ДЛЯ ПРОДОЛЖЕНИЯ", btnRegister: "СОЗДАТЬ АККАУНТ", loggedInAs: "ВЫ ВОШЛИ КАК", footerNote: "Продолжая, вы соглашаетесь с нашими Условиями обслуживания и Раскрытием рисков." },
      legal: { badgeLegal: "ЮРИДИЧЕСКАЯ ИНФОРМАЦИЯ", termsTitle: "УСЛОВИЯ ОБСЛУЖИВАНИЯ" }
    }
  },
  zh: {
    translation: {
      nav: { pricing: "投资计划", howItWorks: "基础设施", about: "我们的传承", contact: "机构支持", login: "终端访问", openAccount: "创建账户", dashboard: "仪表板", logout: "登出" },
      footer: { desc: "机构级投资基础设施。现代市场的专有技术。", platform: "平台", company: "公司", support: "数字支持", rights: "版权所有。", privacy: "隐私", terms: "条款", disclaimer: "免责声明" },
      auth: { loginTitle: "登录", loginSubtitle: "输入您的访问凭据。", registerTitle: "创建账户", registerSubtitle: "开始您的机构市场之旅。", email: "电子邮件地址", password: "密码", fullName: "全名", forgotPassword: "忘记密码？", noAccount: "没有账户？", hasAccount: "已有访问权限？", btnAccess: "访问账户", btnCreate: "创建我的账户", termsAgree: "我同意条款和隐私政策。", futureTitle: "投资的", futureSubtitle: "未来", features: ["机构级算法", "先进的资本保护", "毫秒级执行", "完全透明"] },
      hero: { title1: "精英算法", title2: "资本管理。", desc: "部署为现代市场设计的机构级量化策略。体验毫秒级的执行精度和先进的风险缓解协议。", getStarted: "探索投资计划", viewStrategies: "技术方法论" },
      stats: { volume: "总管理量", traders: "全球活跃投资者", uptime: "基础设施运行时间", latency: "执行精度" },
      methodology: { badge: "方法论", title: "量化策略", momentum: { title: "动量分析", desc: "使用专有神经网络识别高概率趋势。", f1: "趋势检测", f2: "成交量分析", f3: "模式识别" }, volatility: { title: "波动率适应", desc: "根据实时市场状况动态调整风险敞口。", f1: "动态对冲", f2: "自适应止损", f3: "流动性监控" }, risk: { title: "风险缓解", desc: "多层保护协议确保资本保全。", f1: "回撤控制", f2: "资产相关性", f3: "压力测试" } },
      process_home: { badge: "流程", title: "机构级", subtitle: "工作流", step1: { title: "注册", desc: "安全的入驻和身份验证。" }, step2: { title: "分配", desc: "选择管理资本等级。" }, step3: { title: "集成", desc: "部署算法基础设施。" }, step4: { title: "监控", desc: "通过终端进行实时性能跟踪。" }, step5: { title: "流动性", desc: "无缝的利润提取协议。" } },
      cta_home: { badge: "机遇", title: "扩展您的", subtitle: "资本", desc: "加入利用 Braxel 专有基础设施的精英投资者群体。", btn: "开始分配", trust: "机构级安全保障" },
      pricing: { badge: "透明度", title: "资本", subtitle: "分配", desc: "具有透明费用结构的机构级基础设施。", select: "确保此计划", allocation: "管理资本", month: "月费" },
      howItWorks: { badge: "基础设施", title: "技术", subtitle: "架构", desc: "我们的专有生态系统专为速度、安全和持续性能而构建。", steps: [{ title: "注册", desc: "创建您的机构资料。" }, { title: "仪表板", desc: "访问您的私人管理终端。" }, { title: "计划选择", desc: "选择您的资本分配等级。" }, { title: "API 部署", desc: "自动连接到全球市场。" }, { title: "执行", desc: "毫秒级算法交易处理。" }, { title: "报告", desc: "详细的每周性能分析。" }], cta: "准备好部署了吗？", ctaBtn: "加入网络" },
      about: { badge: "传承", title: "机构级", subtitle: "卓越", desc: "Braxel Markets 代表了算法资本管理的巅峰。", historyTitle: "我们的历史", historyDesc1: "由量化分析师和软件工程师团队创立，Braxel 旨在弥合零售资本与机构技术之间的鸿沟。", historyDesc2: "今天，我们管理着数十亿的交易量，专注于风险调整后的回报和基础设施的稳定性。", stats: { founded: "成立于", users: "活跃用户", uptime: "运行时间", support: "支持" }, values: { mission: "使命", missionDesc: "为全球资本提供精英算法基础设施。", vision: "愿景", visionDesc: "定义自动化量化管理的未来。", values: "价值观", valuesDesc: "透明、精准和坚定的安全。" } },
      contact: { badge: "支持", title: "机构级", subtitle: "渠道", desc: "我们的专业支持团队 24/7 为机构咨询提供服务。", infoTitle: "联系信息", formTitle: "直接咨询", placeholders: { name: "全名", email: "电子邮件地址", subject: "主题", message: "信息" }, sendBtn: "发送咨询" },
      dashboard: { portfolio: "投资组合", activeServices: "活跃服务", newAllocation: "新分配", noServices: "未发现活跃的投资计划。", balance: "当前余额", withdraw: "提款", liquidity: "流动性", requestWithdraw: "申请提款", selectAccount: "选择账户", amount: "金额 (USD)", iban: "IBAN / 银行详情", btnWithdraw: "提交提款申请", profile: "个人资料管理", settings: "设置", firstName: "名字", lastName: "姓氏", saveChanges: "保存更改" },
      checkout: { summary: "摘要", finalize: "完成分配", managedCapital: "管理资本", total: "总计", securityDesc: "您的交易受 AES-256 加密和机构安全协议保护。", secure: "安全结账", authRequired: "需要身份验证", authDesc: "请登录或创建账户以继续分配。", btnLogin: "登录以继续", btnRegister: "创建账户", loggedInAs: "登录身份为", footerNote: "继续操作即表示您同意我们的服务条款和风险披露。" },
      legal: { badgeLegal: "法律", termsTitle: "服务条款" }
    }
  },
  ja: {
    translation: {
      nav: { pricing: "投資プラン", howItWorks: "インフラストラクチャ", about: "私たちの遺産", contact: "機関サポート", login: "ターミナルアクセス", openAccount: "アカウント作成", dashboard: "ダッシュボード", logout: "ログアウト" },
      footer: { desc: "機関投資家レベルの投資インフラ。現代市場向けの独自技術。", platform: "プラットフォーム", company: "会社", support: "デジタルサポート", rights: "全著作権所有。", privacy: "プライバシー", terms: "規約", disclaimer: "免責事項" },
      auth: { loginTitle: "ログイン", loginSubtitle: "アクセス資格情報を入力してください。", registerTitle: "アカウント作成", registerSubtitle: "機関投資家市場での旅を始めましょう。", email: "メールアドレス", password: "パスワード", fullName: "氏名", forgotPassword: "パスワードをお忘れですか？", noAccount: "アカウントをお持ちではありませんか？", hasAccount: "すでにアクセス権をお持ちですか？", btnAccess: "アカウントにアクセス", btnCreate: "アカウントを作成する", termsAgree: "規約とプライバシーに同意します。", futureTitle: "投資の", futureSubtitle: "未来", features: ["機関投資家レベルのアルゴリズム", "高度な資本保護", "ミリ秒単位の実行", "完全な透明性"] },
      hero: { title1: "エリート・アルゴリズム", title2: "資本管理。", desc: "現代市場向けに設計された機関投資家レベルの計量戦略を展開します。ミリ秒単位の実行精度と高度なリスク軽減プロトコルを体験してください。", getStarted: "投資プランを探索する", viewStrategies: "技術的方法論" },
      stats: { volume: "総運用資産", traders: "グローバル・アクティブ投資家", uptime: "インフラ稼働率", latency: "実行精度" },
      methodology: { badge: "方法論", title: "計量戦略", momentum: { title: "モメンタム分析", desc: "独自のニューラルネットワークを使用した高確率トレンドの特定。", f1: "トレンド検出", f2: "出来高分析", f3: "パターン認識" }, volatility: { title: "ボラティリティ適応", desc: "リアルタイムの市場状況に基づくエクスポージャーの動的調整。", f1: "動的ヘッジ", f2: "適応型ストップ", f3: "流動性監視" }, risk: { title: "リスク軽減", desc: "資本保全を確実にするための多層保護プロトコル。", f1: "ドローダウン制御", f2: "資産相関", f3: "ストレステスト" } },
      process_home: { badge: "プロセス", title: "機関投資家向け", subtitle: "ワークフロー", step1: { title: "登録", desc: "安全なオンボーディングと本人確認。" }, step2: { title: "配分", desc: "運用資本レベルの選択。" }, step3: { title: "統合", desc: "アルゴリズムインフラの展開。" }, step4: { title: "監視", desc: "ターミナルによるリアルタイムのパフォーマンス追跡。" }, step5: { title: "流動性", desc: "シームレスな利益出金プロトコル。" } },
      cta_home: { badge: "機会", title: "資本を", subtitle: "拡大する", desc: "Braxel独自のインフラを利用するエリート投資家グループに参加してください。", btn: "配分を開始する", trust: "機関投資家レベルのセキュリティ" },
      pricing: { badge: "透明性", title: "資本", subtitle: "配分", desc: "透明な手数料体系を備えた機関投資家レベルのインフラ。", select: "このプランを確保する", allocation: "運用資本", month: "月額料金" },
      howItWorks: { badge: "インフラ", title: "技術的", subtitle: "アーキテクチャ", desc: "当社の独自エコシステムは、速度、セキュリティ、一貫したパフォーマンスのために構築されています。", steps: [{ title: "登録", desc: "機関投資家プロフィールを作成します。" }, { title: "ダッシュボード", desc: "プライベート管理ターミナルにアクセスします。" }, { title: "プラン選択", desc: "資本配分レベルを選択します。" }, { title: "API展開", desc: "グローバル市場への自動接続。" }, { title: "実行", desc: "ミリ秒単位のアルゴリズム注文処理。" }, { title: "レポート", desc: "詳細な週次パフォーマンス分析。" }], cta: "展開の準備はできましたか？", ctaBtn: "ネットワークに参加" },
      about: { badge: "遺産", title: "機関投資家としての", subtitle: "卓越性", desc: "Braxel Marketsは、アルゴリズム資本管理の頂点を象徴しています。", historyTitle: "私たちの歴史", historyDesc1: "計量分析家とソフトウェアエンジニアのチームによって設立されたBraxelは、個人資本と機関技術の架け橋となるために作られました。", historyDesc2: "今日、私たちはリスク調整後リターンとインフラの安定性に焦点を当て、数十億のボリュームを管理しています。", stats: { founded: "設立", users: "アクティブユーザー", uptime: "稼働率", support: "サポート" }, values: { mission: "ミッション", missionDesc: "グローバル資本にエリートアルゴリズムインフラを提供すること。", vision: "ビジョン", visionDesc: "自動化された計量管理の未来を定義すること。", values: "価値観", valuesDesc: "透明性、精度、そして揺るぎないセキュリティ。" } },
      contact: { badge: "サポート", title: "機関投資家向け", subtitle: "チャネル", desc: "当社の専任サポートチームは、機関投資家からのお問い合わせに24時間365日対応しています。", infoTitle: "連絡先情報", formTitle: "直接お問い合わせ", placeholders: { name: "氏名", email: "メールアドレス", subject: "件名", message: "メッセージ" }, sendBtn: "お問い合わせを送信" },
      dashboard: { portfolio: "ポートフォリオ", activeServices: "アクティブなサービス", newAllocation: "新規配分", noServices: "アクティブな投資プランが見つかりません。", balance: "現在の残高", withdraw: "出金", liquidity: "流動性", requestWithdraw: "出金をリクエストする", selectAccount: "アカウントを選択", amount: "金額 (USD)", iban: "IBAN / 銀行詳細", btnWithdraw: "出金リクエストを送信", profile: "プロフィール管理", settings: "設定", firstName: "名", lastName: "姓", saveChanges: "変更を保存" },
      checkout: { summary: "概要", finalize: "配分を完了する", managedCapital: "運用資本", total: "合計", securityDesc: "お客様の取引はAES-256暗号化と機関セキュリティプロトコルによって保護されています。", secure: "安全なチェックアウト", authRequired: "認証が必要です", authDesc: "配分を進めるには、ログインまたはアカウント作成を行ってください。", btnLogin: "ログインして続行", btnRegister: "アカウント作成", loggedInAs: "ログイン中:", footerNote: "続行することにより、利用規約とリスク開示に同意したことになります。" },
      legal: { badgeLegal: "法務", termsTitle: "利用規約" }
    }
  },
  ar: {
    translation: {
      nav: { pricing: "خطط الاستثمار", howItWorks: "البنية التحتية", about: "إرثنا", contact: "الدعم المؤسسي", login: "الوصول إلى المحطة", openAccount: "إنشاء حساب", dashboard: "لوحة القيادة", logout: "تسجيل الخروج" },
      footer: { desc: "بنية تحتية استثمارية مؤسسية. تكنولوجيا خاصة للسوق الحديث.", platform: "المنصة", company: "الشركة", support: "الدعم الرقمي", rights: "جميع الحقوق محفوظة.", privacy: "الخصوصية", terms: "الشروط", disclaimer: "إخلاء المسؤولية المالية" },
      auth: { loginTitle: "تسجيل الدخول", loginSubtitle: "أدخل بيانات الاعتماد الخاصة بك.", registerTitle: "إنشاء حساب", registerSubtitle: "ابدأ رحلتك في السوق المؤسسي.", email: "البريد الإلكتروني", password: "كلمة المرور", fullName: "الاسم الكامل", forgotPassword: "هل نسيت كلمة المرور؟", noAccount: "ليس لديك حساب؟", hasAccount: "لديك وصول بالفعل؟", btnAccess: "الوصول إلى الحساب", btnCreate: "إنشاء حسابي", termsAgree: "أوافق على الشروط والخصوصية.", futureTitle: "مستقبل", futureSubtitle: "الاستثمار", features: ["خوارزميات مؤسسية", "حماية متقدمة لرأس المال", "تنفيذ في أجزاء من الثانية", "شفافية كاملة"] },
      hero: { title1: "إدارة رأس المال", title2: "الخوارزمية النخبوية.", desc: "نشر استراتيجيات كمية مؤسسية مصممة للسوق الحديث. جرب دقة التنفيذ في أجزاء من الثانية وبروتوكولات تخفيف المخاطر المتقدمة.", getStarted: "استكشاف خطط الاستثمار", viewStrategies: "المنهجية التقنية" },
      stats: { volume: "إجمالي حجم الإدارة", traders: "المستثمرون النشطون عالمياً", uptime: "وقت تشغيل البنية التحتية", latency: "دقة التنفيذ" },
      methodology: { badge: "المنهجية", title: "الاستراتيجيات الكمية", momentum: { title: "تحليل الزخم", desc: "تحديد الاتجاهات عالية الاحتمالية باستخدام شبكات عصبية خاصة.", f1: "كشف الاتجاه", f2: "تحليل الحجم", f3: "التعرف على الأنماط" }, volatility: { title: "التكيف مع التقلبات", desc: "تعديل ديناميكي للتعرض بناءً على ظروف السوق في الوقت الفعلي.", f1: "التحوط الديناميكي", f2: "أوامر وقف متكيفة", f3: "مراقبة السيولة" }, risk: { title: "تخفيف المخاطر", desc: "بروتوكولات حماية متعددة الطبقات لضمان الحفاظ على رأس المال.", f1: "التحكم في التراجع", f2: "ارتباط الأصول", f3: "اختبار الإجهاد" } },
      process_home: { badge: "العملية", title: "سير العمل", subtitle: "المؤسسي", step1: { title: "التسجيل", desc: "انضمام آمن والتحقق من الهوية." }, step2: { title: "التخصيص", desc: "اختيار مستوى رأس المال المدار." }, step3: { title: "التكامل", desc: "نشر البنية التحتية الخوارزمية." }, step4: { title: "المراقبة", desc: "تتبع الأداء في الوقت الفعلي عبر المحطة." }, step5: { title: "السيولة", desc: "بروتوكولات سحب أرباح سلسة." } },
      cta_home: { badge: "فرصة", title: "ضاعف رأس", subtitle: "مالك", desc: "انضم إلى مجموعة النخبة من المستثمرين الذين يستخدمون بنية Braxel التحتية.", btn: "ابدأ التخصيص", trust: "أمن على مستوى مؤسسي" },
      pricing: { badge: "الشفافية", title: "تخصيص", subtitle: "رأس المال", desc: "بنية تحتية مؤسسية مع هيكل رسوم شفاف.", select: "تأمين هذه الخطة", allocation: "رأس المال المدار", month: "رسوم شهرية" },
      howItWorks: { badge: "البنية التحتية", title: "الهندسة", subtitle: "التقنية", desc: "تم بناء نظامنا البيئي الخاص من أجل السرعة والأمان والأداء المستمر.", steps: [{ title: "التسجيل", desc: "أنشئ ملفك الشخصي المؤسسي." }, { title: "لوحة القيادة", desc: "الوصول إلى محطة الإدارة الخاصة بك." }, { title: "اختيار الخطة", desc: "اختر مستوى تخصيص رأس المال الخاص بك." }, { title: "نشر API", desc: "اتصال آلي بالأسواق العالمية." }, { title: "التنفيذ", desc: "معالجة أوامر خوارزمية في أجزاء من الثانية." }, { title: "التقارير", desc: "تحليلات أداء أسبوعية مفصلة." }], cta: "جاهز للبدء؟", ctaBtn: "انضم إلى الشبكة" },
      about: { badge: "الإرث", title: "التميز", subtitle: "المؤسسي", desc: "تمثل Braxel Markets قمة إدارة رأس المال الخوارزمية.", historyTitle: "تاريخنا", historyDesc1: "تأسست Braxel على يد فريق من المحللين الكميين ومهندسي البرمجيات لسد الفجوة بين رأس المال الفردي والتكنولوجيا المؤسسية.", historyDesc2: "اليوم، ندير مليارات الأحجام مع التركيز على العوائد المعدلة حسب المخاطر واستقرار البنية التحتية.", stats: { founded: "تأسست", users: "المستخدمون النشطون", uptime: "وقت التشغيل", support: "الدعم" }, values: { mission: "المهمة", missionDesc: "توفير بنية تحتية خوارزمية نخبوية لرأس المال العالمي.", vision: "الرؤية", visionDesc: "تحديد مستقبل الإدارة الكمية الآلية.", values: "القيم", valuesDesc: "الشفافية والدقة والأمن الراسخ." } },
      contact: { badge: "الدعم", title: "القنوات", subtitle: "المؤسسية", desc: "فريق الدعم المخصص لدينا متاح 24/7 للاستفسارات المؤسسية.", infoTitle: "معلومات الاتصال", formTitle: "استفسار مباشر", placeholders: { name: "الاسم الكامل", email: "البريد الإلكتروني", subject: "الموضوع", message: "الرسالة" }, sendBtn: "إرسال الاستفسار" },
      dashboard: { portfolio: "المحفظة", activeServices: "الخدمات النشطة", newAllocation: "تخصيص جديد", noServices: "لم يتم العثور على خطط استثمار نشطة.", balance: "الرصيد الحالي", withdraw: "سحب الأموال", liquidity: "السيولة", requestWithdraw: "طلب سحب", selectAccount: "اختر الحساب", amount: "المبلغ (USD)", iban: "IBAN / تفاصيل البنك", btnWithdraw: "إرسال طلب السحب", profile: "إدارة الملف الشخصي", settings: "الإعدادات", firstName: "الاسم الأول", lastName: "اسم العائلة", saveChanges: "حفظ التغييرات" },
      checkout: { summary: "الملخص", finalize: "إنهاء التخصيص", managedCapital: "رأس المال المدار", total: "الإجمالي", securityDesc: "معاملتك محمية بتشفير AES-256 وبروتوكولات أمنية مؤسسية.", secure: "دفع آمن", authRequired: "المصادقة مطلوبة", authDesc: "يرجى تسجيل الدخول أو إنشاء حساب للمتابعة.", btnLogin: "تسجيل الدخول للمتابعة", btnRegister: "إنشاء حساب", loggedInAs: "مسجل الدخول باسم", footerNote: "بالمتابعة، فإنك توافق على شروط الخدمة وإخلاء المسؤولية عن المخاطر." },
      legal: { badgeLegal: "قانوني", termsTitle: "شروط الخدمة" }
    }
  },
  he: {
    translation: {
      nav: { pricing: "תוכניות השקעה", howItWorks: "התשתית", about: "המורשת שלנו", contact: "תמיכה מוסדית", login: "גישה למסוף", openAccount: "יצירת חשבון", dashboard: "לוח בקרה", logout: "התנתק" },
      footer: { desc: "תשתית השקעות ברמה מוסדית. טכנולוגיה קניינית לשוק המודרני.", platform: "פלטפורמה", company: "חברה", support: "תמיכה דיגיטלית", rights: "כל הזכויות שמורות.", privacy: "פרטיות", terms: "תנאים", disclaimer: "הצהרת סיכון פיננסי" },
      auth: { loginTitle: "התחברות", loginSubtitle: "הזן את פרטי הגישה שלך.", registerTitle: "יצירת חשבון", registerSubtitle: "התחל את המסע שלך בשוק המוסדי.", email: "כתובת אימייל", password: "סיסמה", fullName: "שם מלא", forgotPassword: "שכחת סיסמה?", noAccount: "אין לך חשבון?", hasAccount: "כבר יש לך גישה?", btnAccess: "גישה לחשבון", btnCreate: "צור את החשבון שלי", termsAgree: "אני מסכים לתנאים ולפרטיות.", futureTitle: "העתיד של", futureSubtitle: "ההשקעות", features: ["אלגוריתמים ברמה מוסדית", "הגנת הון מתקדמת", "ביצוע במילישניות", "שקיפות מלאה"] },
      hero: { title1: "ניהול הון", title2: "אלגוריתמי עילית.", desc: "פרוס אסטרטגיות כמותיות ברמה מוסדית המיועדות לשוק המודרני. חווה דיוק ביצוע במילישניות ופרוטוקולי הפחתת סיכונים מתקדמים.", getStarted: "חקור תוכניות השקעה", viewStrategies: "מתודולוגיה טכנית" },
      stats: { volume: "סך נפח מנוהל", traders: "משקיעים פעילים גלובליים", uptime: "זמן פעילות תשתית", latency: "דיוק ביצוע" },
      methodology: { badge: "מתודולוגיה", title: "אסטרטגיות כמותיות", momentum: { title: "ניתוח מומנטום", desc: "זיהוי מגמות בהסתברות גבוהה באמצעות רשתות עצביות קנייניות.", f1: "זיהוי מגמות", f2: "ניתוח נפח", f3: "זיהוי תבניות" }, volatility: { title: "התאמה לתנודתיות", desc: "התאמה דינמית של החשיפה בהתבסס על תנאי השוק בזמן אמת.", f1: "גידור דינמי", f2: "סטופים אדפטיביים", f3: "ניטור נזילות" }, risk: { title: "הפחתת סיכונים", desc: "פרוטוקולי הגנה רב-שכבתיים להבטחת שימור ההון.", f1: "בקרת דראודאון", f2: "קורלציית נכסים", f3: "מבחני קיצון" } },
      process_home: { badge: "תהליך", title: "זרימת עבודה", subtitle: "מוסדית", step1: { title: "הרשמה", desc: "תהליך הצטרפות מאובטח ואימות זהות." }, step2: { title: "הקצאה", desc: "בחירת רמת ההון המנוהל." }, step3: { title: "אינטגרציה", desc: "פריסת התשתית האלגוריתמית." }, step4: { title: "ניטור", desc: "מעקב ביצועים בזמן אמת באמצעות המסוף." }, step5: { title: "נזילות", desc: "פרוטוקולי משיכת רווחים חלקים." } },
      cta_home: { badge: "הזדמנות", title: "הגדל את", subtitle: "ההון שלך", desc: "הצטרף לקבוצת העילית של משקיעים המשתמשים בתשתית הקניינית של Braxel.", btn: "התחל הקצאה", trust: "אבטחה ברמה מוסדית" },
      pricing: { badge: "שקיפות", title: "הקצאות", subtitle: "הון", desc: "תשתית ברמה מוסדית עם מבנה עמלות שקוף.", select: "אבטח תוכנית זו", allocation: "הון מנוהל", month: "עמלה חודשית" },
      howItWorks: { badge: "תשתית", title: "ארכיטקטורה", subtitle: "טכנית", desc: "המערכת הקניינית שלנו בנויה למהירות, אבטחה וביצועים עקביים.", steps: [{ title: "הרשמה", desc: "צור את הפרופיל המוסדי שלך." }, { title: "לוח בקרה", desc: "גישה למסוף הניהול הפרטי שלך." }, { title: "בחירת תוכנית", desc: "בחר את רמת הקצאת ההון שלך." }, { title: "פריסת API", desc: "חיבור אוטומטי לשווקים גלובליים." }, { title: "ביצוע", desc: "עיבוד פקודות אלגוריתמי במילישניות." }, { title: "דיווח", desc: "ניתוח ביצועים שבועי מפורט." }], cta: "מוכן להתחיל?", ctaBtn: "הצטרף לרשת" },
      about: { badge: "מורשת", title: "מצוינות", subtitle: "מוסדית", desc: "Braxel Markets מייצגת את פסגת ניהול ההון האלגוריתמי.", historyTitle: "ההיסטוריה שלנו", historyDesc1: "הוקמה על ידי צוות של אנליסטים כמותיים ומהנדסי תוכנה, Braxel נבנתה כדי לגשר על הפער בין הון פרטי לטכנולוגיה מוסדית.", historyDesc2: "כיום אנו מנהלים מיליארדים בנפח מסחר עם דגש על תשואות מותאמות סיכון ויציבות תשתית.", stats: { founded: "נוסדה", users: "משתמשים פעילים", uptime: "זמן פעילות", support: "תמיכה" }, values: { mission: "משימה", missionDesc: "לספק תשתית אלגוריתמית עילית להון גלובלי.", vision: "חזון", visionDesc: "להגדיר את העתיד של ניהול כמותי אוטומטי.", values: "ערכים", valuesDesc: "שקיפות, דיוק ואבטחה בלתי מתפשרת." } },
      contact: { badge: "תמיכה", title: "ערוצים", subtitle: "מוסדיים", desc: "צוות התמיכה הייעודי שלנו זמין 24/7 לפניות מוסדיות.", infoTitle: "פרטי קשר", formTitle: "פנייה ישירה", placeholders: { name: "שם מלא", email: "כתובת אימייל", subject: "נושא", message: "הודעה" }, sendBtn: "שלח פנייה" },
      dashboard: { portfolio: "תיק השקעות", activeServices: "שירותים פעילים", newAllocation: "הקצאה חדשה", noServices: "לא נמצאו תוכניות השקעה פעילות.", balance: "יתרה נוכחית", withdraw: "משיכה", liquidity: "נזילות", requestWithdraw: "בקש משיכה", selectAccount: "בחר חשבון", amount: "סכום (USD)", iban: "IBAN / פרטי בנק", btnWithdraw: "שלח בקשת משיכה", profile: "ניהול פרופיל", settings: "הגדרות", firstName: "שם פרטי", lastName: "שם משפחה", saveChanges: "שמור שינויים" },
      checkout: { summary: "סיכום", finalize: "סיום הקצאה", managedCapital: "הון מנוהל", total: "סה\"כ", securityDesc: "העסקה שלך מוגנת על ידי הצפנת AES-256 ופרוטוקולי אבטחה מוסדיים.", secure: "תשלום מאובטח", authRequired: "נדרש אימות", authDesc: "אנא התחבר או צור חשבון כדי להמשיך בהקצאה.", btnLogin: "התחבר להמשך", btnRegister: "צור חשבון", loggedInAs: "מחובר כ-", footerNote: "בהמשך התהליך, אתה מסכים לתנאי השירות ולגילוי הסיכונים שלנו." },
      legal: { badgeLegal: "משפטי", termsTitle: "תנאי שימוש" }
    }
  }
};

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: 'en',
    debug: false,
    detection: {
      order: ['localStorage', 'cookie', 'sessionStorage', 'navigator'],
      caches: ['localStorage', 'cookie'],
    },
    interpolation: {
      escapeValue: false,
    }
  }, (err, t) => {
    if (err) return console.error(err);
    document.documentElement.lang = i18n.language;
  });

i18n.on('languageChanged', (lng) => {
  document.documentElement.lang = lng;
});

export default i18n;