// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ymzdxifedtjwkxkzfwqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltemR4aWZlZHRqd2t4a3pmd3F1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwOTQ5NTMsImV4cCI6MjA4ODY3MDk1M30.zoiG08eJ3bhp4wKXk8L_P9NH1dYpbP4ta92yrRpHIfk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'braxel-auth-session',
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
  }
});
